### ISSUE TITLE
User type 'User' cannot share password with collection

### ISSUE THREAD

**Issue by syserr0r** [dani-garcia/vaultwarden#157]
A user who has access to the collection (and not 'Readonly') cannot share a password with that collection -- when attempting to do so the following error is shown:
![image](https://user-images.githubusercontent.com/2324422/44736330-d5256d80-aae6-11e8-970a-ca98cee358ce.png)

The only work-around is to set the user type to 'Admin' (or 'Owner'), however this allows access to all collections regardless of the explicit collection permissions

**Comment by syserr0r** [comment]
The issue seems to be the `has_full_access()` check here:
https://github.com/dani-garcia/bitwarden_rs/blob/781056152a4b8e5b6bc70031aafd65bf9d59fd1c/src/api/core/ciphers.rs#L140-L145

**Comment by mprasil** [comment]
Yeah we seem to call the function from here:
https://github.com/dani-garcia/bitwarden_rs/blob/781056152a4b8e5b6bc70031aafd65bf9d59fd1c/src/api/core/ciphers.rs#L425-L440

We do check the collection access later, so in this case we might need to somehow relay the information to the function we call, that user doesn't need write access to the entire organization as we will add it to collection later. (and maybe we should do that part first, that way if the collection stuff fails for whatever reason, we won't add the cipher to the organization direct for user that might not have the rights)

**Comment by durd** [comment]
Sorry to reopen this, we are experiencing this issue aswell, albeit it with a different error but same meaning. I do get the same error when trying to remove the item from a collection, not sure if that is intended even if I have write access.

We are running 2.10.1 from docker bitwardenrs/server:latest on Debian 10.

![Screenshot 2019-07-22 at 17 25 49](https://user-images.githubusercontent.com/8933824/61645705-8311ab80-aca7-11e9-9673-5560b1e885ad.png)
