### ISSUE TITLE
unable to build web-vault

### ISSUE THREAD

**Issue by rapkin61** [dani-garcia/vaultwarden#1657]
**git clone --recurse-submodules https://github.com/bitwarden/web.git web-vault**
Cloning into 'web-vault'...
remote: Enumerating objects: 26356, done.
remote: Counting objects: 100% (940/940), done.
remote: Compressing objects: 100% (437/437), done.
remote: Total 26356 (delta 597), reused 775 (delta 485), pack-reused 25416
Receiving objects: 100% (26356/26356), 132.85 MiB | 5.99 MiB/s, done.
Resolving deltas: 100% (19172/19172), done.
Submodule 'jslib' (https://github.com/bitwarden/jslib.git) registered for path 'jslib'
Cloning into '/home/klaus/web-vault/jslib'...
remote: Enumerating objects: 10753, done.        
remote: Counting objects: 100% (1253/1253), done.        
remote: Compressing objects: 100% (641/641), done.        
remote: Total 10753 (delta 724), reused 1029 (delta 574), pack-reused 9500        
Receiving objects: 100% (10753/10753), 3.42 MiB | 5.69 MiB/s, done.
Resolving deltas: 100% (7805/7805), done.
Submodule path 'jslib': checked out '4eb50d757d03343ee842ea68a6b2c8282ef3f382'
**cd web-vault/**
**git checkout "$(git tag --sort=v:refname | tail -n1)"**
M	jslib
Note: checking out 'v2.19.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 9d42a565 update jslib

....so ... this is v2.19 - we need to apply patch for that

**git apply v2.19.0.patch** 

**npm install**

 node-sass@4.13.1 install /home/klaus/web-vault/node_modules/node-sass
 node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/linux-x64-67_binding.node
Download complete .] - :
Binary saved to /home/klaus/web-vault/node_modules/node-sass/vendor/linux-x64-67/binding.node
Caching binary to /home/klaus/.npm/node-sass/4.13.1/linux-x64-67_binding.node

 ngx-infinite-scroll@7.0.1 postinstall /home/klaus/web-vault/node_modules/ngx-infinite-scroll
 opencollective postinstall

                                          Thanks for installing ngx-infinite-scroll 
                                        Please consider donating to our open collective
                                               to help us maintain this package.

                                                   Number of contributors: 0
                                                     Number of backers: 7
                                                     Annual budget: US$ 29
                                                   Current balance: US$ 189

                             Donate: https://opencollective.com/ngx-infinite-scroll/donate

 node-sass@4.13.1 postinstall /home/klaus/web-vault/node_modules/node-sass
 node scripts/build.js

Binary found at /home/klaus/web-vault/node_modules/node-sass/vendor/linux-x64-67/binding.node
Testing binary
Binary is fine

 webpack-cli@3.2.1 postinstall /home/klaus/web-vault/node_modules/webpack-cli
 lightercollective

     *** Thank you for using webpack-cli! ***

Please consider donating to our open collective
     to help us maintain this package.

  https://opencollective.com/webpack/donate

                    ***

 bitwarden-web@2.19.0 postinstall /home/klaus/web-vault
 npm run sub:init

 bitwarden-web@2.19.0 sub:init /home/klaus/web-vault
 git submodule update --init --recursive

error: Your local changes to the following files would be overwritten by checkout:
	src/angular/components/register.component.ts
Please commit your changes or stash them before you switch branches.
Aborting
Unable to checkout 'f80e89465ffc004705d2941301c0ffb6bfd71d1a' in submodule path 'jslib'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitwarden-web@2.19.0 sub:init: `git submodule update --init --recursive`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bitwarden-web@2.19.0 sub:init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/klaus/.npm/_logs/2021-05-03T09_24_53_641Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitwarden-web@2.19.0 postinstall: `npm run sub:init`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bitwarden-web@2.19.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/klaus/.npm/_logs/2021-05-03T09_24_53_671Z-debug.log

**Comment by rapkin61** [comment]
...excuse me for that strange kind of formatting!
How can I switch that off?

**Comment by Arathen** [comment]
This is a +1 for me as well. Im also getting the exact same error when trying to build the web vault.

`
arathen@ubuntu98 ~/src/web-vault $ npm install

  bitwarden-web@2.19.0 postinstall /home/arathen/src/web-vault
  npm run sub:init


  bitwarden-web@2.19.0 sub:init /home/arathen/src/web-vault
  git submodule update --init --recursive

error: Your local changes to the following files would be overwritten by checkout:
        src/angular/components/register.component.ts
Please commit your changes or stash them before you switch branches.
Aborting
Unable to checkout 'f80e89465ffc004705d2941301c0ffb6bfd71d1a' in submodule path 'jslib'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitwarden-web@2.19.0 sub:init: git submodule update --init --recursive
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bitwarden-web@2.19.0 sub:init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arathen/.npm/_logs/2021-05-04T22_25_28_504Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitwarden-web@2.19.0 postinstall: npm run sub:init
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bitwarden-web@2.19.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arathen/.npm/_logs/2021-05-04T22_25_28_979Z-debug.log
arathen@ubuntu98 ~/src/web-vault $ git status
HEAD detached at v2.19.0
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
        modified:   jslib (new commits, modified content)
        modified:   package-lock.json
        modified:   src/404.html
        modified:   src/app/app.component.ts
        modified:   src/app/layouts/footer.component.html
        modified:   src/app/layouts/frontend-layout.component.html
        modified:   src/app/layouts/navbar.component.html
        modified:   src/app/organizations/settings/organization-subscription.component.ts
        modified:   src/app/send/access.component.html
        modified:   src/app/services/services.module.ts
        modified:   src/app/settings/two-factor-u2f.component.ts
        modified:   src/scss/styles.scss

no changes added to commit (use "git add" and/or "git commit -a")
arathen@ubuntu98 ~/src/web-vault $ git show
commit 9d42a565dbef29c5c361dbe5b3db88d765d65a98 (HEAD, tag: v2.19.0)
Author: Kyle Spearrin <kyle.spearrin@gmail.com>
Date:   Thu Mar 11 10:49:49 2021 -0500

  update jslib

diff --git a/jslib b/jslib
index f29afc7c..f80e8946 160000
--- a/jslib
+++ b/jslib
@@ -1 +1 @@
-Subproject commit f29afc7cf7bbd514d07c0354b3c45491dcae3c14
+Subproject commit f80e89465ffc004705d2941301c0ffb6bfd71d1a
`
