### ISSUE TITLE
chrome extension unexpectedly logout when trying to modify data.

### ISSUE THREAD

**Issue by QingKongBaiYu** [dani-garcia/vaultwarden#1687]
### Subject of the issue

chrome extension unexpectedly logout when trying to modify data (create, delete and modify items). it works well on Android app and web. the official account works well with chrome extension.
### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.21.0
* Web-vault version: v2.19.0d
* Running within Docker: true
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.33.0
* Install method: Docker image
* Clients used: web vault, android app, chrome extension.
* Reverse proxy and version: nginx v1.18.0(ubuntu)
* Other relevant information: 

### Config (Generated via diagnostics page)
```json
{
  "_duo_akey": null,
  "_enable_duo": false,
  "_enable_email_2fa": false,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_ip_header_enabled": true,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_max_conns": 10,
  "database_url": "****/**.*******",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://****.*************.***",
  "domain_origin": "*****://****.*************.***",
  "domain_path": "",
  "domain_set": true,
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "email_attempts_limit": 3,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "enable_db_wal": true,
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "invitation_org_name": "Vaultwarden",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "Info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "org_attachment_limit": null,
  "org_creation_users": "",
  "password_iterations": 100000,
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sends_folder": "data/sends",
  "show_password_hint": true,
  "signups_allowed": true,
  "signups_domains_whitelist": "",
  "signups_verify": false,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_explicit_tls": false,
  "smtp_from": "",
  "smtp_from_name": "Vaultwarden",
  "smtp_host": null,
  "smtp_password": null,
  "smtp_port": 587,
  "smtp_ssl": true,
  "smtp_timeout": 15,
  "smtp_username": null,
  "templates_folder": "data/templates",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_syslog": false,
  "user_attachment_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "websocket_address": "0.0.0.0",
  "websocket_enabled": false,
  "websocket_port": 3012,
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```

### Steps to reproduce

1. login in chrome extension and sync successfully
2. try to add/delete/modify an item
### Expected behaviour

chrome extension modify data successfully
### Actual behaviour

chrome extension unexpectedly logout
### Troubleshooting data

![image](https://user-images.githubusercontent.com/45838887/117905810-60caa100-b306-11eb-9789-3b0c2b8cd9ca.png)

**Comment by BlackDex** [comment]
Please post some logs from around the time this happens.

**Comment by QingKongBaiYu** [comment]
> Please post some logs from around the time this happens.

I'd like to do this, could you tell where to get the log? I tried but didn't find it.

**Comment by BlackDex** [comment]
They should be in the volume where your database is stored, vaultwarden.log.
Or you could use `docker logs {container-name}`

**Comment by QingKongBaiYu** [comment]
> They should be in the volume where your database is stored, vaultwarden.log.
> Or you could use `docker logs {container-name}`

I find this in `docker logs`
`[auth][ERROR] Unauthorized Error: No access token provided`.

**Comment by BlackDex** [comment]
I think there are some extensions or browser settings/tweaks to prevent long term cookies or sessions. It could be that this is causing the issue. Also check the settings if the extensions it self, there is a auto lock/logout option which you may have configured.

You could try to disable all but the bitwarden extension and see what happens.

**Comment by QingKongBaiYu** [comment]
> I think there are some extensions or browser settings/tweaks to prevent long term cookies or sessions. It could be that this is causing the issue. Also check the settings if the extensions it self, there is a auto lock/logout option which you may have configured.
> 
> You could try to disable all but the bitwarden extension and see what happens.

thanks, I will test it later. (not at home)

**Comment by QingKongBaiYu** [comment]
> I think there are some extensions or browser settings/tweaks to prevent long term cookies or sessions. It could be that this is causing the issue. Also check the settings if the extensions it self, there is a auto lock/logout option which you may have configured.
> 
> You could try to disable all but the bitwarden extension and see what happens.

problem solved after turning off adguard, thanks for your help!
