### ISSUE TITLE
Backup of attachments not working

### ISSUE THREAD

**Issue by philippstreller** [dani-garcia/vaultwarden#1695]
Hi,

I self-host Vaultwarden on a t3.micro in the AWS cloud.

Backup up and restoring the db.sq3lite works perfectly fine but backing up attachments does not.

What I do:

1. tar the attachments-directory in /vw-data (tar -zcvf ...)
2. upload the archive to s3 bucket

When I want to restore (new, empty machine) I do:

1. download the archive from s3 bucket
2. extract the attachments directory into /vw-data (tar -zxvf ...)

In my expectations, this should work as it does with passwords. But it does not. I can *see* the attachments after restoring it like this but when I try to open/download them, I get an error (it doesn't get any more specific, it just says "Es ist ein Fehler aufgetreten" ("an error occured"). 
They are either not really there or encrypted so I can't do anything with them?

**Comment by BlackDex** [comment]
Could you post the vaulwarden log files of the times during the attempts to download an attachment?
And also please post a support string which you can generate via `/admin/diagnostics`.

**Comment by philippstreller** [comment]
I terminated and rebuilt the machine multiple times by now and never backed the logs up so I can't. 

I just tried to recreate the behavior in order to post them and ... it's working now. So I must have messed up before at some point. Consider this closed, thanks for the quick answer!
