### ISSUE TITLE
Wrong Device Name on New Device Logged in Notification

### ISSUE THREAD

**Issue by ncabete** [dani-garcia/vaultwarden#1731]
### Subject of the issue
Upon logging in on an iPhone 12 Pro, VaultWarden sends a notification to my email letting me know that a new device logged into my account, which is fine, however the device type is not correct - it says "IPhone13,3"

### Steps to reproduce
Access your Bitwarden on a iPhone 12 Pro running the latest iOS Version (14.6) - watch out for the email notification to come in.

### Expected behaviour
Device Type should be iPhone 12 Pro

### Actual behaviour
Device Type is iPhone 13.3

### Troubleshooting data
https://i.imgur.com/qAu4CXJ.png

**Comment by BlackDex** [comment]
Nothing we can do about. This is something the client is sending us.
Please remote this upstream @ https://github.com/bitwarden/mobile/issues
