### ISSUE TITLE
This browser requires https to use the web vault

### ISSUE THREAD

**Issue by BlaceLP** [dani-garcia/vaultwarden#1746]
### 
I get this error when I create an admin account in the web gui: "This browser requires https to use the web vault"

The Docker command:
 docker run -d --name bitwarden -p 8084:80 -p 8443:443 vaultwarden/server:latest

**Comment by RealOrangeOne** [comment]
Browsers require HTTPS for a lot of the security features.

This isn't an error, nor an issue with vaultwarden (it'd be bitwarden itself). Equally, It's definitely worth setting up HTTPS!
