### ISSUE TITLE
change maximum file size

### ISSUE THREAD

**Issue by vista-narvas** [dani-garcia/vaultwarden#1753]
### Subject of the issue

when uploading a file for send, i get the error
"Maximum file size is 100 MB."
i cant find any config for changing the maximum file size

### Deployment environment

* vaultwarden version:
vaultwarden/server:latest
just pulled again

* Install method:
docker

* Clients used: 
web vault and browser addon

* Reverse proxy and version: 
traefik

* MySQL/MariaDB or PostgreSQL version: 
nope

* Other relevant details:

### Expected behaviour

a way to set the maximum file size

**Comment by RealOrangeOne** [comment]
Looking at the code, the [default is 110MB](https://github.com/dani-garcia/vaultwarden/blob/main/src/api/core/sends.rs#L171), but it can be overriden with the [`$USER_ATTACHMENT_LIMIT`](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template#L202) environment variable

**Comment by vista-narvas** [comment]
i tried using USER_ATTACHMENT_LIMIT: 8388608 in my docker-compose.yml
and im still not able to upload bigger files

i think USER_ATTACHMENT_LIMIT is only for the global limit
in the [error](https://github.com/dani-garcia/vaultwarden/blob/main/src/api/core/sends.rs#L167) it says "Attachment size limit reached! Delete some files to open space"
if i change USER_ATTACHMENT_LIMIT to 1 when i try to upload a small file i get that error

**Comment by jjlin** [comment]
Max attachment size is primarily limited by what the clients are designed to handle, and you can't change that without building your own version of the client. See https://bitwarden.com/help/article/attachments/ for details.

In principle, the server could handle arbitrarily large attachments, but it also has some checks to mirror the client limits.

**Comment by vista-narvas** [comment]
ok so the limiting factor is the client
i guess there is nothing to do about that
thank you for your time

the issue can be closed
