### ISSUE TITLE
All 2FA keys incorrect

### ISSUE THREAD

**Issue by opicron** [dani-garcia/vaultwarden#1764]
### Subject of the issue
edit: *not sure if I should list this here or at the official Bitwarden*
Generated TOPT 2FA keys do not match Google Authenticator

### Deployment environment
Synology Docker

* vaultwarden version:
1.21.0

* Install method:
Docker image

* Clients used: 
n/a - Desktop/Webvault

### Steps to reproduce
I checked the date on Synology and Docker container, that is correct.
All of the 2FA keys which have not changed in the last weeks are incorrect. Yesterday they were working fine.
The resulting generated keys are now no longer the same as my backups in Google Authenticator.

### Expected behaviour
I expect the same generated keys as in Google Authenticator

### Actual behaviour
They are different and now no longer work as 2FA.

**Comment by omueller** [comment]
Hi @opicron, have you changed something in the mean time (if it was working fine before, or it is a new installation) ?   You wrote you checked the date, but is the time really correct on second level on all devices (synology, vaultwarden/docker, google auth device) ?   And is everything green also under /admin/diagnostics ?

**Comment by BlackDex** [comment]
Please check the `/admin/diagnostics` page and check the time.
Also, post the `Support String` which you can generate over there.

**Comment by opicron** [comment]
I think this is correct?

```
Date & Time (Local)
    Server: 2021-06-10 13:04:43 +00:00 
Date & Time (UTC) Ok
    Server: 2021-06-10 13:04:43 UTC 
    Browser: 2021-06-10 12:58:31 UTC
```

**Comment by BlackDex** [comment]
It looks to me like either server or your host is drifting time. They are too much apart.
12:58:31 and 13:04:43 are more than 6 minutes difference.

I'm not sure which is wrong, it could even be both. Try to enable NTP or something on the docker host.

**Comment by opicron** [comment]
The synology host is updated by Google NTP. Docker has same time. I now see that only the firefox plugin is incorrect. The iPhone bitwarden shows the correct keys. I would expect that the Firefox plugin doesnt use the local time, I think my expectation is incorrect.

I will mark as closed now, especially seeing nobody else is having issues. Sorry.

**Comment by BlackDex** [comment]
@opicron Then it looks like your client (where you are running Firefox on) is not having the correct time as seen there is more then 6 minutes time difference. I would try to enable or verify the NTP state of  you client (laptop/desktop/rpi, whatever)
