### ISSUE TITLE
Building from source is broken

### ISSUE THREAD

**Issue by knightian** [dani-garcia/vaultwarden#1778]
clone repo
cargo build --features sqlite --release

Dont Profit :(

```
    Updating git repository `https://github.com/dani-garcia/webauthn-rs`
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to load source for dependency `webauthn-rs`

Caused by:
  Unable to update https://github.com/dani-garcia/webauthn-rs?rev=70b458f246d207e5b6333ada9f1d5794c5e01da1#70b458f2

Caused by:
  object not found - no match for id (70b458f246d207e5b6333ada9f1d5794c5e01da1); class=Odb (9); code=NotFound (-3
```)

**Comment by knightian** [comment]
Seems that commit for webauthn-rs 70b458f246d207e5b6333ada9f1d5794c5e01da1 doesn't exist anymore?

But it's still specified in Cargo.toml

When I replaced it with the latest commit ee6575188884f6663ba5784727fe67daf93a619a instead, it worked.

**Comment by BlackDex** [comment]
Strange, i did a cargo clean yesterday, it still worked then.
Also my PR i pushed an hour or so ago failed on the exact same issue.

**Comment by knightian** [comment]
Yea bad merge I guess, probably just updating Cargo.toml is the fix

**Comment by knightian** [comment]
But then maybe using the latest commit of webauthn-rs is not good actually:

![image](https://user-images.githubusercontent.com/72685601/122653124-0682f280-d186-11eb-8a18-5aa2e3373422.png)

**Comment by knightian** [comment]
I think that @dani-garcia needs to push commit 70b458f246d207e5b6333ada9f1d5794c5e01da1 for webauthn-rs? Probably sitting on your local device :P

**Comment by dani-garcia** [comment]
Oh, I got the PR based on that commit merged upstream and then deleted my local branch without thinking, my mistake. I'll update it now.

**Comment by dani-garcia** [comment]
Should be fixed now!

**Comment by knightian** [comment]
It is thanks :D
