### ISSUE TITLE
Trying to get in touch with you regarding a security issue

### ISSUE THREAD

**Issue by huntr-helper** [dani-garcia/vaultwarden#1794]
Hi there,

I couldn't find a `SECURITY.md` in your repository and so am not sure how to best contact you privately to disclose the security issue.

Can you add a `SECURITY.md` file with your e-mail to your repository, so that I know who to contact? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, please let me know so I can ping you the info.

Thanks! (cc @JamieSlome)

**Comment by BlackDex** [comment]
@huntr-helper, you could contact me or @dani-garcia via Matrix if you want. I will look into the SECURITY.md.

**Comment by JamieSlome** [comment]
@BlackDex - awesome, if you could just drop a contact e-mail in your `SECURITY.md`, and we will send over a magic link to you!
