### ISSUE TITLE
Version stale when compiling

### ISSUE THREAD

**Issue by grawlinson** [dani-garcia/vaultwarden#1805]
I'm one of the packagers for Vaultwarden on Arch Linux and I'm just updating the package, noticed this when compiling:

https://github.com/dani-garcia/vaultwarden/blob/72e1946ce5c3e6c33024be499b6e0e516a35ce92/Cargo.toml#L3

Seems like the version field in Cargo.toml does not get updated to reflect the tagged version.

**Comment by BlackDex** [comment]
It never does. We use the git tags for this.
