### ISSUE TITLE
Alpine Docker Images are missing for v1.22

### ISSUE THREAD

**Issue by axdotl** [dani-garcia/vaultwarden#1807]
With the latest release v1.22 the alpine docker images were not published.

**Comment by BlackDex** [comment]
The base image we use seems to have remove OpenSSL, which is something we really need.
This causes the build to fail.

I Was working on something similar, but haven't come around finishing it quite the way i want, but i could try to quickly update the packages and see if we can use that

**Comment by BlackDex** [comment]
I have a quick fix i think. Still depends on @dani-garcia if he can trigger a new build on the same tag, or that he needs to release e new minor version for this to have it available on docker hub.

**Comment by dani-garcia** [comment]
I've created a new minor release to fix this issue, 1.22.1, once the images are compiled in docker hub it should be fixed.

**Comment by axdotl** [comment]
Thanks to you both @BlackDex and @dani-garcia for the fast fix 🚀 
Images is available 🙏🏼
