### ISSUE TITLE
Attachment size limit displayed to user does not match the limit imposed in the Vaultwarden admin panel

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [dani-garcia/vaultwarden#1818]
![1](https://user-images.githubusercontent.com/76442625/124281771-fa157700-db41-11eb-81e9-13660c8ed0c7.png)

This upload will fail and will return the shown error due to the size restriction set by the admin using the admin panel. It is set to 50MB in this example.

**Comment by BlackDex** [comment]
Those are hard-coded limits in the web-vault, and not something we can change on-the-fly, per server.
What we can do is change the error message to indicate what the limit is so that it will be more clear.

**Comment by BlackDex** [comment]
I have checked the code a bit better, and the size limit you can configure isn't per attachment, but as a total amount of storage. The wording is a bit off, so i think we should change that.
