### ISSUE TITLE
Vaultwarden 1.22.1 arm64 (Docker) not starting

### ISSUE THREAD

**Issue by dude71** [dani-garcia/vaultwarden#1825]
error while loading shared libraries: /usr/lib/aarch64-linux-gnu/libgssapi_krb5.so.2: invalid ELF header

**Comment by BlackDex** [comment]
I just checked the image, and it seems to run for me using an qemu aarch64 environment.
Also, i checked the `libgssapi_krb5.so.2` file which points to `libgssapi_krb5.so.2.2` which really reads as an arm64 ELF file. So not sure what happened over there. Could you try it again as a clean image maybe?

**Comment by dude71** [comment]
Tried again pulling fresh image, same problem. This is happening since 1.22.0.

Platform: RPI4, Linux 5.4.124 #0 SMP Sun Jun 13 22:02:19 2021 aarch64 GNU/Linux
Container runtime: Podman 2.2.1.

Last known working version: 1.21. Container log:

/--------------------------------------------------------------------\
|                        Starting Vaultwarden                        |
|                           Version 1.21.0                           |
|--------------------------------------------------------------------|
| This is an *unofficial* Bitwarden implementation, DO NOT use the   |
| official channels to report bugs/features, regardless of client.   |
| Send usage/configuration questions or feature requests to:         |
|   https://bitwardenrs.discourse.group/                             |
| Report suspected bugs/issues in the software itself at:            |
|   https://github.com/dani-garcia/vaultwarden/issues/new            |
\--------------------------------------------------------------------/

[INFO] No .env file found.

[2021-07-06 10:56:47.880][start][INFO] Rocket has launched from http://0.0.0.0:80

**Comment by dude71** [comment]
Sorry my mistake, somehow the podman-graphroot folder got corrupted on the SD card causing this issue. Deleting this folder and pulling everything from scratch solved the problem. This issue can be closed
