### ISSUE TITLE
Logged in as __$1__

### ISSUE THREAD

**Issue by ItsDrike** [dani-garcia/vaultwarden#1837]
You probably have some badly formatted template, as seen from the screenshot, instead of showing the actual username, there's just `__$1__`. (I've censured the domain for obvious reasons).

![image](https://user-images.githubusercontent.com/20902250/124465738-47cdf180-dd85-11eb-9b3f-86a445e6a881.png)

**Comment by BlackDex** [comment]
This is not a vaultwarden bug. It was an issue on the bitwarden/web code which also has been resolved in a newer version which we do not yet have available for vaultwarden.
