### ISSUE TITLE
Password hint: An error has occurred. But does show.

### ISSUE THREAD

**Issue by Robin-floss** [dani-garcia/vaultwarden#1847]
### Subject of the issue
When requesting your password hint it says `An error has occurred.`.
But under that it does actually show the hint

### Deployment environment
* vaultwarden version: latest

* Install method: docker

* Clients used: web vault

### Steps to reproduce
Click `Get master password hint` when trying to login
Enter your email

### Expected behaviour
It should show your password hint

### Actual behaviour
It shows your password hint, in an error box

### Troubleshooting data
![image](https://user-images.githubusercontent.com/46354497/125095957-fa2eed00-e0d4-11eb-9045-a111e38b993e.png)

**Comment by jjlin** [comment]
Normally, BItwarden only provides the password hint via email. This is a Vaultwarden-specific feature that allows the hint to be provided when the user hasn't set up email service:

https://github.com/dani-garcia/vaultwarden/blob/3968bc8016611cdf9a84db68990f27624ab17889/src/config.rs#L391-L393

Though personally, I think this option should've been disabled by default.

**Comment by pepa65** [comment]
Yes, please disable by default!

**Comment by Robin-floss** [comment]
> Normally, BItwarden only provides the password hint via email. This is a Vaultwarden-specific feature that allows the hint to be provided when the user hasn't set up email service:

Yeah, but the current way is that it shows as "An error has occurred", and as "error" the password hint. While it's not an error?

**Comment by jjlin** [comment]
It's not an error, but Bitwarden doesn't support this feature natively, so this is a Vaultwarden-specific hack that uses an error message to display the data. That's just the only way to do it.

#1848 will disable this setting by default. People who want password hints should just set up SMTP service and use that instead, anyway.

**Comment by BlackDex** [comment]
Closing because PR #1848 has been merged
