### ISSUE TITLE
Malformed sender name when using some chars in "From Name"

### ISSUE THREAD

**Issue by hrvylein** [dani-garcia/vaultwarden#1862]
When configuring the "From Name" with a ":" in SMTP Email Settings, f.e. "Example: Vaultwarden". Sender mail and name change to "nobody@invalid.invalid" on the receiving end.

I don't know if this is a specific problem with my mail hoster or if there is a quirk in retrieving the from_name from config or when setting up the e-mail.

**Comment by BlackDex** [comment]
I just tested a double colon `:` and that works fine for me.
It was sent using postfix and received by GMail.

**Comment by BlackDex** [comment]
You could btw, enable `SMTP_DEBUG=true` and see what is actually being sent out.

**Comment by hrvylein** [comment]
Then nevermind I guess and there is something wrong on my end. I will test with SMTP_DEBUG when I have time and reopen if it still persists.
