### ISSUE TITLE
After last upgrade, can no longer view org users

### ISSUE THREAD

**Issue by sempervictus** [dani-garcia/vaultwarden#1876]
### Subject of the issue
After upgrading the core and web components last night, i can no longer view org users - page just hangs waiting to load the list of users, logs say
```
vaultwarden[95995]: [2021-07-28 12:19:48.237][vaultwarden::api::core::organizations][ERROR] Organization Keys already exist
vaultwarden[95995]: [2021-07-28 12:19:48.237][response][INFO] POST /api/organizations/<org_id>/keys (post_org_keys) => 400 Bad Request

```

### Deployment environment

* vaultwarden version: 1.22.2-1, web is 2.21.1-1

* Install method: Packages

* Clients used: management webui

* Reverse proxy and version:  Apache 2.4.48-1 

* MySQL/MariaDB or PostgreSQL version: 

### Steps to reproduce
Click users in an org existing before the update

### Expected behaviour
Users load and i can manage them

### Actual behaviour
Permanent wait for users to load

### Troubleshooting data
![image](https://user-images.githubusercontent.com/1331084/127321702-f48c9f96-22f0-45ff-8d83-e55e7d7b37ea.png)

**Comment by BlackDex** [comment]
Try to logout and and back in again.

**Comment by BlackDex** [comment]
Closed due to inactivity
