### ISSUE TITLE
SMTP Client error: internal client error: No compatible authentication mechanism was found

### ISSUE THREAD

**Issue by belerovon** [dani-garcia/vaultwarden#1892]
I use an Postfix SMTP Relay host for outgoing mails - also I configured valuewarden to use this host in the same way.
The SMTP Relay Host accept my private networks and has no authentication enabled.

Now when I try to send mails via valuewarden I got the following error:
[2021-08-11 10:34:59.896][vaultwarden::mail][ERROR] SMTP Client error: internal client error: No compatible authentication mechanism was found

Some version before Bitwarden_rs works fine with this host.

**Comment by melbv** [comment]
Just found this and i have the same issue - could you specify what you corrected in the docker-compose?
Many thanks in advance

**Comment by BlackDex** [comment]
normally this means a wrong port, or not using ssl/tls when that is needed.
You can enable SMTP_DEBUG=true for a short time while testing and see what the output is.

**Comment by melbv** [comment]
Hi Mathijs
Thanks for the reply. I was testing the setup w/o TLS/SSL on port 25 to avoid those but will try with the encryption to see if it changes anything
21 Sep 2021, 18:49 by ***@***.***:

**Comment by BlackDex** [comment]
Normally port 25 doesn't allow login, only 587 or 465 allow login and sending email.
Port 25 is only used for receiving e-mail by the final endpoint.

**Comment by melbv** [comment]
Tbh, 25 is perfectly fine for relaying btw an app & a mta on the same server - which i do on another machine where i run nextcloud with postfix (no docker install).
Having docker containers on this machine complicates a little the declarations and i thought i could have learnt something from the set up to implement! Ill keep looking then...

21 Sep 2021, 19:15 by ***@***.***:
