### ISSUE TITLE
2FA works on Linux desktop and mobile, but not on Windows

### ISSUE THREAD

**Issue by AndreVuillemot160** [dani-garcia/vaultwarden#1904]
### Subject of the issue
2FA works on Linux desktop and mobile, but not on Windows

### Steps to reproduce
1. Download latest Bitwarden desktop client on PC running Windows
2. Connect to Vaultwarden instance
3. Copy OTP of Windows version
4. Get from website incorrect OTP

### Expected behaviour
Basically, Windows generated codes should be working.

### Actual behaviour
In reality, not working.

**Comment by BlackDex** [comment]
This has nothing to do with Vaultwarden. The clients are not build by us.

Also check the windows time if it is correct. If it is at drift it can't generate correct codes.
