### ISSUE TITLE
Vaultwarden export stops after few entries

### ISSUE THREAD

**Issue by nakal** [dani-garcia/vaultwarden#1918]
### Subject of the issue

The function Tools / Vault export is broken for me. It stops after a few entries (here: 13) and is incomplete. I have got ~550 entries.

### Deployment environment

* FreeBSD 12.2
* nginx
* vaultwarden version: 1.22.2

* Install method: OS package (compiled with Poudiere)
* Clients used: Firefox on FreeBSD
* Reverse proxy and version: nginx 1.20.1
* MySQL/MariaDB or PostgreSQL version: MariaDB 10.4.20

* More information: Vaultwarden was upgraded from Bitwarden manually by following the documentation.

### Steps to reproduce

1. Click on Export, use CSV or JSON.
2. See downloaded file. It has fewer entries.

### Expected behaviour

It should export the full vault contents.

### Actual behaviour

It stops at some point, just after few passwords.

### Troubleshooting data

Nothing of use in logs (nginx-error.log or vaultwarden.log).

It could be some encoding problems (I use probably use typical German characters somewhere). The last exported entry actually uses a German word with umlauts "Sicherungsschlüssel".

**Comment by BlackDex** [comment]
That is not something done by Vaultwarden. The export is done fully within the clients since they have all the logic regarding encryption and decryption.

That is also the reason why there are no useful logs within Vaultwarden or your Reverse Proxy.
