### ISSUE TITLE
Confirming multiple organisation invites at once results in error

### ISSUE THREAD

**Issue by bokkabonga** [dani-garcia/vaultwarden#1984]
### Subject of the issue

When you select multiple Users who accepted an invite to an organisation and try to confirm all at once an the website loads indefinitely.  
### Deployment environment

 (Generated via diagnostics page)
* Vaultwarden version: v1.22.2-8c10de3e
* Web-vault version: v2.21.1
* Running within Docker: true
* Environment settings overridden: true
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: MySQL
* Database version: 10.4.12-MariaDB-1:10.4.12+maria~bionic
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** DOMAIN, HIBP_API_KEY, USER_ATTACHMENT_LIMIT, ORG_ATTACHMENT_LIMIT, SIGNUPS_ALLOWED, SIGNUPS_VERIFY, SIGNUPS_VERIFY_RESEND_TIME, SIGNUPS_VERIFY_RESEND_LIMIT, SIGNUPS_DOMAINS_WHITELIST, INVITATIONS_ALLOWED, INVITATION_ORG_NAME, DISABLE_2FA_REMEMBER, YUBICO_CLIENT_ID, YUBICO_SECRET_KEY, SMTP_HOST, SMTP_SSL, SMTP_PORT, SMTP_FROM, EMAIL_TOKEN_SIZE, EMAIL_EXPIRATION_TIME

```json
{
  "_duo_akey": null,
  "_enable_duo": false,
  "_enable_email_2fa": false,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_ip_header_enabled": true,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_max_conns": 10,
  "database_url": "*****://****:*********************************@**/*********",
  "db_connection_retries": 10,
  "disable_2fa_remember": true,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://*********.***.****-******.**",
  "domain_origin": "*****://*********.***.****-******.**",
  "domain_path": "",
  "domain_set": true,
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "email_attempts_limit": 3,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "enable_db_wal": false,
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": "***",
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "invitation_org_name": "Bitwarden",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": "/data/bitwarden.log",
  "log_level": "Info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "org_attachment_limit": 20480,
  "org_creation_users": "",
  "password_iterations": 100000,
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": true,
  "signups_allowed": false,
  "signups_domains_whitelist": "***.****-******.**,***.**",
  "signups_verify": true,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_explicit_tls": false,
  "smtp_from": "*********@***.****-******.**",
  "smtp_from_name": "Bitwarden_RS",
  "smtp_host": "**********.***.****-******.**",
  "smtp_password": null,
  "smtp_port": 25,
  "smtp_ssl": false,
  "smtp_timeout": 15,
  "smtp_username": null,
  "templates_folder": "data/templates",
  "trash_auto_delete_days": 60,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_syslog": false,
  "user_attachment_limit": 5121,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "websocket_address": "0.0.0.0",
  "websocket_enabled": true,
  "websocket_port": 3012,
  "yubico_client_id": "61202",
  "yubico_secret_key": "***",
  "yubico_server": null
}
```
</details>

### Steps to reproduce

Inivte one or more user(s) to an organisation and have him accept the invite. Then check on or more users using the checkbox and try to accept them all at once.

### Expected behaviour
All Users are confirmed and added to the organisation

### Actual behaviour
Website loads indefinitely

### Troubleshooting data
Logfile logs the following:

[2021-09-21 10:13:18.027][request][INFO] POST /api/organizations/6233a33a-3272-4565-82d4-b7f804889fa3/users/public-keys
[2021-09-21 10:13:18.029][response][INFO] POST /api/organizations/<org_id>/users/<org_user_id> (edit_user) => 422 Unprocessable Entity

**Comment by BlackDex** [comment]
Already fixed in the current `testing` version via: https://github.com/dani-garcia/vaultwarden/commit/f36bd72a7f772fd108b31e5ca1f502238ab1ef00
