### ISSUE TITLE
Fido2 Webauthn broken on latest version of Android app (2.13.0)

### ISSUE THREAD

**Issue by TheRealMazur** [dani-garcia/vaultwarden#1996]
### Subject of the issue

It seems that with the recent version of the mobile app some changes were introduced to FIDO2 Webauthn authentication - https://github.com/bitwarden/mobile/pull/1519 
After updating, there is a 404 error when trying to authenticate, as the app is trying to connect to an unimplemented endpoint, example below:  
https://vault.mydomain.com/webauthn-mobile-connector.html?data=[DATA]=&parent=bitwarden%3A%2F%2Fwebauthn-callback&v=2 

### Deployment environment

* vaultwarden version: 1.22.2

* Install method: docker image

* Clients used:  Android

* Reverse proxy and version: 

* MySQL/MariaDB or PostgreSQL version: 

* Other relevant details:

### Steps to reproduce

Try to authenticate with Fido2 Webauthn using the latest (2.13.0) mobile app

### Expected behaviour

Authentication is possible

### Actual behaviour

Error 404 happens

**Comment by BlackDex** [comment]
I think it should work fine. Are you using a reverse proxy, and if so which one? Does it has caching functionally? Did you clear the case?

**Comment by BlackDex** [comment]
Sorry, i just saw that this specific endpoint is available within the current testing image, and thus already fixed. But not in the current latest version 

Either use the testing image or wait for a new release.

**Comment by TheRealMazur** [comment]
Thank you for the quick response!
The latest testing docker image is panicking and not starting on my Raspberry Pi 4, so I guess I'll wait for a release :)
