### ISSUE TITLE
Cannot update from 1.22.2 to 1.23.0 due to database migration error

### ISSUE THREAD

**Issue by FrankelJb** [dani-garcia/vaultwarden#2085]
### Subject of the issue
Updating from 1.22.2 to 1.23.0 fails with a database error:

```
[CAUSE] QueryError(
DatabaseError(
__Unknown,
"Can't create table `vaultwarden_db`.`emergency_access` (errno: 150 \"Foreign key constraint is incorrectly formed\")",
),
)
```

### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.22.2
* Web-vault version: v2.21.1
* Running within Docker: false
* Environment settings overridden: true
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: MySQL
* Database version: 10.5.12-MariaDB
* Install method: Kubernetes (running k3s)

### Steps to reproduce

When upgrading the container image to use `vaultwarden/server:1.23.0`, the database migration fails with the error. I have made no changes to the database or the connection string. I can also rollback from the failed 1.23.0 to 1.22.2 without any trouble:
```
DatabaseError(
[CAUSE] QueryError(
[2021-11-06 18:30:08.768][vaultwarden::util][WARN] Can't connect to database, retrying: DieselMig.
Executing migration script 20210830193501/up.sql
Running migration 20210830193501
)
),
[CAUSE] QueryError(
DatabaseError(
__Unknown,
"Can't create table `vaultwarden_db`.`emergency_access` (errno: 150 \"Foreign key constraint is incorrectly formed\")",
),
)
```
### Expected behaviour

Expected migrations to run and database to be updated.

### Actual behaviour

Cannot start Vaultwarden and rollback to 1.22.2 is required.

**Comment by BlackDex** [comment]
Already fixed via #2080

**Comment by jjlin** [comment]
This one is actually more like #2054.

**Comment by BlackDex** [comment]
Ah indeed, sorry for the quick mistake

**Comment by FrankelJb** [comment]
Thanks for the amazingly quick response. Incredible work on this project!

**Comment by BlackDex** [comment]
@MurzNN this is the same issue as the OP, which has the same solution: See https://github.com/dani-garcia/vaultwarden/discussions/1559#discussioncomment-544070

**Comment by MurzNN** [comment]
Yeah, sorry for noise, have found this issue first and decided that I have the same situation, that comment fixes all for me!
