### ISSUE TITLE
web vault dark mode

### ISSUE THREAD

**Issue by toxic0berliner** [dani-garcia/vaultwarden#2104]
I think the docker image is a bit behind in terms of web vault UI. Maybe it's not just as simple as pulling from upstream, but I find I'm missing the dark mode in options. 
I'm using the docker hub vaultwarden/server: latest
Server Installed Ok
    1.23.0 
Server Latest
    1.23.0 
Web Installed
    2.23.0c 

Thanks in advance for any time spent on this comfort point ;)

**Comment by BlackDex** [comment]
This is already fixed via https://github.com/dani-garcia/vaultwarden/commit/450c4d4d97da91898abc6a32bb748d275d36b6ac

When you use the testing tagged images it will be available.
