### ISSUE TITLE
Can't create Organisation.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [dani-garcia/vaultwarden#2124]
### Subject of the issue
Can't create Organisation, getting a TypeError: Cannot read properties of undefined (reading 'hasAdditionalSeatsOption')

### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.23.0
* Web-vault version: v2.23.0c
* Running within Docker: true (Base: Debian)
* Environment settings overridden: true
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Time Check: true
* Domain Configuration Check: false
* HTTPS Check: false
* Database type: SQLite
* Database version: 3.35.4
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** ADMIN_TOKEN

```json
{
  "_duo_akey": null,
  "_enable_duo": false,
  "_enable_email_2fa": false,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_ip_header_enabled": true,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_max_conns": 10,
  "database_url": "****/**.*******",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "****://*********",
  "domain_origin": "****://*********",
  "domain_path": "",
  "domain_set": true,
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "email_attempts_limit": 3,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 5 * * * *",
  "emergency_request_timeout_schedule": "0 5 * * * *",
  "enable_db_wal": true,
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "invitation_org_name": "Vaultwarden",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "Info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "org_attachment_limit": null,
  "org_creation_users": "****************@*****.***",
  "password_iterations": 100000,
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": false,
  "signups_domains_whitelist": "",
  "signups_verify": false,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_explicit_tls": false,
  "smtp_from": "",
  "smtp_from_name": "Vaultwarden",
  "smtp_host": null,
  "smtp_password": null,
  "smtp_port": 587,
  "smtp_ssl": true,
  "smtp_timeout": 15,
  "smtp_username": null,
  "templates_folder": "data/templates",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_syslog": false,
  "user_attachment_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "websocket_address": "0.0.0.0",
  "websocket_enabled": true,
  "websocket_port": 3012,
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>

* Reverse proxy and version: nginxproxymanager

* Other relevant details:

### Steps to reproduce
Admin has my email in the Organisation Users setting.
I previously set the env variable for enabling admin page and set this up.

I login and try to create an Organisation.

### Expected behavior
Create an Organisation

### Actual behavior
core.js:6210 ERROR TypeError: Cannot read properties of undefined (reading 'hasAdditionalSeatsOption')

### Troubleshooting data
The page does not seem to have labels on these inputs.
And might be missing some options?

![image](https://user-images.githubusercontent.com/1968109/144257491-2e57c32c-a8d3-4649-87f5-36dddd57a96e.png)

Happens even if I uncheck "This account is owned by a business."

**Comment by BlackDex** [comment]
Looks like you do not have HTTP enabled.
And i see that you have configured the `org_creation_users` config.
If the mail address  you filled in there exactly matches the mail address you use to login into the web-vault then that is ok.

But you really need to configure your `DOMAIN` correctly, and you really need HTTPS.

**Comment by LiamKarlMitchell** [comment]
I have nginx proxy manager handling https and domain just fine :)
Randomly it worked when I tried it in Opera rather than Chrome.

**Comment by BlackDex** [comment]
This is already fixed in the latest `testing` version.
See https://github.com/dani-garcia/bw_web_builds/commit/1e990dd7aed291152fe91496f8f4308846d03a11
