### ISSUE TITLE
Can't connect to database

### ISSUE THREAD

**Issue by KBCACheia** [dani-garcia/vaultwarden#2132]
After a restart the vaultwarden can't connect the database. And i get this message.

"[vaultwarden::util][WARN] Can't connect to database, retrying: Failed to create pool. 
[CAUSE] Error (
       None,
)"

### Deployment environment

Debian 10
Docker
DB: PostgreSQL
Version: 1.23.0

**Comment by BlackDex** [comment]
Duplicate of #2134
