### ISSUE TITLE
Direct links to items

### ISSUE THREAD

**Issue by mfominov** [dani-garcia/vaultwarden#2160]
Hi, first of all i want to say thx for this project it's really awesome.

This is not a bug, it's a kind of feature request.

It will be useful to create direct links to secrets for sharing with someone.

**Comment by BlackDex** [comment]
This is something for the clients, which we do not maintain our selfs.
Also, feature requests for Vaultwarden should actually go to https://github.com/dani-garcia/vaultwarden/discussions/categories/ideas

If you have feature requests for clients then i suggest to go to this page: https://community.bitwarden.com/c/feature-requests/5
