### ISSUE TITLE
admin page still active after commenting out ADMIN_TOKEN in docker-compose

### ISSUE THREAD

**Issue by degrashopper** [dani-garcia/vaultwarden#2163]
### Subject of the issue
admin page

### Deployment environment

* vaultwarden version: 1.23.1

* Install method: docker

* Clients used: desktop, android

* Reverse proxy and version: traefik v2.5.4

* MySQL/MariaDB or PostgreSQL version: SQLite

* Other relevant details:

### Steps to reproduce
comment out ADMIN_TOKEN under vaultwarden in docker-compose and restart the container.
### Expected behaviour
/admin page should not exist after commenting out ADMIN_TOKEN

### Actual behaviour
/admin page is still visitable

**Comment by BlackDex** [comment]
You probably have saved some settings via the /admin interface before, which creates a `config.json` which overrules the ENV variables including the `ADMIN_TOKEN`.

Either delete that file, or empty that out via the /admin interface.
