### ISSUE TITLE
Native MacOS and iOS app not working with latest vaultwarden release?

### ISSUE THREAD

**Issue by Vip0r** [dani-garcia/vaultwarden#2173]
### Subject of the issue
Even with the latest vaultwarden image the native mac os and iOS app seems no more working (can't sync the vault).
If i logout and try to re-logon i got the error "failed to fetch data"

WebLogon is working and also the browser-integration is working properly

### Deployment environment
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                    PORTS                                      NAMES
c48444bae464        vaultwarden/server:latest     "/usr/bin/dumb-init …"   2 months ago        Up 43 minutes (healthy)   80/tcp, 3012/tcp                           vaultwarden
7609f88915f9        nginx:1.15-alpine             "nginx -g 'daemon of…"   12 months ago       Up 43 minutes             0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   bitwarden_nginx_1
(please ignore created - timestamp ; i already also tried to pull the latest img)

### Steps to reproduce
upgraded the ios/mac app to the latest version

Tried to re-setup my containers without success. Can you confirm if the latest vaultwarden image should work with the current iOS&macOS native apps (

MacOS Version (Version 1.30.0 (1935))
iOS Version (Version 2.15.0 (1225)

**Comment by BlackDex** [comment]
I just quickly tested it on iOS, and that seems to work just fine.
Could you check the logs during the time you try to sync?
Also check the reverse proxy.

**Comment by Vip0r** [comment]
> I just quickly tested it on iOS, and that seems to work just fine.
> Could you check the logs during the time you try to sync?
> Also check the reverse proxy.

Thanks for testing. Maybe there is an issue with my ssl cert. Got the following if try to test the connection with open_ssl:

`
openssl s_client -showcerts -connect vault.ndnet:443 -servername vault.ndnet
....
verify error:num=20:unable to get local issuer certificate`


Will check that and provide feedback

**Comment by Vip0r** [comment]
I am prette sure this is related to an expired ssl cert. I have renewed the self signed cert and updated the cert/key files used by nginx.

If i trust the cert on my macbooks i can browse via safari without any issues. However if i test via the openssl on the terminal i always get the "unable to get local issuer certificate".

**Comment by Vip0r** [comment]
As i am pretty sure that this is issue is somehow related to my own setup i will close this and move this to discussions.
