### ISSUE TITLE
Bitwarden cli breaks when creating a send with `--maxAccessCount` flag

### ISSUE THREAD

**Issue by jcalonso** [dani-garcia/vaultwarden#2196]
### Subject of the issue

Bitwarden cli breaks when creating a send with `--maxAccessCount` or `-a` flags.

### Deployment environment

* vaultwarden version: 1.23.1

* Install method: Docker

* Clients used: bitwarden-cli 

* Reverse proxy and version: traefik 2.5 

* MySQL/MariaDB or PostgreSQL version: Sqlite 

* Other relevant details: bitwarden-cli 1.20.0-1

* OS: Archlinux

### Steps to reproduce

```
bw send "test" --maxAccessCount 1
```
### Expected behaviour

Create a send and output the url.
### Actual behaviour

Throws an error:
```
         <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="utf-8">
                <title>422 Unprocessable Entity</title>
            </head>
            <body align="center">
                <div role="main" align="center">
                    <h1>422: Unprocessable Entity</h1>
                    <p>The request was well-formed but was unable to
                be followed due to semantic errors.</p>
                    <hr />
                </div>
                <div role="contentinfo" align="center">
                    <small>Rocket</small>
                </div>
            </body>
            </html>
```

**Comment by BlackDex** [comment]
Confirmed.
The CLI uses a String instead of an Integer.
Patch is on the way.
