### ISSUE TITLE
People tab in organization does not work

### ISSUE THREAD

**Issue by jce-zz** [dani-garcia/vaultwarden#2204]
When I try to access the people tab in my main organization it remains empty forever with a spinning wheel.

Upon checking the logs and Developer console I realized that one of the API calls fails:
```
POST /api/organizations/<xxx>/keys
404 Not Found
```

I'm using the web-vault version 2.25.0. This was definitely working some time earlier. I'm also using Microsoft Edge Chromium latest version to access my vault.

What is going wrong here and how to fix it?

**Comment by BlackDex** [comment]
May i ask which version of Vaultwarden you are using? Because that endpoint does exists.

**Comment by jce-zz** [comment]
I think I was using 1.23 and the endpoint was somehow missing. However, in the meantime I have switched to the latest version by using the binary from the official docker image and now the endpoint is there again and the people section works fine. Issue can be closed, thanks!
