### ISSUE TITLE
Vault export and re-import not working

### ISSUE THREAD

**Issue by A30BL** [dani-garcia/vaultwarden#2211]
### Subject of the issue
Hello,
I am currently using vaultwarden version 2.25.0 on two different machines. The first installation was intended as a test version, but was then used for a longer time. Now the vault of the first installation should be transferred to a newer computer, which also runs version 2.25.0 with an empty vault.
So I tried to export the vault from computer 1 in csv format and also in json format. The export completed without any errors.
Then I tried to import the data on computer 2 as "Bitwarden (json)" and "Bitwarden (csv)" and got the error message in each case:

Import Error
There was a problem with the data you tried to import. Please resolve the errors listed below in your source file and try again.
HTML code content:
 
<!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="utf-8">
                <title>400 Bad Request</title>
            </head>
            <body align="center">
                <div role="main" align="center">
                    <h1>400: Bad Request</h1>
                    <p>The request could not be understood by the server due
                to malformed syntax.</p>
                    <hr />
                </div>
                <div role="contentinfo" align="center">
                    <small>Rocket</small>
                </div>
            </body>
            </html>
        

### Deployment environment

* vaultwarden version: 2.25.0

* Install method: Vaultwarden software package that comes with Dietpi

* Clients used: web vault

* Reverse proxy and version: 

* MySQL/MariaDB or PostgreSQL version: 

* Other relevant details:

### Steps to reproduce
Dietpi installation with software package "183 vaultwarden"

### Expected behaviour
Vaultwarden imports vault data

### Actual behaviour
Vaultwarden does not import own vault data

**Comment by BlackDex** [comment]
Could you please post the /admin/diagnostics `Support String`?
Because looking at the DietPi install script it is still using web-vault v2.21.1, also v2.25.0 is not the version number of Vaultwarden it self, that is the web-vault version.

**Comment by BlackDex** [comment]
Also, if all is empty, and you have no other users besides your self, you could also just transfer the database it self.
