### ISSUE TITLE
Problem, if the user has the "manager" rights.

### ISSUE THREAD

**Issue by learnnew007** [dani-garcia/vaultwarden#2286]
Hello!

There is a problem, if the user has the "manager" rights, then when you click on the button "manage" it redirects to the start page and will logoff.
![manage](https://user-images.githubusercontent.com/96025961/152216959-c46bfc7f-599e-416c-b33a-fa853e03867a.PNG)

Why is this happening?
How to solve this problem?

Thanks!

**Comment by BlackDex** [comment]
Update to the latest version as this is fixed already.
https://github.com/dani-garcia/vaultwarden/pull/2169

**Comment by learnnew007** [comment]
But i use last version vaultwarden/server:1.23.1!!
And have a problem((
What to do?

**Comment by BlackDex** [comment]
Install the current latest version which is 1.24.0 https://github.com/dani-garcia/vaultwarden/releases/tag/1.24.0

**Comment by learnnew007** [comment]
Thank you so much!
