### ISSUE TITLE
Manager role can't move  entries to other collection

### ISSUE THREAD

**Issue by IgnazNepumuk** [dani-garcia/vaultwarden#2290]
### Subject of the issue

User with 'manager' role, can't edit the entries  associated collection. If the user tries to edit the collection (click on the gear, collections) following message appears: 
"Collections
There are no collections to list. "
The entry is part of a collection, the user rights are set to "this user can access and modify all items."
### Deployment environment

* vaultwarden version: 1.24.0

* Install method: Docker image

* Clients used:  web vault

* Reverse proxy and version: 

* MySQL/MariaDB or PostgreSQL version: 

* Other relevant details:

### Expected behaviour

Users with Manager role and access control "this user can access and modify all items." should be able to edit every entry within the organization and be able to move an entry from one collection to another.
### Actual behaviour
Users with Manager role and access control "this user can access and modify all items.", are unable to move entries from one collection within the same organization to another collection within the same organization

**Comment by BlackDex** [comment]
This seems to be either by design or a bug in the web vault, which is not maintained by Vaultwarden.
I can reproduce the same on vault.bitwarden.com
