### ISSUE TITLE
bad search results for entries with hyphens

### ISSUE THREAD

**Issue by chrpinedo** [dani-garcia/vaultwarden#2293]
### Subject of the issue
Bad search results for entries with hyphens.
It think it is a bug because there is no special treatment for hyphen or dashes in the basic search according to the [documentation](https://bitwarden.com/help/searching-vault/#basic-search).

### Deployment environment
* vaultwarden version: 1.24.0
* Install method: docker
* Reverse proxy and version: nginx 1.20.2
* MySQL/MariaDB or PostgreSQL version: no
* Other relevant details: no

### Steps to reproduce
* create two entries in the database: "githubtest-pru.com" and "githubtest.com"
* result of basic search "githubtest" is correct: the 2 entries
* result of basic search "githubtest." is correct: 1 entry "githubtest.com"
* result of basic search "githubtest-pru" IS INCORRECT: the 2 entries

### Expected behaviour
* result of basic search "githubtest-pru" should be 1 entry "githubtest-pru.com"

### Actual behaviour
* result of basic search "githubtest-pru" IS INCORRECT: the 2 entries

**Comment by BlackDex** [comment]
This is all handled from within the web-vault and nothing is done on the server endpoints for this.
So, if this is an issue, and you can reproduce this on vault.bitwarden.com i suggest to report an issue https://github.com/bitwarden/web/

**Comment by chrpinedo** [comment]
just FYI, I reported the bug https://github.com/bitwarden/web/issues/1456
