### ISSUE TITLE
Login session expired with account switching

### ISSUE THREAD

**Issue by cksapp** [dani-garcia/vaultwarden#2295]
# Low priority issue, noticed a slight issue with the newest release of the Bitwarden Desktop app [1.31.0](https://github.com/bitwarden/desktop/releases/tag/v1.31.0)

When trying to use the new [Account Switching](https://bitwarden.com/help/account-switching/) feature, you are able to login to one account with Vaultwarden as normal.
![2022-02-10_19h45_57](https://user-images.githubusercontent.com/66083310/153521468-43808c4e-56b0-4dac-b8e4-af61c74509b4.png)

After login to another account with the same VW server, the first initial account logged in will time out.
![2022-02-10_19h47_57](https://user-images.githubusercontent.com/66083310/153521470-00c0a337-cb92-44d5-a1ff-db09a7f46cc7.png)

Latest release of the desktop app reinstalled, and Vaultwarden server upgraded to latest 1.24.0

**Comment by BlackDex** [comment]
Confirmed. It looks like it is trying to access the token, `[INFO] (login) POST /identity/connect/token`, but not allowed.

**Comment by cksapp** [comment]
Thanks for the info, pretty interesting to know.
I will note it seems this is even _less_ of a priority issue as upstream had several major issues with this release and have rolled back to [1.30](https://github.com/bitwarden/desktop/releases/tag/v1.30.0) as latest. Who's to say what changes may be made, my guess not much would be changed but best not to even worry about it until this is fully patched and a new public release is available.

**Comment by BlackDex** [comment]
I digged a little bit into this. And it looks like we currently only have a uniqueness on the device-id.
This in turn makes it that we overwrite this when a new user logs-in, which effectively deletes there refresh token.
To change this we need to change the whole code regarding the device table to match on both device-id and user-id on all fronts.

This will take some time and needs some good testing. But it is one the list now :).
Thanks for the report.

**Comment by BlackDex** [comment]
Small update, i think i have a working patch. I just need some time to do some final checking :)
