### ISSUE TITLE
New browser extention update not compatible

### ISSUE THREAD

**Issue by kearfy** [dani-garcia/vaultwarden#2298]
### Subject of the issue
New update of the (chrome) browser extension does not work with vaultwarden anymore.

### Deployment environment

* vaultwarden version: 1.24.0

* Install method: docker

* Clients used: 
* web vault

* Reverse proxy and version: 
* nginx reverse proxy

* MySQL/MariaDB or PostgreSQL version: 
* mysql (i guess)

* Other relevant details:

### Steps to reproduce

update browser extension to latest version

### Expected behaviour

can sign in and use extension

### Actual behaviour

it completely breaks, cannot decrypt, cannot find field 'keys', etc

**Comment by rakeshdas1** [comment]
Just faced this issue as well - simple fix is to log in and out of the browser extension.

**Comment by kearfy** [comment]
Did that earlier today, now happens to me again but the fix doesnt work this time...

**Comment by taylorcoffelt** [comment]
Getting this as well on Vaultwarden version 1.24.0, extension version 1.56.1

All entries are showing as `error: cannot decrypt`: 
![image](https://user-images.githubusercontent.com/690213/153634011-5e6ce4db-c88d-4de1-af02-91f5da2cea22.png)
![image](https://user-images.githubusercontent.com/690213/153634168-d0a33ac7-e45e-4d68-8c7d-b8719c8c4817.png)
In extension search doesn't work.

If I log out, and attempt to log back in, I'm getting intermittently the `cannot find field 'keys'` toast error message.

---
I just tried logging in and out one more time and now all the entries are showing, and search is now working.
I have the extension installed in another Chrome profile, and that one is still showing the broken behavior. Both Chrome profiles are on the same extension version.

**Comment by viyh** [comment]
I'm also getting this on two separate laptops that use two separate Vaultwarden servers.

**Comment by mka142** [comment]
It crashes there:
![Screenshot from 2022-02-11 18-25-55](https://user-images.githubusercontent.com/69858959/153639485-3d53c01c-a037-435d-a134-f68d08e072a4.png)

**Comment by mka142** [comment]
Try to turn off and on in chromium extension settings
![Screenshot from 2022-02-11 18-43-55](https://user-images.githubusercontent.com/69858959/153642062-9baffc59-0d3f-4037-87ce-d1698c98e589.png)

**Comment by MaxRubbel** [comment]
Uninstall and Install the Extensions helps me.

**Comment by kearfy** [comment]
> Uninstall and Install the Extensions helps me.

I can confirm that this works for me. I will close the issue for now.
