### ISSUE TITLE
Time zone doesn't reflect environment variable in Docker

### ISSUE THREAD

**Issue by HawaiianPizza** [dani-garcia/vaultwarden#2342]
### Subject of the issue
Time zone doesn't reflect what is stated in the environment variable.

### Deployment environment

* vaultwarden version: 1.24.0

* Install method: Docker image

* Clients used: Web vault, Android

### Steps to reproduce

1. Inside docker-compose.yml, set the environment variable to:

```
environment:
      - TZ="America/Toronto"
```

2. Go to the Admin panel.
3. Go to Users.
4. `Created at` and `Last active` are only in UTC.

### Expected behaviour

Time zone is expected to display in the specified time zone in the docker-compose file.
### Actual behaviour

Time zone in docker-compose file is ignored and instead Vaultwarden uses UTC.

**Comment by BlackDex** [comment]
Works for me.
Within `docker-compose.yml` you need to remove the quotes `"` around the value.
