### ISSUE TITLE
trim() the login email field: Android might add trailing spaces

### ISSUE THREAD

**Issue by hitech95** [dani-garcia/vaultwarden#2348]
### Subject of the issue
Android might add trailing space to email on login input

### Deployment environment

* vaultwarden version: 1.24.0 

* Install method: Docker Compose

* Clients used: Android Client

* Reverse proxy and version: traefik v2

* PostgreSQL version: PostgreSQL 11.15 (Debian 11.15-1.pgdg90+1) on x86_64-pc-linux-gnu

* Other relevant details:

### Steps to reproduce

- Using gboard auto completion on first login and/or after disconnecting the account 
- The email address input might have a trailing space.
- Perform the login and you will get an authentication error.
- The "issue" is not easily visible
-  looking in vaultwarden logs you find the error:
`[2022-03-02 22:12:09.086][vaultwarden::api::identity][ERROR] Username or password is incorrect. Try again. IP: x.x.x.x. Username: xxxxxx@gmail.com .`
- Note that the trailing dot is not attached to the email address as in the template:
https://github.com/dani-garcia/vaultwarden/blob/main/src/api/identity.rs#L104
The issue seems not to be present using the official server. (I have not tried with self hosted one)

### Expected behaviour

Server perform trim on input email berfore looking for the user in the database.

### Actual behaviour

Login is rejected

**Comment by JeDaYoshi** [comment]
Can reproduce on web vault too. Since autocomplete is happy to do this, it's probably best user-experience speaking if it is trimmed, for safety.

(For some reason though, `/api/accounts/prelogin` sends `{ email: "test@example.com" }` while `/identity/connect/token` sends { "username": "test@example.com " }`)
