### ISSUE TITLE
Password genration rules not preserved 

### ISSUE THREAD

**Issue by naclander** [dani-garcia/vaultwarden#2411]
### Subject of the issue
I can successfully change the password generation rules from default ( increasing length from 14 characters to 25 ).
Upon restarting the tab, or when logging in from a different browser, the password generation rules seem to get reverted back to default.

* Install method: Arch Linux package -  Version 2.27.0, sqlite

* Clients used: web

**Comment by BlackDex** [comment]
Those settings are stored into cookies/local browser cache.
You probably have some extension enabled which prevents the storage or clears the storage of these settings.
