### ISSUE TITLE
Lack of validation on name of the users

### ISSUE THREAD

**Issue by pavel1337** [dani-garcia/vaultwarden#2419]
### Subject of the issue
Lack of validation on name of the users

### Deployment environment
* vaultwarden version: 1.24.0

* Install method: Docker (Base: Debian)

* Clients used: web client

* MySQL/MariaDB or PostgreSQL version: MySQL 8.0.23 RDS

* Other relevant details:

### Steps to reproduce
1. Receieve an invite to vaultwarden
2. Create account with long name (eg. using this command ```pwgen 100000 1```)

### Expected behaviour
- validation error with something like "the name is too long"

### Actual behaviour
- I was able to create a user and login, but I cannot send secrets. I guess because the bearer token is too big, because the username is too long.

### Troubleshooting data
The command I used to create a long username: ```pwgen 100000 1```

The screenshot of the users table; I guess it should be something like ```varchar(x)```
![image](https://user-images.githubusercontent.com/31508908/163392934-38cf465f-262e-47d2-9ee2-789fa271dd0e.png)

The screenshot of the organization with me in it: 
![Screenshot 2022-04-14 at 14-20-33 People Bitwarden Web Vault (1)](https://user-images.githubusercontent.com/31508908/163393340-0620ba1f-d4c6-4d9c-979b-e7251f41b2d2.png)

The screenshot of me trying create a send and developer tools
![image](https://user-images.githubusercontent.com/31508908/163394232-9d1903eb-9bc6-4f21-983c-33973fb13412.png)

**Comment by BlackDex** [comment]
Looks like Bitwarden it self uses a max of 50 characters. It will be a bit difficult now to switch that for Vaultwarden to a lower size if people were already using a larger amount of characters for the names.
Though limiting it a specific amount is not a bad idea, i need to see what a good amount is.

**Comment by dani-garcia** [comment]
We could just limit it in the save function, if we don't want to create a new migration for this change

**Comment by BlackDex** [comment]
I think it should be enough to have this only at the register function, what do you think @dani-garcia ?
That would at least prevent new users from using a large Name, but will not prevent current users forcing them to update it.

**Comment by dani-garcia** [comment]
Right, but a user could also change their name from the web vault after the account was created, I know realistically no one is going to put a long enough name to break the web vault, but we should cover all bases if possible.
