### ISSUE TITLE
Not syncing automatically

### ISSUE THREAD

**Issue by rucksman** [dani-garcia/vaultwarden#2442]
I am using vaultwarden behind a Traefik proxy in my Docker environment. I did install the browser extension, and in addition I am using the windows client (portable) and the Android app (always latest versions).

Entries are not automatically synced for whatever reason. If I am entering a new entry with one of the client (for example the Windows client, but that does not really matter), this new entry is not automatically synced to the other clients even after some hours. I always have to manually sync on all the client to get the latest version of my entries. There is no error in the logs of the docker container, and also not in the clients. It simple does not sync automatically. Is this the desired behaviour, or is there something wrong?

**Comment by codesections** [comment]
Have you configured enabled WebSocket notifications as described in the [relevant wiki page](https://github.com/dani-garcia/vaultwarden/wiki/Enabling-WebSocket-notifications)?  If so, the browser extension and windows client *should* sync automatically (the android app won't currently – support for mobile push notifications is still [a work in progress](https://github.com/SergioBenitez/Rocket/issues/90)).

**Comment by rucksman** [comment]
Thanks for the quick reply.

I followed more or less the Traefik configuration from the [proxy examples page](https://github.com/dani-garcia/vaultwarden/wiki/Proxy-examples). So obviously there is a problem on my side with automatic sync at least between web page, windows client and browser extension, if automtaic sync _should_ work. I will investigate further into my docker configuration. Thanks for helping!
