### ISSUE TITLE
1.24.0 still not released (on github)

### ISSUE THREAD

**Issue by dafanasiev** [dani-garcia/vaultwarden#2460]
Tag 1.24.0 [exists](https://github.com/dani-garcia/vaultwarden/tree/1.24.0), but  only `1.23.1` are released?

**Comment by RealOrangeOne** [comment]
I see a release? https://github.com/dani-garcia/vaultwarden/releases/tag/1.24.0

**Comment by dafanasiev** [comment]
hmmm.... its look like my cache broken or github do something (strange error). closed.
