### ISSUE TITLE
Dashlane import only allows JSON

### ISSUE THREAD

**Issue by cringer** [dani-garcia/vaultwarden#2461]
### Subject of the issue
Dashlane import only allows JSON
### Deployment environment

* vaultwarden version: 1.24.0

* Install method: Docker

* Clients used: Web Vault (Chrome and Firefox)

* Reverse proxy and version:  Traefik (not relevant to this issue)

* MySQL/MariaDB or PostgreSQL version:  Default which I believe is SQLite

* Other relevant details:

### Steps to reproduce

Nothing changed from the default.  Tools -> Import Data

### Expected behaviour

See an option for Dashlane (csv)
### Actual behaviour

Only see Dashlane (json)

### Troubleshooting data

Dashlane no longer does a json output as they no longer support the Desktop application.  Everything now runs through a web application which only allows a csv or DASH export.

**Comment by BlackDex** [comment]
Already fixed in the `testing` tagged images based upon the `main` branch.
