### ISSUE TITLE
Error saving device on postgresql

### ISSUE THREAD

**Issue by jz8132543** [dani-garcia/vaultwarden#2487]
I failed to login on all clients(web, Android, ios and etc). I'm running version 2.25.1 of Vaultwarden/server in docker, using postgresql14. I accidentally restarted postgresql and then can't log into my account. The log is as follows.
```
vaultwarden  | [2022-05-24 06:48:37.570][error][ERROR] Error saving device.
vaultwarden  | [CAUSE] DatabaseError(
vaultwarden  |     __Unknown,
vaultwarden  |     "there is no unique or exclusion constraint matching the ON CONFLICT specification",
vaultwarden  | )
```
The devices table in postgresql has been emptied, but such an error still occurs. How to fix or how to migrate data to other database types like SQLite or MySQL?

**Comment by BlackDex** [comment]
Could you post the generated support string please. That would be really helpful.

**Comment by BlackDex** [comment]
Also, if you still see v2.25.1 as your web-vault version, you are not on the latest version.
I would make sure you are using the latest version. Since it seems to work for me just fine using Postgresql.

So, posting the Support String would be helpful.

**Comment by jz8132543** [comment]
Thanks for your reply! It works after I update my docker container. It is a weird issue but I'm so glad it was solved after update.

**Comment by jz8132543** [comment]
Thanks for your reply! It works after I update my docker container. It is a weird issue but I'm so glad it was solved after update.

**Comment by Bluscream** [comment]
I have a similar error:

```
[2024-03-28 02:40:31.430][response][INFO] (login) POST /identity/connect/token => 400 Bad Request
[2024-03-28 02:40:48.802][request][INFO] POST /identity/connect/token
[2024-03-28 02:40:50.430][request][INFO] POST /identity/connect/token
[2024-03-28 02:40:53.454][error][ERROR] Error saving device.
[CAUSE] DatabaseError(

    Unknown,
    "disk I/O error",
)
```

**Comment by BlackDex** [comment]
@Bluscream that looks more like a PostgreSQL issue that it isn't able to store data. Check the storage or logs of the database.

**Comment by Bluscream** [comment]
> @Bluscream that looks more like a PostgreSQL issue that it isn't able to store data. Check the storage or logs of the database.

i am using the rpi portainer install with no special database (https://github.com/pi-hosted/pi-hosted/blob/master/template/apps/vaultwarden.json)

**Comment by BlackDex** [comment]
Then your issues is misplaced in this topic.
1. It was closed already for a long time.
2. You are using a totally different setup. 

Still remains a database storage issue. 
I suggest to open a topic in the Q&A discussion and post your support string which you can generate via the admin diagnostics page.
