### ISSUE TITLE
Update 1.25.0 not working with Raspberry Pi Zero W (armv6)

### ISSUE THREAD

**Issue by iamwalde** [dani-garcia/vaultwarden#2490]
### Subject of the issue

Update 1.25.0 not working with Raspberry Pi Zero W (armv6)
The latest update (1.25.0) seems not to work for armv6 devices. I can not accesst the web interface. Viewing the log files in Portainer shows me the following error: 

`/start.sh: 25: exec: /vaultwarden: not found`

This error only occur with Raspberry Pi Zero W (armv6) images (I have several of them). Runing Bitwarden with Raspberry Pi Zero W 2 (armv7) works without any problems. If I go back to the 1.24.0 version everything works as intended again. 
So I guess the armv6 Image is broken?! 

### Steps to reproduce
Simply install the Bitwarden on Raspberry Pi Zero:  docker run -d --name vaultwarden -v vw-data:/data/ -p 80:80 vaultwarden/server:latest

### Troubleshooting data
![image details](https://user-images.githubusercontent.com/29702694/170027873-c9879be3-734e-4888-b2bf-64d80869016d.PNG)

**Comment by BlackDex** [comment]
I'm not sure where you got that image from. Since if i try to pull that specific SHA256 ID it fails.
Try to pull it in again, or for that specific platform try to use `vaultwarden/server:latest-arm32v6`

**Comment by BlackDex** [comment]
Also, i do see an issue with the 1.25.0 armv6 image, i can't seem to start it my self either.
The Alpine image does work btw.

**Comment by iamwalde** [comment]
Yeah i can confirm, that alpine works armv6 not.
