### ISSUE TITLE
1.25.0 build does not start with the same configs as 1.24.0

### ISSUE THREAD

**Issue by tophers** [dani-garcia/vaultwarden#2496]
### Subject of the issue
Using Rust 1.61/Stable, compiled the 1.25.0 tag - Also pulled vaultwarden bin from the latest docker.io:/vaultwarden/server
Neither will start simply replacing the older 1.24.0 binary. Error getting Rocket config?  I'm sure this is atleast partly my config, maybe a variable name changed?
### Deployment environment
Debian 11
Github tag 1.25.0
Rust 1.61/Stable

Github Source, Tag 1.25.0
Clients used: 
None, server won't start
Reverse proxy and version: 
NGINX but not a part of this issue since vaultwarden does not start

* MySQL/MariaDB or PostgreSQL version: 
sqllite

* Other relevant details:
No build errors, but get the folllowing when trying to start either binary (though the path to the rocket config changes from where it was compiled.)
[2022-05-24 13:52:23.459][rocket::config::config][ERROR] Rocket configuration extraction from provider failed.
[2022-05-24 13:52:23.508][panic][ERROR] thread 'main' panicked at 'aborting due to configuration error(s)': /home/topher/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.5.0-rc.2/src/config/config.rs:293
   0: vaultwarden::init_logging::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: rocket::config::config::Config::from
   7: vaultwarden::main::{{closure}}
   8: std::thread::local::LocalKey<T>::with
   9: tokio::park::thread::CachedParkThread::block_on
  10: tokio::runtime::thread_pool::ThreadPool::block_on
  11: rocket::async_main
  12: vaultwarden::main
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: std::rt::lang_start::{{closure}}
  15: std::rt::lang_start_internal
  16: main
  17: __libc_start_main
             at ./csu/../csu/libc-start.c:308:16
  18: _start

### Steps to reproduce
I just built the vaultwarden tag and replaced the current binay from the output.
### Expected behaviour

Vaultwarden to start
### Actual behaviour
Vaultwarden doesn't start w/ above error, missing rocket config. I assume this is my configuration, but not sure what changed or what I need to change in my environment.

**Comment by BlackDex** [comment]
Check to see if you have any `ROCKET_` environment variable configured other then `ROCKET_ADDRESS` or `ROCKET_PORT`.

Those could cause some issues with the new Rocket version.

**Comment by tophers** [comment]
Thank you. I guess I was using an older .env template that had the following recommendation
```
## Logging to file
## It's recommended to also set 'ROCKET_CLI_COLORS=off'
```
Which I was doing and did have set. Removing that variable resolved my issue. Thanks.
