### ISSUE TITLE
Web Vaultwarden stops to adapt to the environment langage

### ISSUE THREAD

**Issue by Romuald23** [dani-garcia/vaultwarden#2540]
### Subject of the issue
Web Vaultwarden stops to adapt to the browser language.

In the previous version, Vaultwarden was able to adapt the default language interface to the user language interface. After the 1.25.0 update, we were in the 1.24.0 version, the default language is English even if the desktop environment or web browser is in another language.

The version number : 1.25.0
The webvault : 2.28.1

* Install method: Debian packages

* Clients used: Chromium and Firefox

* MySQL/MariaDB or PostgreSQL version: Postgresql

* Other relevant details:

### Steps to reproduce
Change the language of your browser and open Vaultwarden.

### Expected behaviour
The Vaultwarden interface default language should be the same as the browser.

### Actual behaviour
The Vaultwarden interface default language is English.

**Comment by BlackDex** [comment]
This was a bug in the web-vault: https://github.com/bitwarden/web/issues/1587
It has already been resolved in the latest release of the web-vault `2022.05.0` which is currently available within the `testing` tagged image of Vaultwarden.
