### ISSUE TITLE
"Test SMTP" form saves settings instead of sending email on Enter

### ISSUE THREAD

**Issue by nh2** [dani-garcia/vaultwarden#2542]
Hi, thanks for Vaultwarden!

On the Admin panel, if you enter an email address into the `<input id="smtp-test-email">` and hit <kbd>Enter</kdb>, like this:

![image](https://user-images.githubusercontent.com/399535/172615871-d4ce1f21-8521-4b3e-b632-a71dcfdab2b4.png)

it does not trigger `Send test email` as expected, but instead tries to save the general admin settings, which is a bit confusing.

I believe the test email `<input>` needs its own `<form>` to submit correctly on Enter.

**Comment by BlackDex** [comment]
Thanks for the report.
A `<form>` within a `<form>` is not allowed, but i think i can fix something.
I will take a look at it this evening.
