### ISSUE TITLE
Bug displaying organization elements that are in a folder

### ISSUE THREAD

**Issue by Nyxtorm** [dani-garcia/vaultwarden#2566]
### Subject of the issue

Bug displaying organization elements that are in a folder (web vault version)

### Deployment environment

* Vaultwarden version: v1.25.0-887e320e
* Web-vault version: v2022.5.2 (also tested w/ v2022.05.0 from your last release web build)
* Running within Docker: false (Base: Debian)
* Environment settings overridden: false
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.35.4
* Clients used: Web, Android, Windows, Chrome, Firefox
* Reverse proxy and version: Nginx 1.21.6
* Other relevant information: 

### Steps to reproduce

1. Create a new item in an organization without assigning it a folder (the option should not be available in this case)
2. Go to the personal vault in "All vaults", find the new item and define a folder for it
(Or replace steps 1 and 2 by moving a personal item **that is in a folder** to an organization)
3. Go back to the "Organizations" tab, all items are displayed. But if you click in the left pane on "All items" or even select a collection for example, all the items in a folder are invisible (image 02).
4. The problem is not present as soon as I set the folder to "No folder".

### Expected behaviour / Actual behaviour

The organization items for which I have defined a folder should be displayed instead of disappearing.

Or it should be impossible to assign a folder to an item in the organization if it is not supposed to be possible, but the problem is only on the web version.

### Troubleshooting data

* OK - image01 : https://i.imgur.com/RhgwzXm.png

* Not OK - image02 : https://i.imgur.com/M89mq6h.png

Sorry for my English.

**Comment by BlackDex** [comment]
PR is pushed.
@Nyxtorm thanks for reporting!

**Comment by Nyxtorm** [comment]
Thank you very much for your reactivity to solve this problem, I just tested the PR, it works on my side! 🚀
