### ISSUE TITLE
Minor issue with identicons (Users and Organizations)

### ISSUE THREAD

**Issue by Nyxtorm** [dani-garcia/vaultwarden#2570]
### Subject of the issue

Here is the third (and final) minor problem I have encountered recently. The "identicons" are displayed or not randomly with an error in the browser console

### Deployment environment

* Vaultwarden version: v1.25.0-b71d9dd5
* Web-vault version: v2022.5.2
* Running within Docker: false (Base: Debian)
* Environment settings overridden: false
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.35.4
* Clients used: Web, Android, Windows, Chrome, Firefox
* Reverse proxy and version: Nginx 1.21.6
* Other relevant information: 

### Steps to reproduce

1. Go to Vaultwarden admin page
2. In the "Users" or "Organizations" tab, refresh the browser page X times (about 5 to 20 times)
3. Sometimes identicons are OK, sometimes they're blank with an error in web console : https://i.imgur.com/ppz2hSH.png

### Expected behaviour / Actual behaviour

Identicons should be always displayed, as before.

### Troubleshooting data

Blank identicons : https://i.imgur.com/WbDWFZI.png

Sorry for my English.

**Comment by BlackDex** [comment]
I think this was because i updated the script loading to use `defer`, even though i tested multiple browsers and reverse proxies, it seems to not work in all environments. I have removed the `defer` again, that should probably fix this sporadic issue.

**Comment by Nyxtorm** [comment]
PR tested just now on my side, I confirm that it corrects the problem.
