### ISSUE TITLE
Renaming folder will not rename subfolders

### ISSUE THREAD

**Issue by maxhq** [dani-garcia/vaultwarden#2703]
### Subject of the issue
When renaming a folder, all subfolders will then appear on the top level prefixed with the old parent folder and a slash. 

### Deployment environment

* vaultwarden version: 1.25.2

* Install method: Docker image (vaultwarden/server:latest)

* Clients used: web vault and Bitwarden Linux Client

* Reverse proxy and version: none

* MySQL/MariaDB or PostgreSQL version: none

### Steps to reproduce

Example folder structure:

- parent
  - daughter
  - son

Rename `parent` to `authority`.

### Expected behaviour

- authority
  - daughter
  - son

### Actual behaviour

- authority
- parent/daughter
- parent/son

When renaming `authority` back to `parent` the previous structure is restored.

**Comment by BlackDex** [comment]
Unfortunately that is not something we can change on the server side.
The server never receives the actual folder name, and thus there is no way for the server side to try and match this.

This should either be reported as a bug/feature request at Bitwarden it self.
Either here https://community.bitwarden.com/c/feature-requests/5 or here https://github.com/bitwarden/clients/issues
