### ISSUE TITLE
Error 404 when trying to export organization vault using latest version of the clients (2022.9.x)

### ISSUE THREAD

**Issue by TimoVerbrugghe** [dani-garcia/vaultwarden#2760]
### Subject of the issue
When trying to export an organization vault using the bitwarden cli (command `bw export --organizationid <ORGID> --session <SESSION_KEY> --format json`), I get a 404 error that the resource can't be found.

Other cli commands with the same organization id (like f.e. `bw get organization <orgid>`) do work and give the expected response.

I first filed an issue with bitwarden itself, but they referred me to vaultwarden. https://github.com/bitwarden/clients/issues/3595

### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.25.2
* Web-vault version: v2022.6.2
* Running within Docker: true (Base: Debian)
* Environment settings overridden: true
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Time Check: false
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.35.4
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** SIGNUPS_ALLOWED, INVITATIONS_ALLOWED, ADMIN_TOKEN

```json
{
  "_duo_akey": null,
  "_enable_duo": false,
  "_enable_email_2fa": false,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "****/**.*******",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://*********.****.**",
  "domain_origin": "*****://*********.****.**",
  "domain_path": "",
  "domain_set": true,
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "email_attempts_limit": 3,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 5 * * * *",
  "emergency_request_timeout_schedule": "0 5 * * * *",
  "enable_db_wal": true,
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "invitation_org_name": "Bitwarden_RS",
  "invitations_allowed": false,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "Info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "password_hints_allowed": true,
  "password_iterations": 100000,
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": true,
  "signups_allowed": false,
  "signups_domains_whitelist": "",
  "signups_verify": false,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_explicit_tls": false,
  "smtp_from": "****@*******.**",
  "smtp_from_name": "Bitwarden_RS",
  "smtp_host": "****.*****.***",
  "smtp_password": "***",
  "smtp_port": 587,
  "smtp_security": "starttls",
  "smtp_ssl": true,
  "smtp_timeout": 15,
  "smtp_username": "***********@*****.***",
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_syslog": false,
  "user_attachment_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "websocket_address": "0.0.0.0",
  "websocket_enabled": false,
  "websocket_port": 3012,
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>

### Steps to reproduce
Using the bw cli (in my case installed using npm), signed into my selfhosted bitwarden server
`bw config server <serverurl> bw login --apikey bw sync bw unlock`

List my organizations in order to get organization IDs
`bw list organizations --session <BW_SESSION_KEY>`

Try to export one of my organizations' vault as a non-encrypted json
`bw export --format json --organizationid <orgid> --session <BW_SESSION_KEY> --output /test`

### Expected behaviour
A json formatted file with the items in my organization vault

### Actual behaviour
Getting the following error code:

`{"response":{"error":{"code":404,"reason":"Not Found","description":"The requested resource could not be found."}},"captchaRequired":false,"statusCode":404}`

### Troubleshooting data
<img width="770" alt="Screenshot 2022-09-22 at 19 43 59" src="https://user-images.githubusercontent.com/7707120/191933174-98f027b8-57a2-411d-be05-8a98e808385c.png">

**Additional Context**
I've triple checked that the org id is correct. Additionally, other commands such as

bw get organization <orgid>
bw list org-collections --organizationid <orgid>

do work with the same org id that I'm using on the export command.

Exporting using other formats (csv or encrypted json) come with the same result.

Exporting the organization vault using the web client works as expected.

**Comment by BlackDex** [comment]
Looks like there are some new endpoints here which are not used by the web-vault indeed.
