### ISSUE TITLE
"Bypass admin page security" should not be overrideable by admin-page

### ISSUE THREAD

**Issue by kosli** [dani-garcia/vaultwarden#2761]
The option in the admin page to "Bypass admin page security" should not be able to override what was set in the environment as this imposes a security risk.  

e.g. as owner of a vaultwarden instance it would be great to set the "default" values in the environment, so that I still give an admin access to the admin pages, but he cannot override the values that I have set. -> especially if the settings can have such a big impact as bypassing the admin page security.

**Comment by stefan0xC** [comment]
I agree that it might be nice to prevent changing the config via admin panel altogether but why would you give someone else access to the admin panel? Especially if you don't trust them enough to not mess with your settings.

As a workaround for your problem I'd probably recommend setting up an additional authentication layer for the `/admin` panel in your reverse proxy.

**Comment by kosli** [comment]
It is not about trust. Even if I trust them, it is just to "easy" to set a tick and immediately the admin interface is widely open to the world (and shodan etc.). I don't see the use-case for having the web UI overriding the env settings -> I would even turn it around and everything set be the env cannot be changed/overriden via the web UI -> as the env always needs higher privileges than the web UI to access it.

**Comment by BlackDex** [comment]
Regarding the env vs config, this is a design choice made in the past which isn't easily to be changed at this point. So, config.json overrides env's.

Only thing we could do right now is too move that specific setting to read only, which prevents it from being edited in the interface.

With that, i think we also need to do some other changes, but i have to think those through.

**Comment by BlackDex** [comment]
Also, as @stefan0xC mentioned, i would definitely add an extra auth in front of the admin endpoint, this also prevents shodan from getting specific info.
