### ISSUE TITLE
First time setting up docker/VW strange res error?

### ISSUE THREAD

**Issue by DudeThatsErin** [dani-garcia/vaultwarden#2775]
This is my console when trying to set it up using the stuff on the main page: https://srcb.in/fYNKW5jHl3

I've tried googling the error and you can see me running a command to cancel all docker instances and yet it still doesn't work for some reason.

I would love to get this working but idk what is happening.

This is on my VPS with Hostinger with these setups:

- Linux Ubuntu 20.04
- root access
- 1GB RAM
- 20GB Storage
- 1 CPU
- IPv4 & IPv6
- 1TB Bandwidth

I am saving up to afford a bigger server with more RAM but for now this is what I have.

**Comment by BlackDex** [comment]
In theory 1G should be enough. But could you try the Alpine based images, and see if that helps?

**Comment by BlackDex** [comment]
Ow, wait, you seem to be using port 80 already for something else. You can't run two applications on the same port without a proxy.

**Comment by DudeThatsErin** [comment]
> Ow, wait, you seem to be using port 80 already for something else. You can't run two applications on the same port without a proxy.

Oh so changing the port should fix that? Good to know.

**Comment by BlackDex** [comment]
> > Ow, wait, you seem to be using port 80 already for something else. You can't run two applications on the same port without a proxy.
> 
> Oh so changing the port should fix that? Good to know.

If you would use `-p 8080:80` that would probably work.

**Comment by DudeThatsErin** [comment]
> > > Ow, wait, you seem to be using port 80 already for something else. You can't run two applications on the same port without a proxy.
> > 
> > 
> > Oh so changing the port should fix that? Good to know.
> 
> If you would use `-p 8080:80` that would probably work.

So, that worked but now I have a different error...
```
root@flowering-goodness:~# docker run -d --name vaultwarden -v /vw-data/:/data/ -p 8080:80 vaultwarden/server:latest
3a8a0516ea9b499efbe7d5ecb7f623205194c31cced691ba4e1da9074026476e
root@flowering-goodness:~# docker run valtwarden
Unable to find image 'valtwarden:latest' locally
docker: Error response from daemon: pull access denied for valtwarden, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**Comment by DudeThatsErin** [comment]
I got it. It was `docker start vaultwarden`.

Is there a way to use it on a domain like domain.com? So, I can go to domain.com:8080 to access the vault, instead of an IP?

**Comment by DudeThatsErin** [comment]
Alright, thank you.
