### ISSUE TITLE
Registration cannot be completed without invite link

### ISSUE THREAD

**Issue by stefan0xC** [dani-garcia/vaultwarden#2800]
Currently invited users cannot complete their registration without the link in the invitation.
The token in the invitation is also only valid for five days so the user would have to be re-invited first.
So if I've lost the mail I cannot register even when I don't want to join the organization that invited me.

Re-invitation via Admin-link is currently not possible, so you'd have to first delete a user (which is not ideal).
As for what a user can do, I shall quote myself [from the discourse forum](https://vaultwarden.discourse.group/t/automatically-expire-invitations/1212?u=stefan0xc):
> A user might have been invited but lost the invitation mail. When they try to register they are informed that the account already exists. They then have to request a password hint to get an email that contains a link to a form where they can request the account deletion to get another email with a link to finally delete their account. And only then can they register a new account.
These steps are not really obvious (why would I request a password hint without an account? why should I delete my account if don’t have an account?) and the warnings are also unsettling (do I already have an account that I am deleting?) so this is not a very user-friendly experience.

This is not how Bitwarden behaves. See the discussion in #2795 for an analysis.

### Deployment info
Behavior can be observed with latest release v1.25.2 as well as on the main branch (6fa6eb18e88f6d090eff5139d5a67bb56d25bf7f)

### Steps to reproduce
With invitations and signups allowed and mail enabled:
1. Invite user@example.com via admin panel or any organization.
2. Try to register as user@example.com without the link.

### Expected behaviour
I'd expect that registering an email address is possible like it is on Bitwarden.

### Actual behaviour
I can only register with a valid invite token.

**Comment by BadRix90** [comment]
If a user has deleted his account, can he be re-invited via sync? 
Background is, we try to invite our employees via sync. these are synchronized and also displayed. but an invitation is not sent. also, we have tested whether a deleted user, as one who has deleted his account, can be invited via sync. This does not happen. Are we doing something wrong?
