### ISSUE TITLE
When using the duckduckgo service, there is a cors error in the request

### ISSUE THREAD

**Issue by xtrus** [dani-garcia/vaultwarden#2828]
### Subject of the issue

When using the duckduckgo service, there is a cors error in the request.
<img width="1763" alt="截屏2022-10-15 20 06 12" src="https://user-images.githubusercontent.com/115393113/195985998-58e95971-5005-41c9-abdb-07d90483e84b.png">

### Deployment environment

* vaultwarden version: 1.26.0

* Install method: Docker image

* Clients used: web vault in chrome 

* Reverse proxy and version:  Nginx 1.22.0 

* MySQL/MariaDB or PostgreSQL version: sqlite

* Other relevant details:

### Actual behaviour

cors error in request

**Comment by BlackDex** [comment]
Looks like we can't use DuckDuckGo either, the same issue as with FireFox they have implemented CORS check, and it seems it only works from `vault.bitwarden.com`, also self-hosted Bitwarden environments arn't able to use this it looks like.

I have created an issue at Bitwarden regarding this.
https://github.com/bitwarden/clients/issues/3798

Unfortunately there is nothing we can do on our side regarding this.

**Comment by BlackDex** [comment]
Looks like this isn't something we can fix indeed. They reported that this probably needs to be removed from the Self-Hosted environments. Ill leave this ticket open so that we can link this on updating the web-vault which removes this functionality.
