### ISSUE TITLE
password hint not changed

### ISSUE THREAD

**Issue by tessus** [dani-garcia/vaultwarden#2833]
After the password hint field was moved from `My Account` (2022.06.2) to `Security > Master Password` (2022.10.0), there are 2 issues:

- it is not possible to update the password hint
- even when changing the password, the password hint is not saved

Personally I don't use password hints, but I could imagine this is important to others.

I am not sure, if this is just a web UI issue, a server component issue, or both.

**Comment by BlackDex** [comment]
Confirmed.
