### ISSUE TITLE
Deprecated usages on Github Actions

### ISSUE THREAD

**Issue by dani-garcia** [dani-garcia/vaultwarden#2847]
I've noticed some deprecation messages on our Github Actions, both here and in `bw_web_builds`, caused by two things:

The use of the `save-state` and `set-output` commands:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Some actions using Node 12 which is EOL:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

We have around six moths until they become errors, but I'm opening this issue to track them, as the build logs aren't very visible.

**Comment by BlackDex** [comment]
They could be solved with some forked actions. But not sure if i like that.

**Comment by dani-garcia** [comment]
I assume the affected actions will be updated eventually, as I mentioned this isn't something we have to care about until April or so, but also I don't want it surprising us last minute. I'll mark it as low priority.

If by April there are still no updates, we can look into changing/forking to different actions, but we're using pretty popular actions so I don't think this will be an issue.
