### ISSUE TITLE
Missing `register` endpoint in identity API for upcoming Bitwarden November release

### ISSUE THREAD

**Issue by prettyv** [dani-garcia/vaultwarden#2889]
Bitwarden has a [deprecation notice](https://bitwarden.com/help/november-deprecation-notice/) for the November releases planned for 2022-11-16, upping the Bitwarden server version requirement to `>=1.46.0`. Concretely this concerns the two endpoints `/identity/accounts/prelogin` and `/identity/accounts/register`, which were originally moved from `/api` and deprecated in [this commit](https://github.com/bitwarden/server/commit/0def1830afae29ff6ace9da871758ca836f66d3c).

The `prelogin` endpoint has already been implemented in the [identity module](https://github.com/dani-garcia/vaultwarden/blob/main/src/api/identity.rs#L433) I see, but `register` seems to still be missing, which I assume will lead to issues later in the month for new registrations.

**Comment by BlackDex** [comment]
Since the register endpoint can only be accessed via the web-vault, and we try to match the ones we support, the impact will be almost none. Before we will match and update we do need to fix that though.

There are some other fixes we need to do also for export on orgs, which I'm working on atm.

**Comment by prettyv** [comment]
Since the Bitwarden desktop client has an interface for creating an account I assumed that this would use the `register` endpoint as well. Although the UI doesn't communicate clearly if this would create an account via the configured self-hosted server URL or only on official Bitwarden servers (the settings button disappears on the create account page, so that might be an indication towards that). I didn't actively create an account via the client myself yet, so I'm not sure, you may be right.

**Comment by GeekCornerGH** [comment]
@BlackDex @prettyv So I tried today, with my 2022.10.1 client. It actually tries to register on the selfhosted instance as long you specified your instance url in the login page
