### ISSUE TITLE
Problem using Desktop client (windows 10)

### ISSUE THREAD

**Issue by ecesarini** [dani-garcia/vaultwarden#2939]
### Subject of the issue

Hi,
I'm running vaultwarden in production. Everything seems working fine but today i an user reported an issue, saying he can't login into the vault using **window desktop application**.
Most users actually use browser plugin and mobile client, so do I. I installed bitwarden desktop client in my windows 10 and i try a login: I got the same error the user reported. 
I think in some previous vaultwarden release i tried to test desktop client and i don't remember any issue, but maybe i remember wrong.
Maybe am I missing any setting?

Thank you very much,
EC

### Deployment environment

* vaultwarden version: 1.26.0

* Install method: Docker

* Clients used: desktop 

* Reverse proxy and version: Apache/2.4.6

* MySQL/MariaDB or PostgreSQL version: 10.6.4-MariaDB-1:10.6.4+maria~focal 

* Other relevant details: 

### Steps to reproduce

Set desktop client with vaultwarden URL, user mail and master password

### Expected behaviour

Login succesfully
### Actual behaviour

Error, see the attachment

![Screenshot 2022-11-30 150516](https://user-images.githubusercontent.com/73652902/204816699-7fada624-8c34-4345-ae98-b43768711dda.png)

### Troubleshooting data

**Vaultwarden container logs:**
 [2022-11-30 15:00:49.620][vaultwarden::api::identity][ERROR] Username or password is incorrect. Try again. IP: XXX.XXX.XXX.129. Username: ettore.cesarini@XXXXXX.YY.
vaultwarden    | [2022-11-30 15:00:49.621][response][INFO] (login) POST /identity/connect/token => 400 Bad Request

**Comment by Akkowicz** [comment]
There was a desktop client update yesterday, maybe it broke compatibility:
https://github.com/bitwarden/clients

I'm still on previous version: "Desktop v2022.10.1" and login works as expected.
Ask user to try the version I've mentioned above.

**Comment by BlackDex** [comment]
It works ok for me using the `testing` tagged release of Vaultwarden.
There are some changes in the new clients which need some of the new features/code in the `testing` tagged release.
Either use the `testing` tagged release (for now), or revert the desktop client version.

**Comment by ecesarini** [comment]
Tank you all,
I tried desktop 2022.10.1 and the problem doesn't occour.
I'm running vaultwarden in production so for the moment I think I'll wait for the new vaultwarden stable release. I'll suggest the user to install previous version waiting for a new update.

Thank you very much

**Comment by ecesarini** [comment]
Hi,
I updated web-vault to 2022.11.1 and vaultwarden to 1.26.0:testing.
Now in desktop client v2022.11.0 on windows 10 i can access to web vault but there's another problem. It looks like the client can't sync with the vault.
The client return error **Syncing fail**
In the container during the event you can read these logs:
```bash
vaultwarden    | [2022-12-02 15:11:05.886][request][INFO] POST /identity/connect/token
vaultwarden    | [2022-12-02 15:11:05.888][response][INFO] (login) POST /identity/connect/token => 400 Bad Reques
```
Previous version 2022.10.1 works fine.

**Comment by BlackDex** [comment]
I suggest to fully logout in the desktop client and try again.
It works fine for me using the `vaultwarden:testing` image and the latest desktop client.

Could you please post the **Support String** which you can generate via the `/admin/diagnostics` interface?

**Comment by ecesarini** [comment]
> I suggest to fully logout in the desktop client and try again. It works fine for me using the `vaultwarden:testing` image and the latest desktop client.
> 
> Could you please post the **Support String** which you can generate via the `/admin/diagnostics` interface?

Hi,
thank you. I tried login/logout several times. I will try again.

Here's the support string
### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.26.0-8feed291
* Web-vault version: v2022.11.1
* Running within Docker: true (Base: Debian)
* Environment settings overridden: false
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: MySQL
* Database version: 10.6.4-MariaDB-1:10.6.4+maria~focal
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** 


```json
{
  "_duo_akey": null,
  "_enable_duo": false,
  "_enable_email_2fa": true,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_smtp_img_src": "cid:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 100,
  "database_timeout": 30,
  "database_url": "*****://***********:***********@*******/**************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://************.****.**",
  "domain_origin": "*****://************.****.**",
  "domain_path": "",
  "domain_set": true,
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "email_attempts_limit": 3,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 5 * * * *",
  "emergency_request_timeout_schedule": "0 5 * * * *",
  "enable_db_wal": true,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "password-dev",
  "invitations_allowed": false,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "Info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 100000,
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": true,
  "signups_domains_whitelist": "****.****.**",
  "signups_verify": true,
  "signups_verify_resend_limit": 0,
  "signups_verify_resend_time": 60,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": false,
  "smtp_from": "*******@*****.****.**",
  "smtp_from_name": "password-dev.XXXXXXX.YY",
  "smtp_host": "**********.****.**",
  "smtp_password": null,
  "smtp_port": 25,
  "smtp_security": "off",
  "smtp_ssl": false,
  "smtp_timeout": 15,
  "smtp_username": null,
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_syslog": false,
  "user_attachment_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "websocket_address": "0.0.0.0",
  "websocket_enabled": true,
  "websocket_port": 3012,
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>

**Comment by BlackDex** [comment]
Could you enable `LOG_LEVEL=debug` and try it again?
Maybe that will give us some more info.

**Comment by ecesarini** [comment]
> Could you enable `LOG_LEVEL=debug` and try it again? Maybe that will give us some more info.

Hi,
I fully removed bitwarden desktop client, reinstalled last version, and connected to the vault and now sync seems to work.
It's a litte strange.
I'll keep on testing

Thank you
