### ISSUE TITLE
Emergency access sends a lot of emails when the wait time period is reached

### ISSUE THREAD

**Issue by spctechdev** [dani-garcia/vaultwarden#2955]
### Subject of the issue
Vaultwarden sends too much emails when the emergency access wait time lapses or grantor approve the request

### Deployment environment

* Vaultwarden version: v1.26.0
* Web-vault version: v2022.10.0
* Running within Docker: true (Base: Debian)
* Environment settings overridden: false
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.35.4

* Other relevant details:

### Steps to reproduce
Make an emergency request for another account and wait the time the grantor setted.

### Expected behaviour
Only one or some emails to inform that the emergency access is pending

### Actual behaviour
The grantor receives a lot of emails when the emergency wait time is reached

### Troubleshooting data

![mails](https://user-images.githubusercontent.com/111750395/205474020-7e7c49cd-a670-4579-904b-4b7ef619d5f1.png)

**Comment by tessus** [comment]
@BlackDex the PR was approved by Dani. Doesn't that mean you can merge it to main?
Once again. just wondering. It always depends on how a project is run.
