### ISSUE TITLE
Sync fails on self-hosted vaultwarden

### ISSUE THREAD

**Issue by Nos78** [dani-garcia/vaultwarden#2958]
I have been running a self-hosted vaultwarden for several weeks now without issue (having been a previous user of a self-hosted bitwarden installation a couple of years ago, I found my way back to vaultwarden back in September and have been running since then without issue).

A couple of days ago, I found I was no longer able to log into my vault - I was getting the error (I paraphrase) 2fa_incomplete_record, and a quick google search revealed the problem to be incompatible characters in the database, with a solution to be running a bunch of queries to set the charset to be utf8mb4 (or something, I have the actual SQL saved - THANKFULLY - in case you need to see it to undo whatever I have now broken.,..)

After running the queries, it appeared to fix my database with respect to the users with 2FA being unable to log in.

However, it appears to have broken the sync! Which, if you discount being unable to login, is the worst thing that could have happened to a password manager! :smile: 

On the positive side, I finally got around to fixing why my log files were zero length - permissions in my .service file being incorrect - I use ProtectSystem=Strict but had not specified /var/log as a writable directory, only allowing /var/lib/vaultwarden in the list of ReadWritePaths

Having fixed my log files, I see that "Handler Sync" thread is panicking, giving a GET /api/sync/ => 500 Internal Server Error

Digging a little deeper, I see:
```
    [2022-12-05 02:54:09.687][panic][ERROR] thread 'rocket-worker-thread' panicked at 'Error loading ciphers: 
    DatabaseError(Unknown, "Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT)
    for operation '='")': src/db/models/cipher.rs:585
```

At which point I stopped digging, because that's the exact collation that I used in my previous bunch of SQL statements to fix the 2FA problem.

Can someone please provide assistance - whilst I am a competent software engineer, I'm not familiar enough with vaultwarden, or rust, to investigate this and then generate the SQL I'm going to need to fix my database. Having used google earlier to find the previous SQL statements, I'm loathe to do this again in case I create yet another problem for myself :rofl: 

### Deployment environment

GNU/Linux, google cloud VM, running Ubuntu, Kernel 5.15.0-1021-gcp x86_64

I Built vaultwarden from source, so as to negate the need for docker and its ridiculously sized overheads.

On my admin page, all tabs work except for "Diagnostics", it gives a 404 not found, so unfortunately I cannot provide or generate a support string - the log says
```
[2022-12-05 03:04:49.960][request][INFO] GET /admin/diagnostics
[2022-12-05 03:04:49.967][_][WARN] Request guard `AdminToken` is forwarding.
[2022-12-05 03:04:49.971][_][WARN] Response was `None`.
[2022-12-05 03:04:49.971][_][WARN] Responding with registered (not_found) 404 catcher.
```

* Install method:
Built from source

* Clients used: 
Android app, browser login, chrome extension, linux desktop GUI app

* Reverse proxy and version: 
Apache2

* MySQL/MariaDB or PostgreSQL version: 
mysql  Ver 8.0.31-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
/usr/sbin/mysqld  Ver 8.0.31-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

### Steps to reproduce

Vaultwarden is ran from a .service file - no issues encountered until the last 48 hours, when 2FA stopped working (without any intervention from my part - when 2FA logins actually stopped working, I couldn't say for sure, since I enabled the "remember" option, and had not needed a hard login until I installed a new browser and tried logging in with it.

I can say for sure that I have not made any updates to the binary or config since October 29th 2022, and I can say for definate that 2FA was working two weeks ago when I logged into my vault on a new laptop. Sometime between mid-November and now, 2FA login stopped working, and I "fixed" it using the following SQL:

```sql
    # https://github.com/dani-garcia/vaultwarden/wiki/Using-the-MariaDB-(MySQL)-Backend#foreign-key-errors-collation-and-charset

    # Change collation and charset of the database 'bitwarden'
    ALTER DATABASE `bitwarden` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

    # Convert all tables (inc. text fields) - COPY THE OUTPUT!
    SELECT CONCAT('ALTER TABLE `', TABLE_NAME,'` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;') AS CharSetConvert
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA="bitwarden"
    AND TABLE_TYPE="BASE TABLE";

    # Disable foreign key checking temporarily, before running the above copied output
    SET foreign_key_checks = 0;
    ALTER TABLE `__diesel_schema_migrations` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_un
icode_ci;
    ALTER TABLE `attachments` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    ALTER TABLE `ciphers` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    ALTER TABLE `ciphers_collections` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8b4_unicode_ci
;
    ALTER TABLE `collections` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    ALTER TABLE `collections_groups` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
;
    ALTER TABLE `devices` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    ALTER TABLE `emergency_access` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    ALTER TABLE `favorites` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    ALTER TABLE `folders` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    ALTER TABLE `folders_ciphers` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    ALTER TABLE `groups` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    ALTER TABLE `groups_users` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    ALTER TABLE `invitations` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    ALTER TABLE `org_policies` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    ALTER TABLE `organizations` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    ALTER TABLE `sends` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    ALTER TABLE `twofactor` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    ALTER TABLE `twofactor_incomplete` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    ALTER TABLE `users` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    ALTER TABLE `users_collections` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    ALTER TABLE `users_organizations` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    SET foreign_key_checks = 1;
    # verify it all worked, by running a query on at least one table:
    SHOW CREATE TABLE `users`;

    # Note, it should say CHARSET=utf8mb4 at the end
```

**Comment by Nos78** [comment]
Okay, sorry for the post - but this might be useful for anyone else who has done the same thing that I have done today...

Whatever broke my 2FA may well have broken other peoples self-hosted solutions as well, so this is worth posting - they might have also found the same page and followed those instructions to change the charset to utf8mb4_unicode_ci - and break their sync in the process!

It seems the solution was rather simple in the end... I googled for `utf8mb4_0900_ai_ci` and what was the first thing I see? A post about MySQL changing its default unicode character set from _unicode_ci to _0900_ai_ci :rofl: Applying some logic to this, I thought - hang about, I can just use the same SQL I executed earlier, but this time use the correct charset that my log file is telling me it wants! My logic went thus: My database tables are ALL now using the charset utf8mb4_unicode_ci - but the log file says that there are an illegal mix of collations... hmm, well then logically this MUST be rocket, because my DB is all consistent!

The new SQL I executed goes like this (and I cut out the middle bit, since you MUST paste in the correct generated queries yourself - mysql will output all the correct queries, remove the | table bits and paste them into the script before executing it) :

```sql
    -- utf8mb4_0900_ai_ci - NEW
    -- utf8mb4_unicode_ci - OLD

    -- Change collation and charset of the database 'bitwarden'
    ALTER DATABASE `bitwarden` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

    -- Convert all tables (inc. text fields) - COPY THE OUTPUT and PASTE it as indicated below!
    SELECT CONCAT('ALTER TABLE `', TABLE_NAME,'` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;')   
    AS CharSetConvert
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA="bitwarden"
    AND TABLE_TYPE="BASE TABLE";

    -- Disable foreign key checking temporarily, and run the output of the above (after removing the |+| table characters)
    SET foreign_key_checks = 0;
    --
    -- CUT & PASTE the OUTPUT from the SELECT CONCAT... command you just executed --
    --
    SET foreign_key_checks = 1;

    -- verify it all worked, by running a query on at least one table:
    SHOW CREATE TABLE `users`;

    -- Note, it should say CHARSET=utf8mb4 at the end, and utf8mb4_0900_ai_ci

```

For completeness, here is the full set of commands that where generated for me (other installations may be different, the first SELECT CONCAT(...) statement generates these queries:
```sql
    SET foreign_key_checks = 0;
    ALTER TABLE `__diesel_schema_migrations` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `attachments` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `ciphers` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `ciphers_collections` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `collections` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `collections_groups` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `devices` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `emergency_access` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `favorites` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `folders` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `folders_ciphers` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `groups` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `groups_users` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `invitations` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `org_policies` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `organizations` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `sends` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `twofactor` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `twofactor_incomplete` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `users` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `users_collections` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    ALTER TABLE `users_organizations` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
    SET foreign_key_checks = 1;
```

And for background purposes - what I discovered from the above mentioned google search - it appears that the default utf8 charset type has changed from (the now old default) `utf8mb4_unicode_ci` to a new default of `utf8mb4_0900_ai_ci`,
And for why? So that it can cope with all these extra emojis that keep appearing... and the SQL queries that I ran to fix the initial 2FA_incomplete_record problem that appeared over the last several days has changed all my tables to be unicode, using the old (now wrong) default. The page I used was dated sometime in 2021.

I was unable to find out when this default charset changed from _unicode_ci to _0900_ai_ci - but I used the same SQL to fix it, so now it all works perfectly.

**Comment by Nos78** [comment]
Attempt to close this issue...

**Comment by Nos78** [comment]
@BlackDex thanks for that pointer! You're right, I hadn't stopped vaultwarden before chomping on the database - AFAIR my default was utf8mb4_unicode_ci before I encountered the 2FA_incomplete_record issue (and I double checked this by opening phpmyadmin that I had forgotten I'd installed) and sure enough, thats my db default.

I don't know where the different collation came from - the reason I subsequently changed from unicode_ci to 0900_ai_ci was because the error log suggested that rocket was looking for this? I'd prefer to put it back to `utf8mb4_unicode_ci` if it's going to sync and 2FA works. Would you know where this other collation came from - like it appeared out of nowhere :rofl: - and thanks for the input in any event.

**Comment by BlackDex** [comment]
Well, if one tables still had that collation, or maybe the database it self, because some MySQL upgrade changed it, that could have caused this. And then a new Vaultwarden migration created or updated some tables which then got the 'new' defaults.

Reverting all tables back to Unicode will not be an issue i think, since 0900 is just an extension on top of Unicode as far as i understand, save there should be no characters containing those extended range in the database at all.
