### ISSUE TITLE
Unable to list organization collections at element creation

### ISSUE THREAD

**Issue by Nyxtorm** [dani-garcia/vaultwarden#2975]
### Subject of the issue
Unable to list organization collections at element creation and therefore to create new elements.

### Deployment environment

- Vaultwarden version: v1.26.0-b7c9a346
- Web-vault version: v2022.11.1
- Running within Docker: false (Base: Debian)
- Environment settings overridden: false
- Uses a reverse proxy: true
- IP Header check: true (X-Real-IP)
- Internet access: true
- Internet access via a proxy: false
- DNS Check: true
- Time Check: true
- Domain Configuration Check: true
- HTTPS Check: true
- Database type: SQLite
- Database version: 3.39.2
- Clients used: Windows / Android / Chrome / Web
- Reverse proxy and version: Nginx 1.23.2

Other relevant details:
-  Chrome version: 108.0.5359.99
-  Chrome Plugin version: 2022.10.1
-  Windows 11 22H2 22621.900
- Nginx reverse proxy 1.23.2 w/ Debian 11 6.0.3

### Steps to reproduce

1. Be the owner of the organization or a user with the appropriate rights and attempt to create an item on the organization

### Expected behaviour

The existing collections should be listed to create the element.

### Actual behaviour

- No collection available at element creation:

<img src="https://i.imgur.com/tKsmItM.png" width=50% height=50%>

- Impossible to see in which collection the element is stored when editing it.
- The only way to have visibility on the collections is through the Organizations tab from the owner account
- This happened with the last update I did. So, the problem should be between commit `8feed2916fee7a06e82e6df5070a9c4ee042bcd0` and commit `b7c9a346c1f7f664f2bda997632cb14fdd55b94d`.

**Comment by BlackDex** [comment]
Hmm, it looks like the new version of the extension has some issues with syncing.
Syncing still seems to work for the mobile client, at least, it doesn't report an error. But it also doesn't list the collections there either. This is something we need to look into.
