### ISSUE TITLE
CSP viomation error

### ISSUE THREAD

**Issue by zoic21** [dani-garcia/vaultwarden#2988]
### Subject of the issue

Issue when I want to download attach file (on webapp and android app) due to CSP violation

### Deployment environment

* vaultwarden version: 1.26.0

* Install method: Docker

* Clients used: web vault

* Reverse proxy and version: nginx, I don't known the version

* MySQL/MariaDB or PostgreSQL version: by default

* Other relevant details:

### Steps to reproduce

Try to donwload attach file

### Expected behaviour

Get my file

### Actual behaviour

Turn indefinitely

### Troubleshooting data

![image](https://user-images.githubusercontent.com/1536036/207782147-a233c811-cd10-43fc-a7b5-34bddeceb83b.png)

**Comment by BlackDex** [comment]
Are you sure you configured the domain correctly?
Please check the `/admin` interface and go to the diagnostics page.
Verify if all is ok.

This should work because the domain on which your instance is running is always allowed.

**Comment by zoic21** [comment]
Hello,

Really sorry for the bother, I try to pay attention to this kind of thing. I must not have been awake...
