### ISSUE TITLE
TOTP not working with some services

### ISSUE THREAD

**Issue by 0xab3d** [dani-garcia/vaultwarden#3001]
### Subject of the issue

TOTP not working with some services such as _sucuri.net_

### Deployment environment

* vaultwarden version: 1.26

* Install method: Docker

* Clients used:  web vault and Edge extension

* Reverse proxy and version:  Sucuri SaaS

* MySQL/MariaDB or PostgreSQL version: 

* Other relevant details:

### Steps to reproduce

Edit the Sucuri entry, try to add the TOTP seed, nothing happens. Once I click save, the Edge extension just logs out. Replicated this on the web as well.

### Expected behaviour

TOTP seed starts providing the 6 digit codes.
### Actual behaviour

The Edge extension and the web session logs out when I save the changes.

**Comment by BlackDex** [comment]
I'm not sure how Sucuri SaaS works. Does that add an extra layer of authentication, then that could be an issue.

**Comment by 0xab3d** [comment]
Hey, it is a reverse proxy (acting as WAF)

**Comment by BlackDex** [comment]
I think the WAF is removing some headers or other items, which breaks either the client or server.

Check the logs, maybe set the log-level to debug for some more info.

**Comment by 0xab3d** [comment]
You're totally right. I have checked the logs and turned out the WAF is blocking PUT methods..
