### ISSUE TITLE
Valutwarden not comaptible with Bitwarden client application v2022.11.0 (Mac OS - AppStore)

### ISSUE THREAD

**Issue by makovice** [dani-garcia/vaultwarden#3017]
### Subject of the issue
Prelogin endpoint (/identity/accounts/prelogin) does not work. 

### Deployment environment

* vaultwarden version: vaultwarden/server:testing (1.26.0-10dadfca)

* Install method: Docker image

* Clients used: Mac OS desktop 2022.11.0, Architecture arm64

### Steps to reproduce

When connecting from client app, found in webserever log

   ... "GET /api/devices/knowndevice/xxx@xxxx.cz/xxxxxxxxxxxxxxx HTTP/2.0" 404 597 "-" ...
   ... "POST /identity/accounts/prelogin HTTP/2.0" 404 597 "-" ...
   ... "POST /identity/connect/token HTTP/2.0" 400 227 "-" ...

When revert to old client app (found v2022.5.0)

   ... "POST /api/accounts/prelogin HTTP/2.0" 200 32 "-" ...
   ... "POST /identity/connect/token HTTP/2.0" 200 3397 "-" ...

### Expected behaviour
So maybe only changed endpoint from /api/... to /identity/... ???

**Comment by BlackDex** [comment]
Already fixed in `main` branch and `testing` tagged docker images.
