### ISSUE TITLE
Problems moving data from one organization to another

### ISSUE THREAD

**Issue by tsfuchs** [dani-garcia/vaultwarden#3047]
Hi there,

I'm having trouble moving data from one organization to another in vaultwarden. I created an organization and imported an old Keepass backup into it, and then created a second organization. I'm trying to selectively move data from the import organization to the second one to rebuild the database, but I keep getting an error message saying that I can't move x out of x entries. I'm not sure why this is happening or if I'm doing something wrong. Can you help me understand what's going on and how to fix it?

![image](https://user-images.githubusercontent.com/13419498/209586376-ada60ea8-2843-435e-9eaa-e7d9f9bd6880.png)

Thanks in advance for your help!

**Comment by BlackDex** [comment]
See #3016

**Comment by tsfuchs** [comment]
HI @BlackDex ,

but I'm not cloning but moving and the other organizations are shown.
And as you can see in the Bitwarden documentation, it is intended what I want to do:
https://bitwarden.com/de-DE/help/about-collections/#move-an-item-between-collections

**Comment by BlackDex** [comment]
@tsfuchs , that only counts for collections within the same organization, not different ones. You can't move items between organizations.

**Comment by tsfuchs** [comment]
@BlackDex I understand that allowing anyone to move shared data could potentially cause issues. However, I still find it disappointing that the owner of an organization is not able to do so. Is this a decision made by Bitwarden and is it something that Vaultwarden is unable to change due to compatibility reasons or is this behavior specific to Vaultwarden?

**Comment by BlackDex** [comment]
You can clone it to your personal vault, and then move it, that is the way for now.

Vaultwarden tries to stay as close as possible to Bitwarden. Also, we do not have the knowledge and manpower to modify the web-vault over and over. And, other clients would still not be able to do it.
Nor, i would want this btw. Without Bitwarden there wouldn't be a Vaultwarden.
