### ISSUE TITLE
Android bitwarden app can't connect to vaultwarden server

### ISSUE THREAD

**Issue by sbhrepo** [dani-garcia/vaultwarden#3075]
### Discussed in https://github.com/dani-garcia/vaultwarden/discussions/3044

<div type='discussions-op-text'>

<sup>Originally posted by **sbhrepo** December 25, 2022</sup>
for sometime I have docker vaultwarden hosted on synology with lets encrypt certificate. It worked fine no issues. I was able to connect from desktop, laptop and android phone.
few days ago I decided to upgrade the the vaultwarden image as new multiple version come between then to now.
I toke the vaultwarden down, backed up the data, removed the container and old image and download the latest image.
I setup the configuration and deployed the new container.
I was able to connect from my desktop and laptop with no issue and saw all my data. and the connection was secured (https connection all good).
but when I tried to connect from my android phone it was refused. it was try for around 30 second to a minute and tell me that it can't connect (the messages not detailed but got different messages in different attempts). I clean the cache and data from the app and try again, same problem. I uninstalled the app and reinstall it, same problem.
I toke 2 extra android devices, one the same mode and my and one different model. I installed bitwarden app on both android devices and both work with no problem.
only my device that was connected before the upgrade has the problem.
at this point I don't know how to continue and what I can do.
its not clear to me if it's a bad state on my device that prevent it working or some information on the database that was transferred to the upgraded/new server not like my device as some identity not much now.
I done many searches for this issue but I didn't find any solution to this problem.
I'll appreciate any suggestion\help available.
   </div>

**Comment by BlackDex** [comment]
Duplicate
