### ISSUE TITLE
Organizations are not all displayed

### ISSUE THREAD

**Issue by alexgeraweb** [dani-garcia/vaultwarden#3148]
### Organizations are not all displayed
Organizations menu item
If you open the organizations drop down here, not all organizations appear there.
I have created more than 50 organizations, but they are not displayed in the list, because the total page is not as high as the list (in the overlay) of organizations.

### Deployment environment

Versions
Server Installed Ok
1.27.0
Server Latest
1.27.0
Web Installed
2022.12.0
Database
SQLite: 3.39.2
Checks
Running within Docker
Yes (Base: Debian)
Environment settings overridden
Yes
Uses a reverse proxy
Yes
IP header Match
Config/Server: X-Real-IP
Internet access Ok
Yes
Internet access via a proxy
No
DNS (github.com) Ok
140.82.121.4
Date & Time (Local)
Server: 2023-01-16 11:37:05 +01:00
Date & Time (UTC) Ok
Server: 2023-01-16 10:37:05 UTCBrowser: 2023-01-16 10:37:05 UTC
Domain configuration Match HTTPS

* vaultwarden version: 1.27.0

* Install method:

* Clients used: web vault

* Reverse proxy and version: 

* MySQL/MariaDB or PostgreSQL version: 

* Other relevant details:

### Steps to reproduce
Create many many organizations and then open the list
![2023-01-16 11_43_27-](https://user-images.githubusercontent.com/122787358/212659752-60608f90-7bae-4ea9-942d-b59d9a9c2c50.png)

**Comment by BlackDex** [comment]
This is a Bitwarden client issue. Not something we can fix on our side that easily. Though i doubt Bitwarden will give this any prio since it's not really build for this amount of organizations i think.

**Comment by BlackDex** [comment]
Ok, I have created a PR for this at Bitwarden. Not sure if they will include it.
In the meantime i will create a PR for our custom web-vault to have the exact same patch.
