### ISSUE TITLE
Error importing encrypted Bitwarden json

### ISSUE THREAD

**Issue by themanbornwithin** [dani-garcia/vaultwarden#3155]
I exported an Organization to an encrypted file, and immediately tried to import it into a new Organization. I get an error stating

`Error decrypting the exported file. Your encryption key does not match the encryption key used to export the data.`

Server Version 1.27.0
Web Version 2023.1.0

**Comment by BlackDex** [comment]
You can't use the default `Account Restricted` export.
You need to select the `Password Protected` export type.

The first can only be used for the exact same organization, and not imported into an other.

![image](https://user-images.githubusercontent.com/610450/213533098-ba099af5-714f-4088-9565-cc737bccac90.png)
