### ISSUE TITLE
Wrong username or password after updating from 1.26.0 to 1.27.0

### ISSUE THREAD

**Issue by mkatanski** [dani-garcia/vaultwarden#3173]
### Subject of the issue

After updating Vaultwarden docker instance from 1.26.0 to 1.27.0 I cannot login to my existing account and I'm 100% sure my login and passwords are ok. I'm using backup copy of `/data` folder on my server so the user exists. Downgrading to 1.26.0 solves the issue immediately. And it happens in both desktop clients and web vault so I guess it has nothing to do with the clients.

I saw some tips to backup locally vault, and start database from scratch and then import vault manually for the 'new" user. But thats problematic as I'm not the only user of this app.

### Deployment environment

* vaultwarden version: 1.27.0

* Install method: Docker image

* Clients used: web vault, mac client, firefox client, ios client

* Other relevant details: I'm using Synology NAS to run docker container

### Steps to reproduce
Update docker image from 1.26.0 to 1.27.0 w/o removing existing database. Then try to login in web vault. There should be an error message explaining that either username or password are incorrect. Which is not true.

### Expected behaviour
User should use his old username and password to login to web vault after update

**Comment by BlackDex** [comment]
Could you provide some logs?
What does the /admin interface tell you with the new version on how many users there are?
Are you using the latest versions of the Bitwarden Clients (I think not, because then you would have issues with 1.26).

**Comment by mkatanski** [comment]
It looks the issue fixed itself. I downgraded to 1.26.0 and upgraded to 1.27.0 and it works. I don't know why I couldn't authenticate myself previously. However, after reconnection the Firefox client says that is still connected to the 1.26.0 (maybe some cache?). Web admin says that server version is 1.27.0 and web installed is 2022.12.0.

Sorry for raising this "issue" 😅
