### ISSUE TITLE
Issue with Server side KDF Iterations not showing altered in db.sqlite3

### ISSUE THREAD

**Issue by jtbruins12** [dani-garcia/vaultwarden#3223]
### Subject of the issue

Issue with Client side KDF Iterations not showing altered in db.sqlite3. I recently updated my KDF iterations client side on the web vault to 600k and when looking at the sqlite database, it does not show that the iterations changed, it still shows 100k.
### Deployment environment

* Vaultwarden version: v1.27.0
* Web-vault version: v2022.12.0
* Running within Docker: true (Base: Debian)
* Environment settings overridden: false
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.39.2

### Steps to reproduce

I run Vaultwarden via a "stack" in portainer. I just changed the KDF iterations and then also changed my password and said for it to rotate my account keys and it seems it's still at 100k based on the database file.

### Expected behaviour

I would expect the database entry for my user account to be updated with the proper amount otherwise it makes me believe the key was not changed and the iterations did not change. I changed my password after changing it as well and it did not have an affect.
### Troubleshooting data

![image](https://user-images.githubusercontent.com/18764311/216805498-0fc1fc40-a4e2-4d01-a307-567a1bba2579.png)

 Here is a screenshot of the server side admin panel showing 600k iterations

![image](https://user-images.githubusercontent.com/18764311/216805051-472ec003-5c88-4870-96cc-c12a7edbbb16.png)

Here is a screenshot of the database for my account selecting password iterations from the table.

**Comment by jtbruins12** [comment]
lmao I'm stupid and there is literally a "client_kdf_iter" that I overlooked

**Comment by jtbruins12** [comment]
I restarted vaultwarden in-between chaning the password iterations and changing my password too.

**Comment by BlackDex** [comment]
Not sure what you are reporting here. But i think you tried to change the server side after the whole client change, and saw it didn't changed for your account.

That is true for the version of Vaultwarden you are using. That is fixed in the `testing` tagged images already. There it will increase your server side kdf on login.

**Comment by BlackDex** [comment]
Fixed already via #3163
