### ISSUE TITLE
[error][ERROR] 2FA token not provided

### ISSUE THREAD

**Issue by Y0ngg4n** [dani-garcia/vaultwarden#3226]
### Subject of the issue
Can not login with 2FA enabled.

If you remove 2FA in the Admin panel you can login again.
If you add 2FA back i can not login.

```
[2023-02-06 17:32:42.940][error][ERROR] 2FA token not provided
[2023-02-06 17:33:01.811][error][ERROR] 2FA token not provided
[2023-02-06 17:59:44.405][error][ERROR] 2FA token not provided
```

### Deployment environment

* vaultwarden version: 1.27.0
* Web version: 2022.12.0

* Install method: Docker (Kubernetes)

* Clients used: 
Web, Android, Firefox Extension

* Reverse proxy and version: 
Traefik + Letsencrypt

* Other relevant details:

### Steps to reproduce

Create a account at  https://vault.vaultwarden.net.
Add 2FA to your account at https://vault.vaultwarden.net
Write me to remove 2FA again. And login again. 

### Expected behaviour
Normal 2FA login

### Actual behaviour

I got the message that an error occurred

**Comment by BlackDex** [comment]
You probably have some security headers enabled your self on the reverse proxy. Like ModSecurity or something. This causes issues.
