### ISSUE TITLE
Collection access tab only displays admin users or higher

### ISSUE THREAD

**Issue by dpinse** [dani-garcia/vaultwarden#3279]
### Subject of the issue
 * Collection access tab only displays admin users or higher

### Deployment environment
* Vaultwarden version: v1.27.0
* Web-vault version: v2023.2.0
* OS/Arch: linux/x86_64
* Running within Docker: true (Base: Alpine)
* Environment settings overridden: true
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Time Check: true
* Domain Configuration Check: false
* HTTPS Check: true
* Database type: MySQL
* Database version: 10.6.12-MariaDB-log
* Clients used: Web vault
* Reverse proxy and version: Nginx 1.22
* Environment settings which are overridden: SIGNUPS_VERIFY_RESEND_TIME, ADMIN_TOKEN
### Steps to reproduce
1. Go to web vault
2. Go to the organization tab => your organization => collection options tab => access

### Expected behaviour
* Should also display users with manager or user roles

### Actual behaviour
* Only displays admins and owners in the access tab

**Comment by BlackDex** [comment]
Do those users have access to those collections configured? Or only for a specific collection?

**Comment by dpinse** [comment]
They have access to the collections, I can view the assigned collections perfectly in the users page of the org just not the access tab. Groups are displayed fine in the above mentioned issue as well.

**Comment by BlackDex** [comment]
Also, that new collection interface doesn't work at all for Vaultwarden currently.
There are a lot of changes we need to implement.
