### ISSUE TITLE
Organization not visible (groups not enabled yet).

### ISSUE THREAD

**Issue by popindavibe** [dani-garcia/vaultwarden#3314]
### Subject of the issue
Organization tab doesn't load. Errors in logs. Everything else appears to be working fine.

### Your environment (Generated via diagnostics page)
* Vaultwarden version: v
* Web-vault version: vv2023.2.0
* Running within Docker: false (Base: Debian)
* Environment settings overridden: true
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: MySQL
* Database version: 10.5.15-MariaDB-0+deb11u1
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** DOMAIN, SIGNUPS_ALLOWED, ADMIN_TOKEN, SMTP_HOST, SMTP_SECURITY, SMTP_PORT, SMTP_FROM, EMAIL_TOKEN_SIZE, EMAIL_EXPIRATION_TIME

```json
{
  "_duo_akey": null,
  "_enable_duo": false,
  "_enable_email_2fa": true,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_smtp_img_src": "cid:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "*****://**************************************************************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://*******************",
  "domain_origin": "*****://******************",
  "domain_path": "",
  "domain_set": true,
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "email_attempts_limit": 3,
  "email_expiration_time": 600,
  "email_token_size": 10,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Vaultwarden - IRAM",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "Info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 100000,
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": true,
  "signups_allowed": false,
  "signups_domains_whitelist": "",
  "signups_verify": false,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "***************************",
  "smtp_from_name": "Vaultwarden",
  "smtp_host": "************",
  "smtp_password": null,
  "smtp_port": 25,
  "smtp_security": "starttls",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": null,
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": 30,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_syslog": false,
  "user_attachment_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "websocket_address": "127.0.0.1",
  "websocket_enabled": true,
  "websocket_port": 3012,
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>
    

* vaultwarden version: 1.27.0

* Install method: compiled from source

* Clients used:  web vault

* Reverse proxy and version: Nginx

### Steps to reproduce
Upgrade to latest Vaultwarden and web vault.

### Expected behaviour

Access to organisation settings as before.

### Actual behaviour
Behaves like it's loading data, forever. I see errors in logs.

![image](https://user-images.githubusercontent.com/7958775/223142753-e1bb492b-19a4-4203-ab17-fb99526c0068.png)

### Troubleshooting data

```
Mar 06 15:42:28 vaultwarden-test vaultwarden[25923]: [2023-03-06 15:42:28.047][request][INFO] GET /api/organizations/xxxxxxxxxxxxxxxxxxxxxxxxxxx/groups
Mar 06 15:42:28 vaultwarden-test vaultwarden[25923]: [2023-03-06 15:42:28.048][vaultwarden::api::core::organizations][ERROR] Group support is disabled
Mar 06 15:42:28 vaultwarden-test vaultwarden[25923]: [2023-03-06 15:42:28.049][response][INFO] (get_groups) GET /api/organizations/<org_id>/groups => 400 Bad Request
```

**Comment by BlackDex** [comment]
This is fixed in `testing` images and `main` branch

**Comment by popindavibe** [comment]
Enabling groups got me a step further, as it now loads (painfully slowly) the entries. Not really usable though.

I'll wait for the next release before updating in production then. Thank you for the quick reply.

**Comment by BlackDex** [comment]
You are using a web-vault that doesn't match the server version i think.

**Comment by popindavibe** [comment]
Oh, ok. I usually just upgrade both Vaultwarden and webvault to latest release, I thought they were always in sync.

I've tried with the older webvault, all is well again, thanks :handshake:

**Comment by BlackDex** [comment]
Well, if you use the `main` branch or `testing` images, then yes. Else there could be a difference :)

**Comment by ghtm2** [comment]
Hi,

sorry for bumping a week old, resolved issue, but I've just now seen this.
> If you are using the stable Vaultwarden version, then you can only use 2022.12.x.

That info needs to be written down somewhere **visible**, because according to this the only two Linux distros packaging vaultwarden right now are doing it wrong:
Both Arch and Void Linux are on vaultwarden 1.27.0 and vaultwarden-web 2023.2.0.

> Well, if you use the `main` branch or `testing` images, then yes. Else there could be a difference :)

That is quite ambiguous, don't you think?

**Comment by BlackDex** [comment]
In the changelog we note which versions we updated the web-vault to.

The `latest` tagged images are based upon the _latest_ tagged version.
The `testing` tagged images are based upon the `main` branch, and are build as soon as we merge or push something to `main`.
Nothing ambiguous about that I think.

The same goes for the `bw_web_build` repo sorta. We do release some new versions there, but that is so that we can use those released versions within the main branch and test stuff.

It's also naive to think that a new web-vault release will always work without any update on the server side in my opinion.
I still want something like a compatibility matrix file or something where we can add this, but that still could be causing issues.
Even now, the current web-vault version isn't fully working on the `main` branch.

**Comment by stefan0xC** [comment]
> Both Arch and Void Linux are on vaultwarden 1.27.0 and vaultwarden-web 2023.2.0.

That's on them. As noted on the [third-party packages wiki page](https://github.com/dani-garcia/vaultwarden/wiki/Third-party-packages/): 

>⚠️ Be aware that the latest vaultwarden release is not always forward-compatible with the latest web-vault version, so you might want to [use an older version](https://github.com/dani-garcia/bw_web_builds/releases) of vaultwarden-web to ensure compatibility.

While I agree that this could be communicated more prominently maybe, making sure that the versions are compatible should be the downstream maintainers job.

**Comment by ghtm2** [comment]
> In the changelog we note which versions we updated the web-vault to.
> 
> The `latest` tagged images are based upon the _latest_ tagged version. The `testing` tagged images are based upon the `main` branch, and are build as soon as we merge or push something to `main`. Nothing ambiguous about that I think.
> 
> The same goes for the `bw_web_build` repo sorta. We do release some new versions there, but that is so that we can use those released versions within the main branch and test stuff.
> 
> It's also naive to think that a new web-vault release will always work without any update on the server side in my opinion. I still want something like a compatibility matrix file or something where we can add this, but that still could be causing issues. Even now, the current web-vault version isn't fully working on the `main` branch.

Which are all things one would know if one would follow the development closely.
The thing is, most people, including myself, just don't, sorry.

> > Both Arch and Void Linux are on vaultwarden 1.27.0 and vaultwarden-web 2023.2.0.
> 
> That's on them. As noted on the [third-party packages wiki page](https://github.com/dani-garcia/vaultwarden/wiki/Third-party-packages/):
> 
> > warning Be aware that the latest vaultwarden release is not always forward-compatible with the latest web-vault version, so you might want to [use an older version](https://github.com/dani-garcia/bw_web_builds/releases) of vaultwarden-web to ensure compatibility.

That's something you'd read at most once though.
At the next update three months down the road you'd have forgotten all about it.

> While I agree that this could be communicated more prominently maybe, making sure that the versions are compatible should be the downstream maintainers job.

Maybe, but the downstream maintainer has a few hundred different packages to keep track of.
Expecting them to be on top of the development and release practices of every single one is what I would call naive.

All I'm saying is that it needs better visibility, preferably on the release tags themselves.
A single line "Not downward compatible with vaultwarden 1.27.0" or some such on newer `bw_web_builds` tags may be sufficient.
