### ISSUE TITLE
Unable to write to log file. /data/log - v1.28.0-alpine

### ISSUE THREAD

**Issue by Pamalosebi** [dani-garcia/vaultwarden#3381]
### Subject of the issue

When upgrading to v1.28.0-alpine from v1.27.0-alpine the container doesn't start up.
It fails with a simple
> vaultwarden-app       | Error loading config:
> vaultwarden-app       |   Unable to write to log file. /data/log

I am using Docker compose and didn't change anything before upgrading.

I tested "chmod 777 -R /data/log", but that didn't help.

The Error disappears forcing version 1.27.0 -> "image: vaultwarden/server:1.27.0-alpine".

* PostgreSQL version: 15.2

### Steps to reproduce

> docker compose down
> docker compose pull
> docker compose up -d

Usually I just use "image: vaultwarden/server:alpine". Since that failed now I changed it to "1.27.0-alpine".
Which works again.

### Expected behaviour

Since I use Docker compose and I am just switching images without modifying anything in the env. I would say it should just run.

### Actual behaviour

It fails to start up. Apparantly caused by a non accessible /data/log.

**Comment by Pamalosebi** [comment]
Well... I guess that's not valid anymore:
## Logging to file
LOG_FILE=/data/log

Guess it has to be specified from now on:
## Logging to file
LOG_FILE=/data/log/my.log

**Comment by BlackDex** [comment]
I would be surprised if the previous would have worked at all if that was a directory before. We never appended a filename in the past. If, it would have logged to a file called `log`

**Comment by Pamalosebi** [comment]
I always just used the docker console logs. They were enough for me.
I just didn't know I needed to specify a proper file from now on. But it's fine to have one.
