### ISSUE TITLE
Allow noninteractive and silent usage (or stderr) for `vaultwarden hash`

### ISSUE THREAD

**Issue by dionysius** [dani-garcia/vaultwarden#3411]
### Subject of the issue

`vaultwarden hash` currently ask interactively for the password and there is no option to be silent. In my packaging environment there is a way to interactively ask the admin for a password at the right time of the installation. And I would like use this input to generate the argon2 hash and automatically place it in the right place of the config file.

Suggestion: I'd like to pass in the password via STDIN and get only the hash out via STDOUT. (Although prefixed with `ADMIN_TOKEN=` is also fine, to make life easier for you)

### Deployment environment

* vaultwarden version: 1.28.1

* Install method: debian-packaging (built from source)

**Comment by BlackDex** [comment]
I'm not a big fan of piping passwords actually.
While it maybe would be fine for your use case, people tend to use the easy stuff and then passwords end up in the history.

Not sure if you can depend on the argon2 cli tool and use that? That does support what you want.

**Comment by dionysius** [comment]
I totally understand you have different goals with the command, just asking. Using vaultwarden would've saved me declaring this dependency and maintaining the recommended settings, but it's not a big deal.
