### ISSUE TITLE
Live sync for organization items only working when not using roles / groups

### ISSUE THREAD

**Issue by wucherpfennig** [dani-garcia/vaultwarden#3413]
### Subject of the issue
* live sync for organization items **does not work** if you are using roles / groups. 
* live sync **does not work** if you are adding members via group to a collection
* live sync **works** only if you are adding a member directly to a collection

### Deployment environment
* vaultwarden version: 1.28.1-alpine
* Install method: docker
* Clients used: all (tested: Windows Desktop, Browser, Firefox, Chrome)
* Reverse proxy and version: traefik-2.9.9
* MySQL/MariaDB or PostgreSQL version: 8.X
* Other relevant details: websocket works as without using groups everything runs as expected

### Steps to reproduce
1. Create an organisation
2. Create a collection
3. Create a group
4. Create two test accounts
5. assign one account to the group (3) and then the group (3) to the collection (2)
6. assign one account directly to the collection (2)
7. add / update / delete items in the collection (2)

**Result**
* account from 5: will only see the changes via reload
* account from 6: will see the changes immediately

### Expected behaviour
Live sync all the items to all the group members not only to the "hardcoded" directly assigned collection members.

### Actual behaviour
Changes from organization members (independent whether using groups or not) will be reflected immediately to the organization owner but if the owner / somebody else creates a new entry in the collection this change will only be available after a "hard" reload (ctrl+shift+r).

This issue is resolved by no using groups! By not using them everything works as expected.

BR wucherpfennig

**Comment by BlackDex** [comment]
Thanks for the report.
I want to note that groups is still an experimental feature. But we do need reports like this to make it better.

**Comment by wucherpfennig** [comment]
We are very much aware of that "experimental" state but to be honest until now everything else works great and it saves us a lot of time managing our accounts and collections. 👍🏻

**Comment by BlackDex** [comment]
Good to hear 😄 . It's probably a query which needs some extra joins (which i do not like)

**Comment by ghunti** [comment]
I have the same issue running 1.29.0

**Comment by BlackDex** [comment]
> I have the same issue running 1.29.0

Which is logical, since the issue is still open ;)

**Comment by xKugeki** [comment]
Are there any new information about bug fixing this problem ^^?
Or workarounds with groups enabled + Live Sync :)

**Comment by BlackDex** [comment]
Not from my part yet. I have not found the time or will to try and tackle this specific issue.
I have some ideas to try and use sub-select queries to maybe tackle this in a bit nice way instead of creating complex joins.
But not yet started on it. So if somebody else finds this an interesting item to pickup, please do not hesitate, there is a `help-wanted` label there for a reason ;)
