### ISSUE TITLE
Unable to create new organisation collections - An unexpected error has occured.

### ISSUE THREAD

**Issue by czarau** [dani-garcia/vaultwarden#3484]
[vaultwarden::api::core::organizations::_][WARN] Data guard `JsonUpcase < NewCollectionData >` failed: Parse("{\"groups\":[],\"name\":\XXXXXX\"}", Error("missing field `Users`", line: 1, column: 119)).

**Comment by BlackDex** [comment]
Which version of Vaultwarden and the web-vault are you using.
What way did you installed Vaultwarden?

**Comment by czarau** [comment]
Installed following this guide... **https://illuad.fr/2020/06/11/install-a-vaultwarden-server.html** on Rocky9
Version of Vaultwarden is current pull.
WebVersion may be out of date... let me check... sorry, still getting my head around this.

**Comment by czarau** [comment]
Oh dear... my fault.. old WebVersion... Thanks for heading me in the right direction. Sorry

**Comment by BlackDex** [comment]
If you used the vault version from that site, then it's very outdated and not compatible
