### ISSUE TITLE
Cant pull docker image due to distribution manifest v1

### ISSUE THREAD

**Issue by StepanKuklis** [dani-garcia/vaultwarden#3489]
### Docker image can't be pulled due to v1 manifest

Hello, when I try to
`docker pull vaultwarden/server:latest `
I get error
`latest: Pulling from vaultwarden/server
mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'`

I googled a bit, and I think there is nothing I can do from my side, so could you please update the manifest?
I'm doing this on just updated Ubuntu 20.04.6 LTS, Docker version 19.03.3, build a872fc2

thank you
### Deployment environment

* vaultwarden version:
vaultwarden/server:latest
DIGEST:sha256:04691aaf1d8531ccb796de620841c030ecfd45613388a2e6a6a9434dc5d14d9d

* Install method:
docker image
* Clients used: 

* Reverse proxy and version: 

* MySQL/MariaDB or PostgreSQL version: 

* Other relevant details:

### Steps to reproduce

`docker pull vaultwarden/server:latest`
### Expected behaviour

Pull latest image of vaultwarden docker image.
### Actual behaviour

Docker refused to pull latest image ( https://hub.docker.com/layers/vaultwarden/server/latest/images/sha256-04691aaf1d8531ccb796de620841c030ecfd45613388a2e6a6a9434dc5d14d9d?context=explore ).

**Comment by BlackDex** [comment]
I suggest to update your docker version.
See https://docs.docker.com/engine/install/ubuntu/

**Comment by StepanKuklis** [comment]
Oh, I see now. You are absolutely right. I didn't checked what is the latest version. After manually updating everything is fine. Sorry for such a silly issue..
