### ISSUE TITLE
Latest testing version returns 404 when creating a new org

### ISSUE THREAD

**Issue by empowerists** [dani-garcia/vaultwarden#3506]
### Subject of the issue
Latest testing version returns 404 when creating a new org

### Deployment environment
Vaultwarden version: v1.28.1-1ec049e
Web-vault version: v2023.4.0
OS/Arch: linux/x86_64
Running within Docker: true (Base: Alpine)
Environment settings overridden: true
Uses a reverse proxy: true
IP Header check: true (X-Real-IP)
Internet access: true
Internet access via a proxy: false
DNS Check: true
Time Check: true
Domain Configuration Check: false
HTTPS Check: true
Database type: MySQL
Database version: 10.6.12-MariaDB-log
Clients used: Web vault
Reverse proxy and version: Nginx 1.22
Environment settings which are overridden: SIGNUPS_VERIFY_RESEND_TIME, ADMIN_TOKEN

### Steps to reproduce
Goto the organizations tab. Click new organization. It loads forever and the returns 404 for /api/plans

### Expected behaviour
/api/plans should return a valid response. 

### Troubleshooting data
![image](https://user-images.githubusercontent.com/129067916/236001202-231d3cda-6c3e-45c8-88f3-7f4004d51563.png)

Going to https://vault.placeholder.com/api/plans in a browser returns a response but I suspect some things were changed on the Bitwarden side in v2023.4.0.

**Comment by BlackDex** [comment]
Your domain is also not valid according to the checks. Please check the settings and try again.

**Comment by empowerists** [comment]
Those checks are intentional. I made some Nginx conf changes to restrict the admin panel to our local network. Using the latest stable alpine 1.28.1 build works perfectly fine. I also get the response when querying that endpoint manually.

![image](https://user-images.githubusercontent.com/129067916/236004938-b3d76dc7-6798-4ac4-b3d2-a04c41bce268.png)

**Comment by empowerists** [comment]
You're right, it seems to add a tailing slash when querying the endpoint. I put a bandaid on this by adding the tailing slash to the endpoint and recompiling but this isn't a good fix long term

**Comment by stefan0xC** [comment]
> but this isn't a good fix long term

Why not? As long as the client only asks for `/api/plans/` and not also `/api/plans` this is exactly the fix that is needed.

**Comment by tessus** [comment]
I just ran into the same issue and my checks are all ok. It's a bummer, because I actually needed to create an org today.
Is there any chance this can be fixed asap? If not, I can also use empowerists workaround and add the slash and recompile. But I'd say this is a rather high priority issue.

Btw, Sergio fixed the issue that stefan0xC opened in https://github.com/SergioBenitez/Rocket/commit/56cf905c6edcea672ef9896dd3e1da7593da793c

**Comment by BlackDex** [comment]
> Btw, Sergio fixed the issue that stefan0xC opened in [SergioBenitez/Rocket@56cf905](https://github.com/SergioBenitez/Rocket/commit/56cf905c6edcea672ef9896dd3e1da7593da793c)

He also mentioned on Matrix that he is not going to implement the whole `/` stuff into 0.5.
Because i had several issues trying to still fix it. And I showed him my changes for Vaultwarden.
So, i think i will use the fearing to strip the trailing `/` and revert all changes hehe.

**Comment by stefan0xC** [comment]
@BlackDex are there other issues with the significance of the trailing slashes or is it just a precaution?

**Comment by BlackDex** [comment]
Well, there are several corner cases which could cause issues.
Like our sub-path for example.

And it looks more like a breaking change. But it just needs more thought before these changes.

**Comment by crazyc4t** [comment]
I had this problem as well, thought it was the websocket not connecting but is this `/api/plan` that is not enabling me to create organizations, I used this script to create vaultwarden inside an LXC container in proxmox: https://github.com/tteck/Proxmox/raw/main/ct/vaultwarden.sh

**Comment by BlackDex** [comment]
Once #3502 is merged, it will solve this.
