### ISSUE TITLE
Item moves between collections requiring manual sync

### ISSUE THREAD

**Issue by AlmightyJojo** [dani-garcia/vaultwarden#3534]
### Subject of the issue
Item moves between collections requiring manual sync

### Deployment environment

Server Installed = 1.28.1
Web Installed = 2023.3.0b
Database = SQLite: 3.39.2
OS/Arch = linux / x86_64
Running within Docker = Yes (Base: Debian)
Environment settings overridden = Yes
Uses a reverse proxy = Yes
IP header Match = Config/Server: X-Real-IP

Websockets enabled and functional.
Single Org deployment.  Org's users personal Vaults disabled.
Collections with group permissions.
Local deployment.  No Inet.

* Install method:  Docker Compose - Debian 11

* Clients used: Web, Firefox Extension, Windows Desktop app

* Reverse proxy and version: Nginx Proxy Manager 2.10.1

### Steps to reproduce

Windows desktop client:  Existing item in collection A.  Move item from collection A to collection B
Firefox extension:  Unlock vault and view collection B.  Item not present.  Settings - sync vault now.  Review Collection B.  Item now present.

docker-compose up -d

- WEBSOCKET_ENABLED=true
- LOG_LEVEL=Info
- LOG_FILE=/data/vaultwarden.log
- EXTENDED_LOGGING=true
- ORG_EVENTS_ENABLED=true
- EVENTS_DAYS_RETAIN=60
- SIGNUPS_ALLOWED=false
- USER_ATTACHMENT_LIMIT=100000
- PASSWORD_ITERATIONS=1000000
- PASSWORD_HINTS_ALLOWED=false
- ORG_GROUPS_ENABLED=true
- ADMIN_TOKEN=$$argon2

### Expected behavior
Items to automatically sync between collection moves.  Not requiring manual sync.
Item adds / deletes, edits of item sync / updating immediately.  Would like collection moves to do same.

Example:
Windows desktop client:  Existing item in collection A.  Move item from collection A to collection B
Firefox extension:  Unlock vault and view collection B.  Item moved is immediately present.

### Actual behavior

Windows desktop client:  Existing item in collection A.  Move item from collection A to collection B
Firefox extension:  Unlock vault and view collection B.  Item not present.  Settings - sync vault now.  Review Collection B.  Item now present.

**Comment by BlackDex** [comment]
I have solved the issue via #3546
