### ISSUE TITLE
Admin login page always responds with a 401

### ISSUE THREAD

**Issue by gabe565** [dani-garcia/vaultwarden#3540]
### Subject of the issue

Ever since https://github.com/dani-garcia/vaultwarden/commit/5a05139efe484b37edbc2db6eb618676d26f3723, the login page consistently returns a 401 status code. I believe this is the intended behavior, but it's causing some login issues for me so I thought I'd see if this warrants changing.

For more context, I protect my admin page behind SSO with [Authentik](https://goauthentik.io) and the nginx [auth request](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html) module. This module sends each request to an SSO auth endpoint before connecting to the upstream server. If the the SSO endpoint returns a 401 response, the user is redirected to the login page. Otherwise, the user is allowed through. It also seems to handle a 401 response from the app by redirecting to the SSO login URL.

When this module is enabled, Vaultwarden's 401 response results in a redirect loop.

During my troubleshooting, I disabled the SSO auth request. Instead of seeing the Vaultwarden login page, I got a response from the [default backend](https://github.com/tarampampam/error-pages) I use since I have it set to replace 401s.

I'm sure I could disable the default 401 backend for Vaultwarden and keep SSO disabled, but all of this troubleshooting made me wonder if there would be a better way to handle this. Would it make more sense for Vaultwarden to return a 200 when the login page is first shown, then return a 401 if the entered code is wrong?

If this behavior shouldn't change, I don't mind closing the issue and finding a workaround.

### Deployment environment

* vaultwarden version: 1.28.1

* Install method: Docker image in Kubernetes

* Clients used:  Web vault, desktop, Android

* Reverse proxy and version:  ingress-nginx v1.7.1

* MySQL/MariaDB or PostgreSQL version: 

* Other relevant details: Running Authentik v2023.5.1

### Steps to reproduce

- Navigate to `/admin`
- Check the response status code

### Expected behaviour

- The initial login page returns a 200 status code
- An invalid token causes the form to be shown again with a 401 status code

### Actual behaviour

- The initial login page returns a 401 status code
- An invalid token causes the form to be shown again with a 401 status code

**Comment by tessus** [comment]
When you use basic auth (e.g. from Apache) and go to `/admin` there is no status code returned until you either cancel the password prompt or submit credentials.

However, by just going to the admin page with the setting `DISABLE_ADMIN_TOKEN=false`, the page should not return 401.

I agree, this looks like a bug, or at least this behavior goes against every standard out there. Otherwise all login prompts on the web would return a 401 upon loading the form, which they don't.

**Comment by gabe565** [comment]
I still have the token enabled just in case I ever mess up my auth request config. Probably overkill, but I'd rather be overly cautious.

And hmm for me it returns a 401 even if I connect directly to Vaultwarden and forego any proxies. Here's an initial pageload to the `/admin` endpoint:

<img width="1068" alt="image" src="https://github.com/dani-garcia/vaultwarden/assets/7717888/a97af0fb-93e2-4ff8-8631-6274201acae0">

**Comment by tessus** [comment]
That's what I was saying. It seems like a bug to me. It shouldn't give you a 401 when going to the admin page directly (without external authnz).

**Comment by gabe565** [comment]
@tessus Ah ok I misread your first message. Thanks for clarifying 👍

**Comment by nillebor** [comment]
You don't use an SSL certificate?
Please establish an encrypted connection!
Vaultwarden requires a certificate to run.

**Comment by tessus** [comment]
@nillebor I think you misunderstood the problem. There is a reverse proxy in front of it with TLS. The example was to show the issue. Also, running vw without TLS for testing purposes is perfectly valid.

**Comment by nillebor** [comment]
vautwarden does not work for me without ssl.
The server started but no login is possible

**Comment by BlackDex** [comment]
@gabe565 @tessus I have created a PR which should resolve this.
