### ISSUE TITLE
Cannot create a folder inside the organization

### ISSUE THREAD

**Issue by Feriman22** [dani-garcia/vaultwarden#3557]
### Subject of the issue
Cannot create a folder inside the organization

### Deployment environment

* vaultwarden version: 2023.3.0
* Install method: Docker image
* Clients used: Chrome
* Reverse proxy and version: -
* MySQL/MariaDB or PostgreSQL version: -
* Other relevant details:

### Steps to reproduce
1., Create a new organization
2., Select it
3., Press the "+" button next to "Folders"
4., Type any name

### Expected behaviour
This should be created within the org, because I'm inside of it

### Actual behaviour
It has been created in my private vault (My vault)

### Screenshots
![image](https://github.com/dani-garcia/vaultwarden/assets/22872515/51228fde-efa7-4794-b433-00c3d8c67a18)
![image](https://github.com/dani-garcia/vaultwarden/assets/22872515/75524551-c6d8-485a-a086-a215b18e95a4)
![image](https://github.com/dani-garcia/vaultwarden/assets/22872515/15b64d1d-e6d9-4adf-8afc-6335e9601a22)

**Comment by BlackDex** [comment]
See: https://github.com/dani-garcia/vaultwarden/discussions/3499
