### ISSUE TITLE
Your Session has been timed out after 3 minutes.

### ISSUE THREAD

**Issue by Wolbaz** [dani-garcia/vaultwarden#3720]
My company email last week has started taking longer to receive outside emails, approximately 3 minutes. By the time my 2FA email comes in, I get a message telling me my session has timed out. Attempting to resend the email gives the same error, I can only have it re-sent by logging in from scratch again. My current work around is to use my personal email, but I have to rely on google phone call 2FA to log into my personal email, which isn't as friendly. For context I can't have my cellphone at work.

### Deployment environment
Docker container on Unraid

* vaultwarden version:1.29.0

* Install method: Docker Container

* Clients used: web vault

* Reverse proxy and version: Traefik 2.6.7

* MySQL/MariaDB or PostgreSQL version: n/a

* Other relevant details:

### Steps to reproduce
Use SMTP 2FA, wait >= 3 minutes, session times out.

### Expected behaviour
Session doesn't time out

### Actual behaviour
Session times out

**Comment by BlackDex** [comment]
This can be configured see https://github.com/dani-garcia/vaultwarden/blob/3dbfc484a54c41d1759646444b439da06445060b/.env.template#L233
