### ISSUE TITLE
Cannot read properties of null (reading 'iterations')

### ISSUE THREAD

**Issue by Hui824** [dani-garcia/vaultwarden#3750]
As mentioned in the question, I encountered this issue when logging in and using self hosting using the Chrome plugin.

docker logs :
[2023-08-04 03:25:25.202][request][INFO] GET /api/devices/knowndevice
[2023-08-04 03:25:25.202][response][INFO] GET /<p..> [10] (web_files) => 404 Not Found
[2023-08-04 03:25:30.937][request][INFO] POST /identity/accounts/prelogin
[2023-08-04 03:25:30.938][response][INFO] 404 Not Found

Version: 
Chrome plugin : 2023.7.0
VW: 
docker tag version:1.29.1
docker exec vaultwarden /vaultwarden --version
vaultwarden 1.23.1

**Comment by Hui824** [comment]
I don't know why I pulled VW version 1.23.1 old version
The issue has been resolved after I upgraded the vw version to 1.27.0.

docker exec vaultwarden /vaultwarden --version
vaultwarden 1.27.0

**Comment by BlackDex** [comment]
@Hui824 the latest version is 1.29.1 currently not 1.27.0

**Comment by Hui824** [comment]
@BlackDex 
Why did I use the command to pull down the image version, which is version 1.23.1
`docker pull vaultwarden/server:latest`

The version I upgraded uses the following command, and the obtained version is 1.27.0
`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR vaultwarden`

Must I use the following command to pull the latest image?
`docker pull vaultwarden/server:1.29.1`

I always use 'latest' to obtain the image

Thank you for your reply

**Comment by BlackDex** [comment]
`docker pull vaultwarden/server:latest` should have pulled `1.29.1` not `1.27.0`.
I use watchtower too, but then for `testing` but that works just great.

It might be that your Docker version is too old? There were some known issues with older docker versions and newer images.
Once updated to the latest version of docker those should be gone.

**Comment by Hui824** [comment]
Okay, thank you for your help

**Comment by qhgary** [comment]
My server side version is 2.25.0 because I pulled with the "latest" label. However, the same issue(same wrong message) occurred when I tried to use bitwarden client side, including browser plugin, android app, etc. 
By the way, it's all right when I pulled the version 1.29.1 which was mentioned above.
