### ISSUE TITLE
Any interest in supporting the new Secrets Manager?

### ISSUE THREAD

**Issue by felddoteth** [dani-garcia/vaultwarden#3793]
Bitwarden announced a Secrets Manager integration. Not begging for code today, just want to know if it has a future in this project as I'm trying to sort out my future Bitwarden deployment strategy. I really don't like their tech stack. Vaultwarden is ❤️

**Comment by tiker** [comment]
I wish Vaultwarden could support it.  https://github.com/dani-garcia/vaultwarden/discussions/3368

**Comment by BlackDex** [comment]
Will not happen unless it's moved out-off the licensed bitwarden directory.
Closing this as not going to happen.
