### ISSUE TITLE
Vaultwarden docker 1.29.2 won't start

### ISSUE THREAD

**Issue by daevidt** [dani-garcia/vaultwarden#3826]
### Subject of the issue
Vaultwarden 1.29.2 (docker) won't start after upgrade (docker image update).

### Deployment environment

* os version: Ubuntu 22.04.3 LTS

* vaultwarden version: 1.29.2 (could not start)

* Install method: docker image (latest)

* Clients used: web vault, Android

* Reverse proxy and version: Apache 2.4.52-1ubuntu4.6

* MySQL/MariaDB or PostgreSQL version: N. A. (sqlite3)

* Other relevant details:

Only accessible from an internal network (restricted in Apache and firewall)
.env file settings:
WEB_VAULT_ENABLED=false
SIGNUPS_ALLOWED=false
DOMAIN=https://...
USE_SENDMAIL=true

### Steps to reproduce
$ docker stop vaultwarden
$ docker rm vaultwarden
$ docker pull vaultwarden/server:latest
$ docker run -d --restart unless-stopped --name vaultwarden -e bwrs.env -v /opt/bitwarden/bwrsdata:/data/ -p 449:80 vaultwarden/server:latest

### Expected behaviour
the docker container should start

### Actual behaviour
the docker container stuck in a restart loop

### Troubleshooting data

$ docker logs vaultwarden

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'OS can't spawn worker thread: Operation not permitted (os error 1)', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/scheduler/multi_thread/worker.rs:447:13

I tried to set RUST_BACKTRACE=1 in bwrs.env, but it made no difference..

**Comment by BlackDex** [comment]
Please provide a `docker info` output, i suspect you are running an older version of Docker which has some issues with newer container images.

**Comment by grantcodes** [comment]
Just confirming I ran into the same issue and reinstalling / upgrading docker [following the official docs](https://docs.docker.com/) seems to have got Vaultwarden up and running for me again.

**Comment by jrkoiter** [comment]
Same issue here. Rolled back to 1.29.1 for now, that works.
