### ISSUE TITLE
Login with device not working for me

### ISSUE THREAD

**Issue by darkman242** [dani-garcia/vaultwarden#3856]
### Deployment environment

* vaultwarden version: 1.29.2-bbd630f1 (actual testing)

* Install method: Docker-Image

* Clients used: web vault, desktop, Android

* Reverse proxy and version: SWAG (docker-image: actual stable)

* MySQL/MariaDB or PostgreSQL version: 

* Other relevant details:

### Steps to reproduce
I log in to WebVault with 2FA (FIDO2 key). After logout and login again, I want to use the 'Log in with device' function. On my Android device I get the notification. I confirm this. On the Web-Vault this confirmation also arrives, because the dialog is confirmed. However, after that the 2FA with WebAuth comes again and I am not logged in.

I have disabled WebSocket on my vaultwarden-compose.yaml and on the reverse proxy.

**Comment by BlackDex** [comment]
Have you selected the remember this device for the 2FA?

**Comment by darkman242** [comment]
Sorry, of course not. now it works. thanks
