### ISSUE TITLE
New Header in Admin Panel Blocking Login Form

### ISSUE THREAD

**Issue by Tyree** [dani-garcia/vaultwarden#3900]
### Subject of the issue
There's a new Vaultwarden header on the admin login page that covers the login form.

### Deployment environment
unRAID Docker

* vaultwarden version:
2023.7.1

* Install method:
unRAID Docker

* Clients used: 
Web

### Steps to reproduce
Open the admin login page

### Expected behaviour
Login form visible

### Actual behaviour
Login form covered
![blocked](https://github.com/dani-garcia/vaultwarden/assets/5395363/8b372606-6443-4c49-9e13-56d15ea91f26)

**Comment by stefan0xC** [comment]
What  browser are you using? In Firefox 117.0.1 it works as expected.

**Comment by Tyree** [comment]
Using Chrome. I just checked with Firefox and Brave and it looks the same. For such a simple page, I wouldn't think there were any crazy, cutting-edge CSS at play.
Looking at the code, the Navbar is fixed-top and I'm assuming that makes it position: absolute....but I don't see margins or anything on the login form to push it down and out from under the navbar.
But if it looks right for you, I don't know.

**Comment by stefan0xC** [comment]
On my system body has a  `padding-top: 75px;` (from `admin.css`).

Do you have maybe overwritten the admin templates? Does anything fail to load?

**Comment by Tyree** [comment]
I just forced an update check on the container. Says it's up to date.

**Comment by Tyree** [comment]
I added the padding-top: 75px to the body, but it still cuts off the top. Is this what yours looks like?
![paddingtop](https://github.com/dani-garcia/vaultwarden/assets/5395363/3e9ea3b3-dffb-430d-8264-83a94a171ade)

**Comment by stefan0xC** [comment]
No. The `.vaultwarden-icon` is also much too large. I think your browser is not loading the `/vw_static/admin.css`. Can you open the file directly?

**Comment by Tyree** [comment]
Do I need to open that from within the container console? Or are you saying within the browser? Is it just http://domain/vw_static/admin.css ?

**Comment by stefan0xC** [comment]
Unless you are using a sub-folder (then it should be `https://domain/path/vw_static/admin.css`).

**Comment by Tyree** [comment]
Okay. Yeah, I opened it in the browser and I do see the padding-top on the body.
I see the problem. I just set up authelia and I have vaultwarden excluded, but not that path. I see the errors in the browser console. 
My bad. Sorry for wasting your time! And thanks for the help!

**Comment by stefan0xC** [comment]
No worries. I'm glad I could help.
(This issue can be closed)
