### ISSUE TITLE
Error "N is Null

### ISSUE THREAD

**Issue by CFox243** [dani-garcia/vaultwarden#3983]
### Subject of the issue
in browser extension when i try to sign in i get an error "n is null".
not sure why just updated to the latest build. not sure if any other users are experiencing this.
when i ran into this error i updated to the testing branch to test if it was a version issue but happens there also.

* vaultwarden version: v1.29.2-008a2cf2

* Install method: Docker

* Clients used: 
i can sign in everywhere except browser extensions. i tried firefox and chrome.
* Reverse proxy and version: 
nginx:latest
* MySQL/MariaDB or PostgreSQL version: 
mysql/mariadb
* Other relevant details:
![AhpRtaXlT4](https://github.com/dani-garcia/vaultwarden/assets/128409855/fd1e1043-b3b7-4bbe-a82a-0a6183701510)

**Comment by BlackDex** [comment]
are there any Vaultwarden logs which may indicate an issue?
What happens in other browsers, or when using a clean browser profile?

**Comment by CFox243** [comment]
> are there any Vaultwarden logs which may indicate an issue? What happens in other browsers or when using a clean browser profile?

The problem has been resolved.
the issue was different by browser:

- chrome I just had to clear cookies and it solved it.

- Firefox had to clear site data and then go to extension settings and change from self-hosted to bitwarden and back. then re-add the custom url and then it could sign in just fine.

Thanks
