### ISSUE TITLE
Error running migrations Docker won't start

### ISSUE THREAD

**Issue by SAS-1** [dani-garcia/vaultwarden#3993]
### Subject of the issue
On pulling the latest testing image I can't get it to start it shows the following in the logs

[23-10-2023 09:19:26.270][panic][ERROR] thread 'main' panicked at 'Error running migrations: QueryError(DieselMigrationName { name: "2023-10-21-221242_add_cipher_key", version: MigrationVersion("20231021221242") }, DatabaseError(Unknown, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '\"key\" TEXT' at line 2"))': src/db/mod.rs:471

   0: vaultwarden::init_logging::{{closure}}

   1: std::panicking::rust_panic_with_hook

   2: std::panicking::begin_panic_handler::{{closure}}

   3: std::sys_common::backtrace::__rust_end_short_backtrace

   4: rust_begin_unwind

   5: core::panicking::panic_fmt

   6: core::result::unwrap_failed

   7: vaultwarden::db::mysql_migrations::run_migrations

   8: vaultwarden::db::DbPool::from_config

   9: vaultwarden::main::{{closure}}

  10: rocket::async_main

  11: vaultwarden::main

  12: std::sys_common::backtrace::__rust_begin_short_backtrace

  13: std::rt::lang_start::{{closure}}

  14: std::rt::lang_start_internal

  15: main

  16: <unknown>

  17: __libc_start_main

  18: _start

### Deployment environment

Synology DS918+     =========================================================================================
    Preferably, use the `Generate Support String` button on the admin page's Diagnostics tab.
    That will auto-generate most of the info requested in this section.
    =========================================================================================
-->

* vaultwarden version: Testing build as of 1027 on 23rd October 2023. Unable to start to get version.

* Install method: Docker on Synology NAS

* MySQL/MariaDB or PostgreSQL version: MariaDB latest

* Other relevant details:

### Steps to reproduce

Pulled latest testing image and issue happens. 

### Expected behaviour

Docker container starts up
### Troubleshooting data

Logs are above

**Comment by BlackDex** [comment]
Thanks for the report.

It is fixed now and a new release will be there in about an hour or so.
