### ISSUE TITLE
Issue importing JSON to vaultwarden web

### ISSUE THREAD

**Issue by obnoxiousish** [dani-garcia/vaultwarden#4005]
Imported .JSON file that was exported from my bitwarden for windows into vaultwarden web, 

Expected Result: a successful import

WHAT ACTUALLY HAPPENS ERROR: e.match was null (or == null idr)

Must be a bug as I exported .csv from bitwarden for windows then imported and it worked fine.

Thanks <3(i just cloned the repos now so must be newest version)

**Comment by BlackDex** [comment]
There is nothing done on the server side in regards of reading any import file from any type.
The conversion is done by the client which then reads, converts and encrypts the imported data and then sends that to the server.

So, if you think this is a server side issue, there must be something in the error logs of Vaultwarden, but i think this is probably a web-vault issue which is not something we develop.

**Comment by obnoxiousish** [comment]
> There is nothing done on the server side in regards of reading any import file from any type. The conversion is done by the client which then reads, converts and encrypts the imported data and then sends that to the server.
> 
> So, if you think this is a server side issue, there must be something in the error logs of Vaultwarden, but i think this is probably a web-vault issue which is not something we develop.

I suppose I thought it would be related to the patchs applied to web-vault, as it seemed unlikely the official one has broken JSON importing, I suppose Ill open a ticket in web-vault's git and vaultwarden web vault patched repo

**Comment by BlackDex** [comment]
Ok, but what do the logs say of Vaultwarden, there probably must have been an error there for this to cause such a message if it is coming from Vaultwarden.

**Comment by dfunkt** [comment]
This is what I get when I try to import my encrypted json to an organization vault:
`vaultwarden  | [2023-10-27 12:19:37.398][vaultwarden::api::core::ciphers][ERROR] The client copy of this cipher is out of date. Resync the client and try again.`
Dozens ,if not hundreds, of messages like this ^^

**Comment by BlackDex** [comment]
Thx! We might be able to track down what the issue is now.

**Comment by dfunkt** [comment]
Still having this issue when using the latest testing build (Version 1.29.2-93da5091, testing-alpine)

**Comment by BlackDex** [comment]
That's because it isn't fixed yet. Only the new web-vault and passkeys are changed after your last try.

**Comment by dfunkt** [comment]
Yeah, I only mentioned it because I tought that maybe the new web-vault would fix the issue.

**Comment by BlackDex** [comment]
That could have been the case, but I think it's more a server side item. I already checked it, have to work on a fix.
