### ISSUE TITLE
Access with device doesn't work if vaultwarden is restarted

### ISSUE THREAD

**Issue by LiskoFINAL** [dani-garcia/vaultwarden#4015]
### Subject of the issue
On my Android device I have enabled pin and biometric unlock to login and enabled Access requests. It works but if vaultwarden is restarted I still get the notifications but it errors out when trying to accept or dismiss the auth requests. To make it working again I have to fully logout and login using password.

### Deployment environment

unraid 6.12.4

* vaultwarden version: 1.29.2

* Install method: Docker

* Clients used: web vault and Android
* Reverse proxy and version: no

* MySQL/MariaDB or PostgreSQL version: no

### Steps to reproduce
Log in the android app
Enable pin and biometric login even after the restart of the app
Enable Accesses Requests
Restart vaultwarden docker
Try to log in the webvault using device
Open the notification on the Android device and try to accept or dismiss the access request

### Expected behaviour
Being able to accept or dismiss the auth request

### Actual behaviour
When trying to accept or decline the auth request it errors out and nothing happens

**Comment by BlackDex** [comment]
This is normal behavior. You disconnect/break the websocket connection.
That is not something we can fix.

**Comment by LiskoFINAL** [comment]
Thank you. What confused me is that if I log out from Android and try to re log in using pin or biometric, it still doesn't remake the websocket connection. I have to login using the full password, but obviously you are out of control of client's behavior. Amazing work guys keep up and thanks.

**Comment by BlackDex** [comment]
There is a bug in the system current stable version which is fixed in testing tagged images which should probably solve your issue.
