### ISSUE TITLE
Docker hub the tag alpine not upgrade

### ISSUE THREAD

**Issue by xqdoo00o** [dani-garcia/vaultwarden#4035]
Just check the docker hub [page](https://hub.docker.com/r/vaultwarden/server/tags?page=1), still 2 months ago
![image](https://github.com/dani-garcia/vaultwarden/assets/12299238/bdd4ba41-e8a4-42ea-a04a-e30a209ee75d)
Is the `alpine` tag not using anymore? mirgated to `latest-alpine` tag? If so, I think you guys may should mention it in release note.

**Comment by BlackDex** [comment]
Indeed, thanks for the report!

**Comment by BlackDex** [comment]
You can btw use `latest-alpine` that one is updated.

**Comment by xqdoo00o** [comment]
but alpine tag still not upgrade, must we waiting for the next release?

**Comment by BlackDex** [comment]
We either need to do that manually, or you have to wait for a new release indeed.
But you might also use `latest-alpine` which makes a bit more clear you are using latest, but then the alpine version.

That one is up-to-date.

**Comment by mrmeowski** [comment]
@BlackDex, would you consider the `alpine` tag deprecated? If so, should we update https://github.com/dani-garcia/vaultwarden/wiki/Which-container-image-to-use to replace `alpine` with `latest-alpine`?

**Comment by BlackDex** [comment]
Thanks, i have update that page.
