### ISSUE TITLE
2023.10.0 shows wrong version info

### ISSUE THREAD

**Issue by logopk** [dani-garcia/vaultwarden#4040]
▶ curl https://vault.example.com/api/config
{"environment":{"api":"https://vault.example.com/api","identity":"https://vault.example.com/identity","notifications":"https://vault.example.com/notifications","sso":"","vault":"https://vault.example.com"},"featureStates":{"autofill-v2":true,"fido2-vault-credentials":true},"gitHash":"cec1e876","object":"config","server":{"name":"Vaultwarden","url":"https://github.com/dani-garcia/vaultwarden"},"version":"2023.9.1"}%                                                                  

so the Browser Extension also shows 2023.9.1

https://github.com/dani-garcia/vaultwarden/blob/cec1e87679cfd0e2f0bce9b7dc3256dbbd2effa8/src/api/core/mod.rs#L202

:-)

Best regards

Peter

**Comment by BlackDex** [comment]
See https://github.com/dani-garcia/vaultwarden/discussions/4034#discussioncomment-7486628
