### ISSUE TITLE
Vaultwarden 1.30.0 not starting on linux/arm

### ISSUE THREAD

**Issue by har64** [dani-garcia/vaultwarden#4055]
### Subject of the issue

vaultwarden not starting on armv6
### Deployment environment

* vaultwarden version: 1.30.0

* Install method: docker

### Troubleshooting data

/bin/sh: error while loading shared libraries: libc.so.6: ELF load command address/offset not page-aligned

**Comment by BlackDex** [comment]
Are you sure you are using the latest version?
Did you do a `docker pull vaultwarden/server:latest` and removed the previous container, and started a new one?

**Comment by har64** [comment]
Downloaded Image with portainer, renamed old Container and started a new one.

**Comment by BlackDex** [comment]
On what platform/host/device are you running this?

**Comment by BlackDex** [comment]
Also, what about `latest-alpine`?

**Comment by BlackDex** [comment]
And, which docker version are you running? It should be at least v20.10 if i'm correct. Any version lower is not supported.

**Comment by har64** [comment]
> On what platform/host/device are you running this?

WD MyCloudEx2Ultra/debian

> Also, what about `latest-alpine`?

running (V1.29.2)

> And, which docker version are you running? It should be at least v20.10 if i'm correct. Any version lower is not supported.

docker v20.10

**Comment by BlackDex** [comment]
Are you running `latest-alpine`? Have you tried that image?

**Comment by har64** [comment]
latest-alpine always restarts (no network, no log)

**Comment by BlackDex** [comment]
Sound like something else then, since one of the two should at least work i think.
A bit more logs on what is happening would be nice. Docker should also be able to provide a bit more information.
Else, we can't do much with the information we currently have.

**Comment by Natherul** [comment]
maybe not the same issue, not sure but I got this today when trying to update my warden instance.

In my case Im running portainer and the error I get from it is
`'failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/bin/entry.sh": stat /usr/bin/entry.sh: no such file or directory: unknown'`

**Comment by BlackDex** [comment]
This is probably a remnant of previous versions. Portainer seems to keep entrypoints defined in an image long long time ago, while this isn't there in the new images, since we do not use the balenalib images anymore.

Check your config and remove the entrypoint and let the image handle it instead of portainer. That will solve your issue.

**Comment by Natherul** [comment]
> This is probably a remnant of previous versions. Portainer seems to keep entrypoints defined in an image long long time ago, while this isn't there in the new images, since we do not use the balenalib images anymore.
> 
> Check your config and remove the entrypoint and let the image handle it instead of portainer. That will solve your issue.

That solved my issue. I was not aware of this behavior in portainer and indeed in the options for it it had saved old values and set them to override default with it. Thanks

**Comment by BlackDex** [comment]
Closing as stale.
If you still think this is a Vaultwarden issue please provide more information and re-open.

**Comment by har64** [comment]
I found the problem.
alpine above 3.17 can't run on my system.
I copied vaultwarden 1.30.1 in a container with alpine 3.17.5 and that works

**Comment by BlackDex** [comment]
You say 3.17 doesn't work, but 3.17.5 does? That seems illogical

**Comment by har64** [comment]
I say beginning with 3.18 alpine isn't running

**Comment by BlackDex** [comment]
Strange, since what it starts is just a basic Alpine image of which almost nothing is used, except curl and sh.

You can't even run a slice
Alpine image by it self?

**Comment by har64** [comment]
Yes, i've e.g. downloaded alpine:latest, which is not running

**Comment by Actuario** [comment]
> This is probably a remnant of previous versions. Portainer seems to keep entrypoints defined in an image long long time ago, while this isn't there in the new images, since we do not use the balenalib images anymore.
> 
> Check your config and remove the entrypoint and let the image handle it instead of portainer. That will solve your issue.

I removed the entrypoint, leaving the field blank and selecting override, but the error persists

Do I have to do something else to delete the entrypoint?

thank you!
