### ISSUE TITLE
[WARN] tls handshake with 127.0.0.1:XXXXX failed: received corrupt message of type InvalidContentType

### ISSUE THREAD

**Issue by rwjack** [dani-garcia/vaultwarden#4112]
### Subject of the issue

Container shows as unhealthy on portainer, even though everything is working. Unsure why I'm getting these WARN logs, the curl healthcheck works within the container.

```
[2023-11-28 13:04:14.301][rocket_http::tls::listener][WARN] tls handshake with 127.0.0.1:39154 failed: received corrupt message of type InvalidContentType
[2023-11-28 13:05:14.348][rocket_http::tls::listener][WARN] tls handshake with 127.0.0.1:51004 failed: received corrupt message of type InvalidContentType
[2023-11-28 13:05:30.237][rocket_http::tls::listener][WARN] tls handshake with 127.0.0.1:34490 failed: cannot decrypt peer's message
[2023-11-28 13:06:14.389][rocket_http::tls::listener][WARN] tls handshake with 127.0.0.1:43980 failed: received corrupt message of type InvalidContentType
[2023-11-28 13:07:14.432][rocket_http::tls::listener][WARN] tls handshake with 127.0.0.1:51626 failed: received corrupt message of type InvalidContentType
```

### Deployment environment

* vaultwarden version:
1.30.1

* Install method:
Docker

* Clients used: 
Irellevant

* Reverse proxy and version: 
Irellevant

* Other relevant details:
```
version: "3"

volumes:
  data:

services:
  bitwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped

    container_name: bitwarden
    hostname: bitwarden

    environment:
      - TZ=[redacted]

    ports:
      - "[redacted]:80"
      #- "[redacted]:3012" WSS disabled due to bw extension data leakage via GET request

    volumes:
      - data:/data/
      - ./certs/:/etc/ssl/custom/
      - ./.env:/.env:ro
 ```

Relevant .env changes:
```
DOMAIN=https://[redacted]

## Rocket specific settings
## See https://rocket.rs/v0.4/guide/configuration/ for more details.
# ROCKET_ADDRESS=0.0.0.0
# ROCKET_PORT=80  # Defaults to 80 in the Docker images, or 8000 otherwise.
# ROCKET_WORKERS=10
ROCKET_TLS={certs="/etc/ssl/custom/[redacted].pem",key="/etc/ssl/custom/[redacted]-key.pem"}
```

### Expected behaviour
Container to show as healthy

### Actual behaviour

Container shows as unhealthy, even though everything is working.

### Troubleshooting data

```
root@bitwarden:/# curl --insecure --fail --silent --show-error https://localhost:80/alive || exit 1
"2023-11-28T12:06:47.277011Z"root@bitwarden:/# echo $?
0
```

**Comment by rwjack** [comment]
> Try setting the LOG_LEVEL to debug and see if you get some more information.

Let me give it a shot.

---

> It could be your host platform which causes some (Open)SSL client settings to be different host-wide, and causes this to happen.

Debian 11 with the latest version of Docker, I doubt that's the issue.

---

> The certs might be unsupported in some way, or not have a full chain available?

I don't think they do have a full chain, it's just a regular certificate generated by [mkcert](https://github.com/FiloSottile/mkcert/)

---

> Also, i see you use port 80, while it looks like you do a port-proxy via Docker. Not sure if you use a reverse proxy in-front of Vaultwarden, if so, it could also be your reverse proxy which is causes an issue.

Port 80 is the default for the container. I expose another port on the Debian host, which is open only to the reverse proxy, but I don't see how that's related, as the healthcheck should curl "localhost", since `ROCKET_ADDRESS` (by default I hope) is configured to `0.0.0.0`.

```
addr="${ROCKET_ADDRESS}"
if [ -z "${addr}" ] || [ "${addr}" = '0.0.0.0' ] || [ "${addr}" = '::' ]; then
    addr='localhost'
fi
```

**Comment by rwjack** [comment]
@BlackDex Though I didn't just try to run the healthcheck manually.

This is the error:
```
root@bitwarden:/# ./healthcheck.sh
curl: (1) Received HTTP/0.9 when not allowed
```

And the timestamp matches a corresponding error in the container logs:
```
[2023-12-01 12:41:08.865][rocket_http::tls::listener][WARN] tls handshake with 127.0.0.1:34488 failed: received corrupt message of type InvalidContentType
```

**Comment by rwjack** [comment]
Gotcha, thanks for the help!

Even though my issue is resolved, do you still want to keep this open as a reminder?

**Comment by BlackDex** [comment]
Yes please, this is something we need to fix i think.
