### ISSUE TITLE
Inconsistent User State Prevents Removal/Reset

### ISSUE THREAD

**Issue by sempervictus** [dani-garcia/vaultwarden#4128]
### Deployment environment

* vaultwarden version: 1.30.1

* Install method: Arch OS package

* Clients used: 

* Reverse proxy and version: 

* MySQL/MariaDB or PostgreSQL version: 

* Other relevant details:
I have a user who's master password is not working and needs to be deleted. Attempting to delete them shows they are the owner of an org to which they do not actually have any access (i am also the owner of that org), verified in the main webui; this false ownership status prevents the user from being deleted so their account can be reset (if it even needs to be given the apparent corruption).

**Comment by BlackDex** [comment]
If there are multiple owners of an org, then you should be able to delete that person just fine. It just needs 1 single owner to exists.

Have you checked the `/admin` interface if that user didn't created an organization it self?

**Comment by sempervictus** [comment]
The user is not even a member of the org, much less an owner.

**Comment by BlackDex** [comment]
Of which org? That still doesn't answer the question if you have checked the `/admin/` interface by going to the `/admin/users/overview` endpoint, so `https://my.domain.tld/admin/users/overview`.

**Comment by sempervictus** [comment]
Sorry, to clarify:
1. In the "normal" web UI, the user is a member of org A and not at all part of org B.
2. In the admin web UI, the user is a member or org A and an admin of org B (other admins exist) <-- data corruption/logic error indicator 1
3. In the admin web UI, attempting to the delete the user which seems to have some level of ownership results in an error stating they are the last admin or org B (when they are not even a member). <-- data corruption/logic error indicator 2
4. In the database, they appear in the `users_organizations` table for org b as:
```sql
uuid                                  user_uuid                             org_uuid                              access_all  akey                                                          status  atype  reset_password_key  external_id
------------------------------------  ------------------------------------  ------------------------------------  ----------  ------------------------------------------------------------  ------  -----  ------------------  -----------
42e4d005-2fd6-48ba-921b-c71cde0b7091  763ad395-42cd-4e7e-8173-bd1bfc4a8b44  6cc922d9-7303-40a3-ae34-daafaf2f6e9f  1           4.bCNCOnH7yTSgFR6h97eM3eFDoGX08nk7Vm+EvBroL9hYSqtXx7sIEFtjE1  2       0 
```

**Comment by BlackDex** [comment]
That shows that the user `763ad395-42cd-4e7e-8173-bd1bfc4a8b44` has owner access to organization `6cc922d9-7303-40a3-ae34-daafaf2f6e9f`. So that seems to validate the claim during the deletion process.

If you filter the database for only that `org_uuid`, are there any other users in there?

**Comment by sempervictus** [comment]
Interestingly **no** my membership (listed as owner in the non-admin UI) is not showing up even though i created the org and this other user has _never_ had access to it. DB confuse the `user_uuid`s somehow?

**Comment by BlackDex** [comment]
So, then, what does the `/admin` interface show you for that user?
Do the org uuid's match for the orgs which you think that user is part of?
If you lookup that org_uuid in the organizations table, does that match?

**Comment by sempervictus** [comment]
the `/admin` view shows the user as a `member` of `org A` and an `owner` in `org B`.
The user is **not** a `member` or `owner` or `org B` and was never granted rights to it, there was no invite email sent (MTA is internal, we have all the logs) granting them any role in `org B`. Whats stranger is that **i am** the owner of `org B` in both UIs but i cannot remove that user because the removal check for "last owner" fails seemingly due to the weird way in which that user is related to the org. How do i re-create my ownership relationship in the database (i think his somehow replaced mine)? There seem to be cryptographic ties in there which do not suffer the user_uuid being changed.

**Comment by BlackDex** [comment]
uuid's do not flip somehow. So either the database is corrupted. Or someone did some manual database changes which caused this strange behavior. But if what you say what you see in the database is the source of truth, then you shouldn't be able to login into your account have access to that org.

The problem here is, i do not have to full picture.
I would need at least a dump of the users, organizations and users_organizations tables (emails and names excluded of course) to make s better guess.

**Comment by sempervictus** [comment]
I think it was some sort of corruption - i deleted the org in question, which allowed me to remove the user. Might be postgres time :)

**Comment by BlackDex** [comment]
Btw, in glad it's solved
