### ISSUE TITLE
Cannot login to Desktop and Mobile clients

### ISSUE THREAD

**Issue by wendellli99** [dani-garcia/vaultwarden#4193]
### Cannot log in to Desktop and Mobile clients
Desktop and mobile clients stopped being allowed to connect to the server. Users cannot sign in or modify content. This likely happened after an Bitwarden app update. The web client and Chrome extension work fine.

### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.30.1
* Web-vault version: v2023.10.0
* OS/Arch: linux/x86_64
* Running within Docker: true (Base: Debian)
* Environment settings overridden: false
* Uses a reverse proxy: true
* IP Header check: false (X-Forwarded-For)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.44.0
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** 

```json
{
  "_duo_akey": null,
  "_enable_duo": false,
  "_enable_email_2fa": true,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_smtp_img_src": "cid:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "auth_request_purge_schedule": "30 * * * * *",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "***************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://***********************",
  "domain_origin": "*****://***********************",
  "domain_path": "",
  "domain_set": true,
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "email_attempts_limit": 3,
  "email_change_allowed": true,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": "***",
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "NetPrism",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "Info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 100000,
  "push_enabled": false,
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.com",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": true,
  "signups_domains_whitelist": "************",
  "signups_verify": true,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "***********************",
  "smtp_from_name": "NetPrism Bitwarden",
  "smtp_host": "*****************",
  "smtp_password": "***",
  "smtp_port": 587,
  "smtp_security": "starttls",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": "******",
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "websocket_address": "0.0.0.0",
  "websocket_enabled": false,
  "websocket_port": 3012,
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>

### Steps to reproduce
Install the latest Bitwarden desktop or mobile apps and sign in to a self-hosted Vaultwarden server.

### Expected behaviour
Users can use the app as usual.

### Actual behaviour
Users cannot sign in or make changes to passwords.

### Troubleshooting data
This is the error seen when signing in on desktop and mobile apps.
<img width="367" alt="Screenshot 2023-12-20 at 17 07 53" src="https://github.com/dani-garcia/vaultwarden/assets/34215792/620cb0f2-fa2b-4541-a24d-4963b17229e7">

**Comment by BlackDex** [comment]
Fully logout and back in again to solve this.

**Comment by wendellli99** [comment]
@BlackDex I tried reinstalling the app, both on mac and iOS. It did not help.

**Comment by BlackDex** [comment]
What do the say during these attempts?
Also check your reverse proxy logs

**Comment by oliboehm** [comment]
Same issue with Desktop Client:
Version 2023.12.0
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64

Vaultwarden Version:  2023.3.0

**Comment by BlackDex** [comment]
> Same issue with Desktop Client: Version 2023.12.0 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture x64
> 
> Vaultwarden Version: 2023.3.0

You are running an outdated Vaultwarden.

**Comment by oliboehm** [comment]
> > Same issue with Desktop Client: Version 2023.12.0 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture x64
> > Vaultwarden Version: 2023.3.0
> 
> You are running an outdated Vaultwarden.

Good point. Just updated Vaultwarden to Version 2023.10.0 and Desktop Client to Version 2023.23.1.
Firefox Client, which also had the issues, works now. But Desktop Client still does not synchronize.

**Comment by BlackDex** [comment]
> > > Same issue with Desktop Client: Version 2023.12.0 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture x64
> > > Vaultwarden Version: 2023.3.0
> > 
> > 
> > You are running an outdated Vaultwarden.
> 
> Good point. Just updated Vaultwarden to Version 2023.10.0 and Desktop Client to Version 2023.23.1. Firefox Client, which also had the issues, works now. But Desktop Client still does not synchronize.

Fully logout and back in again, not locking, but logout.

**Comment by BlackDex** [comment]
> @BlackDex I tried reinstalling the app, both on mac and iOS. It did not help.

Thinking about that, it maybe doesn't clear the cache fully.
Might be that still something is in the cache of the application that causes an issue.

**Comment by oliboehm** [comment]
> > > > Same issue with Desktop Client: Version 2023.12.0 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture x64
> > > > Vaultwarden Version: 2023.3.0
> > > 
> > > 
> > > You are running an outdated Vaultwarden.
> > 
> > 
> > Good point. Just updated Vaultwarden to Version 2023.10.0 and Desktop Client to Version 2023.23.1. Firefox Client, which also had the issues, works now. But Desktop Client still does not synchronize.
> 
> Fully logout and back in again, not locking, but logout.

I've done that. But still no sync. Do you know if there is any client log I can check?
Also checked the Bitwarden Android App on my tablet and mobile. Both work.

**Comment by BlackDex** [comment]
There is a developer console option in the desktop app. The same as in Chromium. That shows all the connections and JavaScript items.

Also, are you sure you selected the self-host option?

**Comment by BlackDex** [comment]
> What desktop app are you using? If you are not using the Windows 10+ app, then it won't work [since only the Windows-flavored desktop app works](https://bitwarden.com/help/setup-two-step-login-fido/).

The desktop apps work just fine. Just some features are platform dependant.

So, you can't only have Webauthn/Fido2 as MFA. All other items work just fine.

**Comment by oliboehm** [comment]
It seems that logout is not the same as shutdown. 
I restarted the Bitwarden desktop app and also Windows 11 with, but the client didn't sync. After that, I actively logged out my account and logged in again. Now it works. Thanks for your support and sorry that I hijacked the thread.

**Comment by DennyDai** [comment]
Had same issue after upgrading. Logged out (Chrome on Win11) then re-login, now it works for me.

**Comment by wendellli99** [comment]
> There is a developer console option in the desktop app. The same as in Chromium. That shows all the connections and JavaScript items.
> 
> Also, are you sure you selected the self-host option?

@BlackDex Could you point out where that option is? I could not find it anywhere. I'm using the macOS client from the App Store.

**Comment by BlackDex** [comment]
@wendellli99 You should be able to press `F12` or go via `View` > `Toggle developer tools`.

**Comment by wendellli99** [comment]
@BlackDex Thank you! Here are the errors I see. The server never outputted any logs during these failed attempts.
<img width="568" alt="Screenshot 2023-12-22 at 15 04 31" src="https://github.com/dani-garcia/vaultwarden/assets/34215792/f7e9c6fd-3913-4460-96d3-86bce78cee49">
[-1703286282535.log](https://github.com/dani-garcia/vaultwarden/files/13757237/-1703286282535.log)

**Comment by BlackDex** [comment]
What are the Vaultwarden logs? The one you posted are client logs.

**Comment by wendellli99** [comment]
> What are the Vaultwarden logs? The one you posted are client logs.
The Vaultwarden server never outputted any logs during these failed attempts.

**Comment by wendellli99** [comment]
If it is helpful, I just discovered that the Bitwarden client shows this error when I try to set the custom server URL. I've been using the same URL and it works for the Chrome extension so I don't think the URL is wrong.
<img width="409" alt="Screenshot 2023-12-22 at 15 39 45" src="https://github.com/dani-garcia/vaultwarden/assets/34215792/1f94cea2-a932-4069-ad48-05848bb97318">

**Comment by BlackDex** [comment]
> > What are the Vaultwarden logs? The one you posted are client logs.
> 
> The Vaultwarden server never outputted any logs during these failed attempts.

If it didn't outputted anything the request probably didn't got received by Vaultwarden. It might be the reverse proxy which doesn't forward the request or does something else.

**Comment by wendellli99** [comment]
Problem solved! If you are using Cloudflare ZT Access, make sure to set "HTTP Only" from "Cookie settings" to false. I guess the Bitwarden app recently made a change that requires this setting.
