### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by 4erf** [dani-garcia/vaultwarden#4293]
### Subject of the issue

Vaultwarden server is quite slow. Saving when using Chrome extension can take up to 10 seconds. Website takes long to load and when it loads it only displays the following:

![image](https://github.com/dani-garcia/vaultwarden/assets/43388082/a84de997-976f-4b77-b27d-0e2157703192)

### Deployment environment

* vaultwarden version: vaultwarden 1.30.1

* Install method: Docker image

* Clients used: web vault, Chrome extension, Android.

* Reverse proxy and version: nginx/1.21.6 

* MySQL/MariaDB or PostgreSQL version: SQLite

* Other relevant details: Served with Cloudflare on custom subdomain. System is quite capable, Ryzen 9, plenty of RAM.

### Steps to reproduce

Nothing different from default, just docker image with exposed port 80 and mounted volume on `/data`.

### Expected behaviour

It should be more responsive. 

### Actual behaviour

It started to be slow and unresponsive suddenly, I didn't update the docker image or change anything, it just suddenly started to become slow. Then I did an update of the docker image, still same issue. Finally, I backed up the db as json, deleted all data, started a fresh vault and imported my data back in, the issue persists.

I believe the issue lays in my data, I must've added some entry in the database that is causing this slowdown, as it started to happen without any change other than new entries to the db. Also, when I started a fresh vault it was fast, until I did the import.

My data is not big, the json was only ~150kb, I have around 170 entries, no attachments or anything fancy, I just use basic fields, custom fields and notes.

Sadly I don't remember exactly when it started to slow down, so I have no clue of which entry I added that caused this, I can do some troubleshooting (deleting recent entries until it works) if it's needed.

### Troubleshooting data

I believe only troubleshooting data I can provide is a redacted version of my json that still fails. But it would require some time to build, let me know if it's a must to provide it. Or if you guys have a script that can automatically redact everything, would be great.

**Comment by BlackDex** [comment]
Looks more like a reverse proxy issue.
Any logs of Vaultwarden which state anything?

This is not enough info to do anything.

**Comment by 4erf** [comment]
Hi, @BlackDex, thanks for the insight, I think you found the source of the issue,

In terms of logs there was nothing useful, only icon fetching logs.

However, regarding reverse proxy, I restarted nginx and the problem just went away... But, I know is only a matter of hours/days until it starts failing again, the same happened when I did the fresh install, worked for around a day but then stopped working, I believed it was my data the issue, but turns out it was this.

It's interesting because no other service under my nginx is failing like this. Do you know how can I debug this further? 

I will wait until it fails again and report any information that you recommend me to take.

**Comment by 4erf** [comment]
Well, it didn't really take long, it's already slow again. If you have any debug ideas let me know.

**Comment by BlackDex** [comment]
Check your nginx logs.
Validate the config against the wiki proxy examples.

**Comment by Hammerhand17** [comment]
> I found root cause.
> 
> I noticed that whenever the page took long to load nginx logs wouldn't show any incoming request. Turns out the issue is between Cloudflare and my network and the white page with vaultwarden logo was just Cloudflare caching.
> 
> I will begin debugging my side, this is not a vaultwarden's issue, sorry for any inconvenience.
> 
> Thanks @BlackDex for such quick help, highly appreciate it!

Did you finally get to solve the issue? I`'m suffering the same and don't know how to solve it.

**Comment by sirterric** [comment]
I was having the same issue, and after changing the KDF algorithm to Argon2id (I was using PBKDF2-SHA-256), everything works faster again. I will do some test but right now is working fine.
My vaultwarden is on docker under linux, and I'm using Cloudflare Tunnels.

**Comment by Joly0** [comment]
He,y dont want piggy back this issue, but is it possible to set the algorithm to Argon2id for all new users (or existing ones even)?

**Comment by stefan0xC** [comment]
> He,y dont want piggy back this issue, but is it possible to set the algorithm to Argon2id for all new users (or existing ones even)?

Why do you do it then? When there has been a recent discussion about this #6984 and also a relevant PR still open #6983

**Comment by Joly0** [comment]
> > He,y dont want piggy back this issue, but is it possible to set the algorithm to Argon2id for all new users (or existing ones even)?
> 
> Why do you do it then? When there has been a recent discussion about this [#6984](https://github.com/dani-garcia/vaultwarden/discussions/6984) and also a relevant PR still open [#6983](https://github.com/dani-garcia/vaultwarden/pull/6983)

Couldnt find either the discussion nor the PR when i searched for them, but may be because i searched for things like "algorithm" and not "kdf"

**Comment by stefan0xC** [comment]
You could have also searched for `argon2id` or open a new discussion instead of necrobumping a closed issue.
