### ISSUE TITLE
(feat) enable by default email second factor authentication

### ISSUE THREAD

**Issue by thefiredragon** [dani-garcia/vaultwarden#4303]
Hey there!
I have a little feature request,
Under organisations it's possible to enable 2fa policies,
but general could it possible to enable email 2fa by default globally?
best Regards

**Comment by BlackDex** [comment]
Not really at the moment.
I know that we miss a feature for Orgs that when 2fa is enforced users are automatically added to the email 2fa.
But that is not something we have yet.
