### ISSUE TITLE
Last version Chrome broken: Cannot read proprietys of null

### ISSUE THREAD

**Issue by pomporov** [dani-garcia/vaultwarden#4346]
Hello

since this morning (i think after chrome auto-upgrade) . 

<img width="482" alt="Capture d’écran 2024-02-14 à 10 06 48" src="https://github.com/dani-garcia/vaultwarden/assets/19282056/a272abe4-32f8-4bb3-9955-5c8c8eb6d784">

Last version on the server , last chrome and last extension version . 

(direct conntection via web works fine)

thanks

**Comment by pomporov** [comment]
I just tested exact same error via OSX native app .

**Comment by BlackDex** [comment]
Works fine for me.
Try to fully logout and login again (not lock).
There were some issues with the clients in some cases, which are solved when you fully logout.
