### ISSUE TITLE
Notifying about Emergency access in the UI and in the clients

### ISSUE THREAD

**Issue by GreenBlast** [dani-garcia/vaultwarden#4352]
### Discussed in https://github.com/dani-garcia/vaultwarden/discussions/4351

<div type='discussions-op-text'>

<sup>Originally posted by **GreenBlast** February 15, 2024</sup>
Hi. 

Thanks for this project. Really amazing.

I was testing the emergency access function and was surprised to discover that the emergency access request is almost silenced.

I would have expected some notification in the clients and also some notice or banner in the UI. In case of the emergency access account is compromised, it is very important to be notified about emergency access requests so they could be rejected on time.

I also encountered the same feature request in the Bitwarden forums.
https://community.bitwarden.com/t/client-notification-banner-etc-of-emergency-access-request/16906/1

Is there a chance we could add some banner in the UI, and add some push notification about emergency access request? I think it will be a good improvement for the current state.

</div>

**Comment by BlackDex** [comment]
Going to close this as 1. Duplicate, 2. Not something we can fix on there server side.

**Comment by BlackDex** [comment]
Also, if you have mail enabled, you do receive an email about this.
