### ISSUE TITLE
    Feature request Duckduckgo Email protection

### ISSUE THREAD

**Issue by TheRealRWJ** [dani-garcia/vaultwarden#4376]
###     Feature request
Hello developers
Thank you for this awesome app
    
Would it be possible to add duckduckgo as a provider to generate a private duck address?
Thanks in advance

**Comment by nzedler** [comment]
There is no provider restriction. Just add the respective SMTP fields. Or am I missing something?

```
SMTP_HOST=smtp.domain.tld
SMTP_FROM=vaultwarden@domain.tld
SMTP_FROM_NAME=Vaultwarden
SMTP_USERNAME=username
SMTP_PASSWORD=password
SMTP_TIMEOUT=15
```

**Comment by fvultee** [comment]
It is already fully supported.  You just need to select duckduckgo as an email forwarder in the Generator section of the extension and then paste in your duckduckgo API key.  Look on the Bitwarden site for how to do this, fairly straightforward and once you paste it in to the extension it works as expected.

**Comment by TheRealRWJ** [comment]
Again thanks for tour quick response.
I am selfhosting vaultwarden nut dont zee duckduckgo listed as an option.
I updated the container today

**Comment by fvultee** [comment]
Did you go to the generator and click 'username' and 'forwarded email aliases', then select the service?  I have duckduckgo and about half a dozen other services listed (see below)

![image](https://github.com/dani-garcia/vaultwarden/assets/25049089/4d697802-09ec-472e-96eb-b06ec3d39d93)

**Comment by TheRealRWJ** [comment]
Thanks for your quick reply.

Simplelogin, Fastmail, addy.io and forward Email are the only s|lectable options i see listed.

What might be the reason I don't see other options line duckduckgo?

**Comment by BlackDex** [comment]
Within the web-vault that is true. We aren't able to use others.
Those are not working for self-hosted systems, also not Bitwarden self-hosted.

**Comment by TheRealRWJ** [comment]
Looks like you're waiting for my message.

Thanks again four your answer
Unfortunately.
I will close the issue
