### ISSUE TITLE
I'm having issues configuring vaultwarden with YubiKey - "Invalid YubiKey OTP provided"

### ISSUE THREAD

**Issue by LordVZlomka** [dani-garcia/vaultwarden#4388]
### Discussed in https://github.com/dani-garcia/vaultwarden/discussions/4387

<div type='discussions-op-text'>

<sup>Originally posted by **LordVZlomka** February 28, 2024</sup>
Hi,

I need help figuring out why my YubiKey doesn't work. I've got my client ID and Secret Key from the YubiKey API page and added the environment variables into my docker container (Synology). I get an error when I enter the OTP code by long pressing my key.
"Invalid YubiKey OTP provided"

![Screenshot_2](https://github.com/dani-garcia/vaultwarden/assets/71541816/9d405a62-917a-4e2b-9c00-eaa15fbf0079)</div>

**Comment by BlackDex** [comment]
Closing this as there already is a discussion open.
Please do not open two exact the same items in two different locations.
