### ISSUE TITLE
Version reported by api/config is wrong

### ISSUE THREAD

**Issue by peterge1998** [dani-garcia/vaultwarden#4389]
### Deployment environment

* vaultwarden version:     image: "vaultwarden/server:latest"

* Install method:
Docker compose

* Clients used: 
Firefox

* Reverse proxy and version: 
none

* Other relevant details:

### Steps to reproduce
visit http://miprdvaultwarden.company.lan:8060/api/config:
![image](https://github.com/dani-garcia/vaultwarden/assets/47355238/76ca9517-0011-4032-90a3-eb3b7829f43b)

### Expected behaviour
Show the actual version thats displayed on the http://miprdvaultwarden.company.lan:8060/#/login page:
![image](https://github.com/dani-garcia/vaultwarden/assets/47355238/b4b3546e-6946-4ab0-be95-8d30a27240ca)

### Actual behaviour
It shows 2023.9.1

### Troubleshooting data
    image: "vaultwarden/server:latest"

**Comment by BlackDex** [comment]
This works as intended:
https://github.com/dani-garcia/vaultwarden/blob/d6b97090fab5eba429a79c35735a0760b2fa9ee2/src/api/core/mod.rs#L196-L201

See:
https://github.com/dani-garcia/vaultwarden/discussions/4034#discussioncomment-7486742
#4040
#4079

**Comment by peterge1998** [comment]
Ah okay, whats the best way to get the current version of vaultwarden then?

**Comment by BlackDex** [comment]
It is there already.
![image](https://github.com/dani-garcia/vaultwarden/assets/610450/7628dd46-97ec-46ef-976c-b5ffb6402a9c)

It also is there in your current screenshot. See the `version` within the `server` path.
