### ISSUE TITLE
Unable to login to web vault after uprgade to 1.30.5 with error "2FA token not provided"

### ISSUE THREAD

**Issue by aheath70** [dani-garcia/vaultwarden#4401]
### Subject of the issue
After uprgade to 1.30.5 unable to log in using thge web vault. Log shows the following error:

```
"[2024-03-03 10:16:21.546][error][ERROR] 2FA token not provided"
```

Reverted back to version 1.30.3 and still getting the same error. Did a complete re-install of the machine, and still getting the same error.

iOS app appears to be able to still access the vault, but don't want to log out of it in case I can't log back in. Still able to login to admin page as well. Only appears to be the web vault which is affected.

### Deployment environment

* vaultwarden version: 1.30.5

* Install method: Docker

* Clients used:  web vault

* Reverse proxy and version:  NGINX Proxy Manager, v2.11.1

* MySQL/MariaDB or PostgreSQL version:  N/A

* Other relevant details:

### Steps to reproduce

N/A

### Expected behaviour

Able to login successfully.

### Actual behaviour

Not able to log in with error,

### Troubleshooting data

```
/--------------------------------------------------------------------\
|                        Starting Vaultwarden                        |
|                           Version 1.30.5                           |
|--------------------------------------------------------------------|
| This is an *unofficial* Bitwarden implementation, DO NOT use the   |
| official channels to report bugs/features, regardless of client.   |
| Send usage/configuration questions or feature requests to:         |
|   https://github.com/dani-garcia/vaultwarden/discussions or        |
|   https://vaultwarden.discourse.group/                             |
| Report suspected bugs/issues in the software itself at:            |
|   https://github.com/dani-garcia/vaultwarden/issues/new            |
\--------------------------------------------------------------------/
[INFO] Using saved config from `data/config.json` for configuration.
[2024-03-03 10:16:00.256][error][ERROR] 2FA token not provided
```

**Comment by aheath70** [comment]
Just sorted it! It was a problem with my reverse proxy set up. Apologies!

**Comment by celevra** [comment]
i've the same issue and also an reverse proxy
what was the exact issue?

**Comment by aheath70** [comment]
Not sure, TBH. I use Cloudflare Zero Trust and I ended up bypassing my reverse proxy and just using the reverse proxy built into Cloudflare.
