### ISSUE TITLE
Vaultwarden is no longer asking me to 2FA/MFA when signing in.

### ISSUE THREAD

**Issue by alternativesurfer** [dani-garcia/vaultwarden#4421]
### Subject of the issue

I signed into Vaultwarden today and was not prompted for my 2FA code.
I signed in to the full vault without having to provide a second factor.

### Deployment environment

* vaultwarden version:

* Install method:

* Clients used: 
Web/Edge app/Android app
* Reverse proxy and version: 
HAProxy

* MySQL/MariaDB or PostgreSQL version: 
postgresql

* Other relevant details:

### Steps to reproduce

I launched my browser, signed into the browser addon (https://microsoftedge.microsoft.com/addons/detail/jbkfoedolllekgbhcbcoahefnbanhhlh) and was allowed to access my vault without entering 2FA.

I confirmed I have multiple 2FA types enabled.

I then tested from the browser window, same behavior.

**Comment by BlackDex** [comment]
MFA/2FA is cached if you check the remember device.
![image](https://github.com/dani-garcia/vaultwarden/assets/610450/2578c4fb-af18-40ca-964f-ce83aaea5412)

Try to do the same in a InCognito/Private Window.

**Comment by alternativesurfer** [comment]
Thaaaaat was it.
Thank you!
