### ISSUE TITLE
[Postgresql/DB] Database URL changes not respected

### ISSUE THREAD

**Issue by Ornias1993** [dani-garcia/vaultwarden#4511]
### Subject of the issue
When changing the DATABASE_URL ENV var, the change isn't respected and the application still tries to access the old url.
This is primarily important when database passwords change.

Having this as an env-var gives the impression it does more than just set it at first boot.

### Deployment environment
Docker/Helm/Kubernetes, irrelevant (container feature)

* vaultwarden version:
Latest (All?)

* Install method:

* MySQL/MariaDB or PostgreSQL version:
Postgresql, should alson happen with MariaDB

* Other relevant details:

### Expected behaviour

- Install in what-ever way you fancy
- Change database password on the side of the DB
- Change DATABASE_URL env var to match the new password
- Cannot connect

### Actual behaviour
- It should respect the new env var

### Troubleshooting data
Might be related to using the admin interface afterwards or not, this I would need to verify

**Comment by BlackDex** [comment]
You probably have changed/saved the config via the Admin Interface, in that case there is a `config.json` located in the data directory. Values in the `config.json` override environment variables.

**Comment by Ornias1993** [comment]
> You probably have changed/saved the config via the Admin Interface, in that case there is a `config.json` located in the data directory. Values in the `config.json` override environment variables.

Well it's not me, it's one of our users...
I might've been to receptive for the feedback there, i'll reopen if I can reproduce more thoroughly!

**Comment by Ornias1993** [comment]
Can confirm user error, issue can stay closed.
