### ISSUE TITLE
Enable support for DUO Universal Login prompt

### ISSUE THREAD

**Issue by jeroen-ansink** [dani-garcia/vaultwarden#4529]
### Subject of the issue
Currently unable to login, because DUO Universal login prompt is not supported.

### Deployment environment

* vaultwarden version: 

* Install method: docker image

* Clients used: web vault

* Reverse proxy and version: caddy 2

* Other relevant details:

### Steps to reproduce
Try to login with DUO 2FA enabled.

### Expected behaviour
Able to login using DUO

### Actual behaviour
Unable to login using DUO

### Troubleshooting data
<img width="794" alt="Scherm­afbeelding 2024-04-30 om 08 49 22" src="https://github.com/dani-garcia/vaultwarden/assets/144269883/5bd921a7-fb32-4898-9832-eb562e0e89d8">

**Comment by jeroen-ansink** [comment]
Ok, is there maybe a way to disable DUO in the backend without being able to login to the frontend and without having a recovery code?

**Comment by BlackDex** [comment]
You can remove all MFA/2FA from your account via the `/admin` interface

**Comment by ajb3932** [comment]
![image](https://github.com/dani-garcia/vaultwarden/assets/45558436/06ac6363-e966-4d73-a067-c64f72544e52)

I'm also having this issue too. No pressure to fix asap from me, just wanted to raise awareness.

**Comment by BlackDex** [comment]
There seems to be a bug in the latest web-vault btw https://github.com/bitwarden/clients/issues/8554
Not sure if that is also the case in the web-vault we currently bundle, but i do not think so.

**Comment by GeorgeCastanza** [comment]
Me too.  As a new user, it wont allow me to use the old (expired, but still working until Sep-24 for some) prompt.

**Comment by 0x0fbc** [comment]
I saw the 'help wanted'. Is there any specific assistance you're looking for? If there isn't anyone actively working on this, I can take a shot at it.

**Comment by BlackDex** [comment]
@0x0fbc, i only looked at the available code of the universal duo implementation provided by Duo in the python and php language to have a baseline. But not yet started coding it.

So, if you want to take a crack at it, feel free to do so 😄.
Everytime I want to start on it i need to do other stuff instead or I am hindered to use a laptop unfortunately.

If you need some help you can find me on our Vaultwarden Matrix channel.

**Comment by yurividal** [comment]
This is odd. i have DUO enabled in my account, and I can login just fine with it.
I am running latest vaultwarden, and have had DUO activated for more than 1 year.

**Comment by ajb3932** [comment]
Effective March 30, 2024 Duo no longer supports the traditional Duo Prompt for most applications.

I think it only affects users trying to activate Duo since March 30th.

**Comment by Simon-CR** [comment]
that would most likely explain this: Can't fetch Duo Keys error when trying to log into the web vault.  Issue is that I even if I the global duo configuration in /admin, I had them configured manually in the individual vault .. kind of stuck ..

**Comment by BlackDex** [comment]
Fixed via #4637
