### ISSUE TITLE
Resolving Item Creation Issues for Manager Role

### ISSUE THREAD

**Issue by bxdcxdx** [dani-garcia/vaultwarden#4601]
### Subject of the issue
In the current version of Vaultwarden, users assigned the “Manager” role experience issues when creating items within newly created folders. This problem manifests consistently across all browsers and operating systems, indicating that it is specifically related to the role permissions rather than the environment.

Consistency and Workarounds:

- This issue occurs every time the described steps are followed, making it a persistent problem for users with the Manager role.
- As a temporary workaround, managers must reload the page to see and use the new folder.
- Alternatively, assigning the manager the Admin role resolves the issue, but this is not a viable long-term solution due to role-specific permissions and security considerations.

Related Issues:
- There is an additional known issue where users with the Manager role cannot delete collections, which further complicates management tasks.

### Deployment environment

* vaultwarden version: 1.30.5

* Install method: docker

* Clients used: web vault

* Reverse proxy and version: Apache HTTP Server version 2.4.54 on the Alpine Linux base

* MySQL/MariaDB or PostgreSQL version: SQLite: 3.44.0

* Other relevant details:

### Steps to reproduce

1. Manager Role Actions:
- A manager logs into Vaultwarden.
- The manager creates a new folder, for example, named “test”.
- The manager navigates into the newly created folder “test”.
- The manager attempts to create a new item within this folder.
2. Encountered Problem:
- The new folder “test” does not appear in the “Collections” list.
- Consequently, the manager is unable to assign the item to the newly created folder.
- To proceed, the manager is forced to reload the entire page.

### Expected behaviour
see the newly created Collection in the Collection list.

### Actual behaviour
Can't see the newly created Collection in the Collection list without a page reload.

**Comment by BlackDex** [comment]
Already resolved via #4517.

Please user the testing tagged container to make use of this fix.
