### ISSUE TITLE
Chrome extension fails CORS due to missing origin

### ISSUE THREAD

**Issue by RaidAndFade** [dani-garcia/vaultwarden#4665]
### Subject of the issue

Latest version of chrome bitwarden extension requires cors header response, which current codebase does not do.

### Steps to reproduce

Download bitwarden chrome extension, try to use vaultwarden as a backend, all POST requests fail due to missing ORIGIN header

### Expected behaviour

expect bitwarden extension works

### Actual behaviour

bitwarden extension receives data but cannot push any new information to vault

### Troubleshooting data

origin header is of format 
Origin: chrome-extension://nngceckbfpebfimklniiiawkandclblb
Code found at https://github.com/dani-garcia/vaultwarden/blame/main/src/util.rs#L133 to allow the domain as well as safari extension "file://" but not chrome-extension prefix. Believe some work is doable there.

**Comment by RaidAndFade** [comment]
Actually, looks to be an issue on the extension itself, there is a closed ticket there that explains the problem, this workaround seems to resolve the issue 
https://github.com/bitwarden/clients/issues/1612#issuecomment-1116438789

**Comment by BlackDex** [comment]
Closing this as it's a client issue, which also seems to be fixed already.
