### ISSUE TITLE
v1.31.0 not fully updated somehow

### ISSUE THREAD

**Issue by TheProcedural** [dani-garcia/vaultwarden#4739]
I know I'm disregarding the issue's guidelines but please bare with me.

After updating to 1.31.0 everything is fine except the web UI which didn't get updated as well but according to the change-logs it has been updated. Am I missing something? or maybe I'm being a dummy and did something wrong?

### My install diagnostics:
![image](https://github.com/user-attachments/assets/9227a9d9-c4aa-4d94-8dbe-ba82fbebf128)

### Changelog notes:
![image](https://github.com/user-attachments/assets/1be9ee01-4fcd-4f02-afef-b6df93996ee2)

**Comment by BlackDex** [comment]
Then you probably overruled the web-vault directory, or are not using the docker images we provide.

**Comment by TheProcedural** [comment]
I'm using the official image, the web-vault directory might be the reason:

My current mounts:
![image](https://github.com/user-attachments/assets/85ea2e9a-5f55-4b7d-b570-79840cfff014)

Do I need to remove the web-vault one then?

**Comment by TheProcedural** [comment]
I assume yes, dummy me!. Thank you for your quick response!
