### ISSUE TITLE
iOS sync not finding new items

### ISSUE THREAD

**Issue by navels** [dani-garcia/vaultwarden#4757]
### Subject of the issue
The iOS app isn't showing new vault items.

### Deployment environment

Note: installed via proxmox helper script (https://tteck.github.io/Proxmox/) and running behind Nginx Proxy Manager with websocket support enabled (although I assume websockets have nothing to do with this)

### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.31.0-54bfcb8b
* Web-vault version: v2024.5.1b
* OS/Arch: linux/x86_64
* Running within a container: false (Base: Not applicable)
* Environment settings overridden: true
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.45.0
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** ADMIN_TOKEN

```json
{
  "_duo_akey": null,
  "_enable_duo": true,
  "_enable_email_2fa": false,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_smtp_img_src": "cid:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "/opt/vaultwarden/data/attachments",
  "auth_request_purge_schedule": "30 * * * * *",
  "authenticator_disable_time_drift": false,
  "data_folder": "/opt/vaultwarden/data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "********************************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://************",
  "domain_origin": "*****://************",
  "domain_path": "",
  "domain_set": true,
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "email_2fa_auto_fallback": false,
  "email_2fa_enforce_on_verified_invite": false,
  "email_attempts_limit": 3,
  "email_change_allowed": true,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "enable_websocket": true,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "experimental_client_feature_flags": "fido2-vault-credentials",
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "http_request_block_non_global_ips": true,
  "http_request_block_regex": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "/opt/vaultwarden/data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Vaultwarden",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "Info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 600000,
  "push_enabled": false,
  "push_identity_uri": "https://identity.bitwarden.com",
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.com",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "/opt/vaultwarden/data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "/opt/vaultwarden/data/sends",
  "show_password_hint": false,
  "signups_allowed": false,
  "signups_domains_whitelist": "",
  "signups_verify": false,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "",
  "smtp_from_name": "Vaultwarden",
  "smtp_host": null,
  "smtp_password": null,
  "smtp_port": 587,
  "smtp_security": "starttls",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": null,
  "templates_folder": "/opt/vaultwarden/data/templates",
  "tmp_folder": "/opt/vaultwarden/data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "user_send_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "/opt/vaultwarden/web-vault",
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>

### Steps to reproduce
- Create a new vault entry via the chrome extension or the vault web ui
- Open the iOS bitwarden app, pull down to refresh
- Search for the new entry

### Expected behaviour
New entry is found

### Actual behaviour
New entry is not found

### Troubleshooting data
I ran the same test using my regular bitwarden account (i.e., not self-hosted vaultwarde) and it worked fine.

**Comment by BlackDex** [comment]
What are the logs during this whole endeavor?
Login on the web-vault and prepare a new password entry.
And then from that point the logs when doing the following with the native iOS client.
1. Login (So fully logout before of course)
2. Try to use the pull-to-sync function (Logs should indicate something happened)
3. Save the new entry
4. Use the pull-to-sync again (again logs should be indicating it works) and see if the entry is there
5. If not, try to force a sync via the settings and check again

From the above steps we would like to have all the logs so that we can see if something is going wrong there.

**Comment by BlackDex** [comment]
btw, i tested this on an Android with the current `testing` tagged version, and i can pull-to-sync just fine and it will update the information. The client version I'm using is v2024.7.0 (18845)

**Comment by navels** [comment]
Aha interesting, if I log out and back in on my iPhone, it does a sync.  If i do a manual sync via the chrome extension, I get this in the logs:

```
Jul 17 09:26:57 vaultwarden vaultwarden[94606]: [2024-07-17 09:26:57.216][request][INFO] POST /identity/connect/token
Jul 17 09:26:57 vaultwarden vaultwarden[94606]: [2024-07-17 09:26:57.217][response][INFO] (login) POST /identity/connect/token => 200 OK
Jul 17 09:26:57 vaultwarden vaultwarden[94606]: [2024-07-17 09:26:57.417][request][INFO] GET /api/sync
Jul 17 09:26:57 vaultwarden vaultwarden[94606]: [2024-07-17 09:26:57.440][response][INFO] (sync) GET /api/sync?<data..> => 200 OK
```

whereas if I pull to sync in the iOS app I get nothing in the logs.  So . . . gotta be an iOS client bug, right?  I will log one.

**Comment by navels** [comment]
I switched to the Beta iOS client, still not seeing pull to refresh hitting my server.

Logged https://github.com/bitwarden/ios/issues/742

**Comment by navels** [comment]
Well duh . . . apparently there is an **Enable sync on refresh** setting
