### ISSUE TITLE
Web interface 2024.5.1b doens't allow more than 10 organization members

### ISSUE THREAD

**Issue by Wiredista** [dani-garcia/vaultwarden#4770]
### New Admin Console allows only 10 organization members
When trying to add more members to an organization I get this message.

> **Update Organization**
> Free organizations can have up to 10 members. Upgrade to a paid plan to invite more members.

Message above may be inaccurate as it was translated from Portuguese.

### Deployment environment
* Vaultwarden version: v1.31.0
* Web-vault version: v2024.5.1b
* OS/Arch: linux/x86_64
* Running within a container: true (Base: Debian)
* Environment settings overridden: false
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: false
* HTTPS Check: false
* Database type: SQLite
* Database version: 3.45.0
* Clients used: Vaultwarden Web Interface
* Reverse proxy and version: Nginx
* Other relevant information: Recently updated from previous version, using docker image vaultwarden/server:latest
* 
### Steps to reproduce
Prerequisites: Have an account and organization created on your installation.

1. Log in as an organization administrator
2. Go to "Admin Console"
3. Go to "Members"
4. Invite and confirm 10 members.
5. Try to invite new member.

### Expected behaviour
It should allow the addition of new members

### Actual behaviour
You get the message:
> **Update Organization**
> Free organizations can have up to 10 members. Upgrade to a paid plan to invite more members.
* Message above may be inaccurate as it was translated from Portuguese.

**Comment by stefan0xC** [comment]
This has been fixed by #4726 and is available in `testing` (and should be part of the next release).

**Comment by ake-cn** [comment]
I also encountered this problem while using it today! When will the next version be released?

**Comment by ake-cn** [comment]
When will the Great God release an updated version of this feature? At present, there is no way to add new members, so we are in a hurry.
@stefan0xC

**Comment by BlackDex** [comment]
@ake-cn you can install the `testing` release and help us make sure it is fixed.

**Comment by ake-cn** [comment]
> @ake-cn you can install the release and help us make sure it is fixed.`testing`

After testing, the latest test version has solved 10 user restrictions. thank.

**Comment by 3gmgithub** [comment]
Just checking in to see when the next release that fixes this issue will be out....
