### ISSUE TITLE
Unable to bulk-change collection for a selection of items in web interface

### ISSUE THREAD

**Issue by ronan-paul** [dani-garcia/vaultwarden#4776]
### Subject of the issue
When you select a bunch of items in an organisation, the action menu does not propose to change the collection they belong: only "delete" option is proposed.

### Deployment environment
* vaultwarden version: 2024.5.1
* Install method: Docker image
* Clients used: Web interface from Chromiulm

### Steps to reproduce
- Select a bunch of items in an organisation
- Click on the action menu on the upper right of the page

### Expected behaviour
The one described in the wiki (https://bitwarden.com/help/about-collections/#bulk-assign-items-to-collections) 
![image](https://github.com/user-attachments/assets/087b992b-ef53-41d6-a607-335ce647742f)

### Actual behaviour
Only the "delete selection" option is proposed 

### Troubleshooting data
<img width="953" alt="image" src="https://github.com/user-attachments/assets/3d13cce9-c881-4dbd-831c-03548c64db0f">

**Comment by BlackDex** [comment]
This is not yet available in the web-vault we have build and released.
It will be when we update the web-vault.

Going to close this, as this is not really an issue.

**Comment by wni-matthewcurran** [comment]
@BlackDex Do you know if this is meant to be available in the web vault now? I have the same behavior on latest (1.33.2) and testing (1.33.2-2697fe8a) docker containers.

Is there a work around? Will this work on any of the apps or maybe CLI?
