### ISSUE TITLE
invited, confirmation required and revoked user tables not showing correct

### ISSUE THREAD

**Issue by notenoughwoodsire** [dani-garcia/vaultwarden#4830]
### Subject of the issue
Following Tables are not displaying in the admin console correctly: invited, confirmation required and revoked user. All show a specific number of invited members, but no entries are shown if tab is active.

### Deployment environment

* vaultwarden version: 1.31

* Install method: docker

* Clients used: not applicable

* Reverse proxy and version: not applicable

* MySQL/MariaDB or PostgreSQL version: latest build for vaultwarden, no special setup

* Other relevant details:

### Steps to reproduce

Log into organisation owner account, goto admin console, navigate to members section, select anything other than "all" members in the upper tab selection, nothing will show, even if a number of members greater than 0 are invited or revoked

### Expected behaviour
invited or revoked members showing below the tab

### Actual behaviour
no entries are shown

### Troubleshooting data
![grafik](https://github.com/user-attachments/assets/c026a649-2d11-4936-b6ff-138b3d34ebb9)
![grafik](https://github.com/user-attachments/assets/d3915173-73ff-41e5-82e7-9c0a855cd139)
![grafik](https://github.com/user-attachments/assets/b5187946-466f-4b20-8c7a-65070d981003)

**Comment by BlackDex** [comment]
Please test the `testing` tagged versions of Vaultwarden and report back.
Those use a newer version of the web-vault and might solve your issue.

**Comment by mightyBroccoli** [comment]
This issue is solved when the web-vault is updated to at least [v2024.6.2](https://github.com/dani-garcia/bw_web_builds/releases/tag/v2024.6.2)

**Comment by BlackDex** [comment]
Closing as resolved
