### ISSUE TITLE
Your local data is too old to be migrated

### ISSUE THREAD

**Issue by textgroove-steven** [dani-garcia/vaultwarden#4846]
### Subject of the issue
Vaultwarden login page is blank and I am getting the following error:

```
Error: Your local data is too old to be migrated. Your current state version is 1, but minimum version is 2.
    at main.b193f247301cc37bf60b.js:3:148310
    at Generator.next (<anonymous>)
    at main.b193f247301cc37bf60b.js:3:148109
    at new t (polyfills.4275a7f2798b637a6613.js:1:199264)
    at ls (main.b193f247301cc37bf60b.js:3:147854)
    at migrate (main.b193f247301cc37bf60b.js:3:148246)
    at Kn.<anonymous> (main.b193f247301cc37bf60b.js:3:139240)
    at Generator.next (<anonymous>)
    at r (main.b193f247301cc37bf60b.js:3:138258)
    at t.invoke (polyfills.4275a7f2798b637a6613.js:1:187708)
    at I (polyfills.4275a7f2798b637a6613.js:1:198345)
    at I (polyfills.4275a7f2798b637a6613.js:1:197893)
    at polyfills.4275a7f2798b637a6613.js:1:199000
    at t.invokeTask (polyfills.4275a7f2798b637a6613.js:1:188392)
    at Object.onInvokeTask (vendor.351bf938ddfd5e202e99.js:1:2172203)
    at t.invokeTask (polyfills.4275a7f2798b637a6613.js:1:188313)
    at e.runTask (polyfills.4275a7f2798b637a6613.js:1:183421)
    at b (polyfills.4275a7f2798b637a6613.js:1:190798)
```

### Deployment environment

* vaultwarden version:
All versions above 1.29

* Install method: Docker image

* Clients used: Any web browser

* Reverse proxy and version: Cloudflare Tunnel

* MySQL/MariaDB or PostgreSQL version: MySQL [5.7.27-30]

* Other relevant details:

### Steps to reproduce
Was on version 1.26, upgraded one version at a time all the way to 1.29. At 1.30, it breaks, 1.29 seems to be okay.

### Expected behaviour
It will work and I can log into the system as expected.

### Actual behaviour
No log in form shows at all, just the above error in the error log. Tried in incogneto and other browsers as well, same issue.

**Comment by BlackDex** [comment]
Not sure why you are upgrading one version at a time. Just update to the latest version and it should be working. 

Just create s backup of you do not trust it. While making backups is always a good idea though.

Also, that error is a client error, which we can't really fix as we do not maintain those.

**Comment by textgroove-steven** [comment]
@BlackDex That is the problem, I just went to the newest and it broke completely. So I went back and did one at a time to find the version it broke in. Anything above 1.30 doesn't work.

What do you mean you don't maintain it? The error I am reporting is at https://vaultwarden.domain.com/#/login (on the hosted page). The page is not loading at all and I am getting the above error.

**Comment by BlackDex** [comment]
Clients are not build by Vaultwarden, so the error reported doesn't help really. Vaultwarden is only the server backend.

The error you have might be cache issues of the browser or your reverse proxy maybe. Try a different browser, Incognito/Private mode and check again.

**Comment by textgroove-steven** [comment]
Interesting, where do you get the clients from that I might be able to report this issue? Bitwarden themselves?

I have tried multiple computers, browsers, incognito, etc. Same issue.

**Comment by BlackDex** [comment]
It clearly states the local client data is too old. Which would be non existing if you opened it in a private window which should have no prior data and starts all over and nothing to be migrated at all.

**Comment by BlackDex** [comment]
The web-vault is build from the official client repo with some small patches to make it work correctly with Vaultwarden. All other clients are the original Bitwarden clients.

**Comment by textgroove-steven** [comment]
Okay, I will reach out to Bitwarden with my error and see what they say.

I know what it states which is why I am very confused that even when I open the site in an incognito window, or a computer which has NEVER used it before, or a brand new browser I just installed, I get the exact same error.

**Comment by BlackDex** [comment]
And what happens with a new account?

Also, i do not think Bitwarden will help at all. 1 this is an older web-vault version. Second you use Vaultwarden for which they do not provide support.

The main issue for me is, this client issue doesn't make sense within a empty browser never used browser. And we are probably not able to reproduce this error at all i think.

**Comment by BlackDex** [comment]
Ah, glad it works now!

Really weird issue.

**Comment by Luckyluke1988** [comment]
Hi i just had the same Problem.
Just clear Browser Cache in Settings, ctl + F5 wont be enough.

**Comment by KiritaniAyaka** [comment]
> Hi i just had the same Problem. Just clear Browser Cache in Settings, ctl + F5 wont be enough.

In more detail. Press F12 to open the DevTools and switch to the Application tab. Then, clear the Local storage and Session storage.
