### ISSUE TITLE
Cannot create more than 10 collections after updating to 1.31.0

### ISSUE THREAD

**Issue by senpro-ziegerl** [dani-garcia/vaultwarden#4851]
### Subject of the issue 
After updating to Vaultwarden 1.31.0, we are no longer able to create more than 10 collections for an organization

### Deployment environment

* vaultwarden version: 1.31.0

* Install method: Kubernetes (K3S) container with the GitHub image, NixOS as the underlying OS

* Clients used: Web Vault

* Reverse proxy and version: Traefik

* MySQL/MariaDB or PostgreSQL version: PostgreSQL 15

* Other relevant details: - 

### Expected behaviour
To be able to create more than 10 collections per organization, as it previously worked

### Actual behaviour
Received a popup that free organizations can only have up to 10 collections and that the plan needs to be upgraded

### Troubleshooting data
![image](https://github.com/user-attachments/assets/65676917-e4fb-4599-806d-1f6372cb4bdc)

**Comment by BlackDex** [comment]
Already resolved in 1.32.0
