### ISSUE TITLE
Bitwarden beta app completely broke entire vaultwarden backend

### ISSUE THREAD

**Issue by PartyingChair** [dani-garcia/vaultwarden#4861]
### Subject of the issue
I created a new login item in the bitwarden beta iOS app. (TO BE CLEAR: I'M AWARE IT IS A BETA, BUT THIS MIGHT BE SOMETHING ON VAULTWARDENS BACK END THAT CAUSED IT - NOT SURE). I changed the Owner to an organization, and then set the collection. I hit save, and got an error that ready: Cryptography error, The cipger's MAC doesn't match the expected value. Now I cannot log into vaultwarden. Tried on the web, windows app, mac app, beta ios app, and non-beta ios app. All either load infinitely, say wrong user/pass, or crash. 

### Deployment environment

* Install method:
Unraid, docker

* Clients used: 
iOS app, Windows app, mac app. 

* Reverse proxy and version: 
Cloudflare tunnels

* MySQL/MariaDB or PostgreSQL version: 

* Other relevant details:

### Steps to reproduce
Create login using bitwardens beta app on iOS (note; I did this in the app, not in the passwords autofill pop up). Set organization. Set collection. Save, and that is when I got the error

### Expected behaviour
To save the new item to the collection/organization

### Actual behaviour
App crashed, and broke database so I cannot get it back up. Had to delete account and start from scratch (again, I know it's a beta, I have backups of all data)

### Troubleshooting data
![Screenshot 2024-08-14 at 4 53 31 PM](https://github.com/user-attachments/assets/5a5021c0-ecaa-4e71-826f-c4f18145edaa)

**Comment by stefan0xC** [comment]
What vaultwarden version did you use?

**Comment by PartyingChair** [comment]
Yeah... that might be my bad. I let auto update do its thing so have a habit of assuming I'm on the latest. I'm on 1.31.0 which appears not to be the latest. I'll update it.

**Comment by PartyingChair** [comment]
And yup, I'm just dumb for not checking the update. Fixed. I'll mark as closed.
