### ISSUE TITLE
Organisation user are disappearing 

### ISSUE THREAD

**Issue by spiritblue01** [dani-garcia/vaultwarden#4874]
### Subject of the issue
After the update to latest version 1.32 users of an organization are disappearing. I can invite a member and assign in to a collections. The user is showing up in the member list and he gets an invitation. After he is accepting the user just disappear in the list. 

I can invite him again now it's showing the name, not only the email like in the first invite. But if he is accepting, he disappears again. 

### Deployment environment

Version 1.32.
Web Version 2024.6.2

Synology DS718+ with Docker

I changed also the KDF iterations to 600.000 because there was a warning

**Comment by BlackDex** [comment]
Please provide screenshots, logs, the `/admin/diagnostics` Support String, and a step-by-step on how to reproduce this specific issue.

**Comment by stefan0xC** [comment]
@spiritblue01 The vaultwarden server logs (ideally from the time the user registered and logged in). If you have events logged enabled, that might also give some clues.

Does the user appear in the Revoked tab?

**Comment by spiritblue01** [comment]
no it does not appear in the revoked tab.

**Comment by BlackDex** [comment]
If the user in the `/admin` overview show that it is part of an org, it probably is part of that org.

Also, what happens if you do not search via the search bar at the top-right but just look for that user by hand, or use the browser search, and check all `Members` tabs, so, `All`, `Invited`, `Revoked`.

**Comment by spiritblue01** [comment]
> If the user in the `/admin` overview show that it is part of an org, it probably is part of that org.
> 
> Also, what happens if you do not search via the search bar at the top-right but just look for that user by hand, or use the browser search, and check all `Members` tabs, so, `All`, `Invited`, `Revoked`.

That is exactly the issue after accepting the invite it is not showing that the user is part of the org it is just blank like in my screenshot. But the user was part of the org once I invited.

**Comment by BlackDex** [comment]
The provide the logs during the moments of
- inviting the user 
- the user accepting the invite 

And if possible, screenshots of the user being in the invite list.

The only thing i can think of is a org policy which removes the user because of policy validations.

**Comment by spiritblue01** [comment]
issue not happened again
