### ISSUE TITLE
Unable export password store after login by device

### ISSUE THREAD

**Issue by Aelliari** [dani-garcia/vaultwarden#4875]
### Subject of the issue
Unable export password store after login by device

### Deployment environment

* vaultwarden version: 1.32

* Install method: docker

* Clients used: web vault 2024.6.2, iOS 2024.7.1 (8086)

* Reverse proxy and version: cloudflare
* MySQL/MariaDB or PostgreSQL version: 1:11.5.2+maria~ubu2404
* Other relevant details: I tested only with 2fa enabled

### Steps to reproduce

1. In web vault enter email your account and press "Log in with device"
2. After succsesful login press "tool -> Export vault -> select any format"
3. After entering master password -> error by incorrect master password. But same time you can change setting protected master password, for example - 2fa setting, and no issue with enter master password
### Expected behaviour

Succesful export password store
### Actual behaviour

Master password error in export menu, but not affected an setting protected by master password

**Comment by BlackDex** [comment]
Please provide loga which are generated during these attempts.

**Comment by stefan0xC** [comment]
I should really test Vaultwarden more with using a device to login... :face_with_peeking_eye:

**Comment by BlackDex** [comment]
Same here, but current its broken anyway using the new Bitwarden Android Beta version haha

**Comment by BlackDex** [comment]
Also @Aelliari, if you login using your master-password you should be able to export it just fine.

**Comment by Aelliari** [comment]
> Also @Aelliari, if you login using your master-password you should be able to export it just fine.

Sorry for delay, as I understand logs are no longer needed as the issue is reproducible?  I'll only get to pc in a few days anyway

And yep, sorry for not mentioning that with normal login - this function works, I checked that too. Thanks for trying to help :)

**Comment by stefan0xC** [comment]
> I should really test Vaultwarden more with using a device to login... 🫣

to replicate the issue it's also important to not use the master password to unlock the android device but just a pin or biometrics. (so even if i did use a login with device I probably would have missed this).
