### ISSUE TITLE
Rust 2024 breaking changes

### ISSUE THREAD

**Issue by zacknewman** [dani-garcia/vaultwarden#4974]
### Vaultwarden Support String

N/A

### Vaultwarden Build Version

N/A

### Deployment method

Build from source

### Reverse Proxy

N/A

### Host/Server Operating System

Other

### Clients

Web Vault

### Steps To Reproduce

Add `rust-2024-compatibility` to the list of `deny` lints and compile code. One error is caused by some of the macro definitions. For example, `crate::error::make_error` doesn't compile due to "the `expr` fragment specifier will accept more expressions in the 2024 edition".

### Expected Result

Compilation to succeed.

### Actual Result

Compilation failure.

### Additional Context

See [the Migration Guide](https://doc.rust-lang.org/nightly/edition-guide/rust-2024/macro-fragment-specifiers.html) for how to fix this.

**Comment by dani-garcia** [comment]
I don't think the `expr` fragment change is something that needs action from our side, as the change only means that in edition 2024 `expr` will also capture `const` and `_` expressions, while it previously didn't do so, and as far as I can see all our uses of `expr` should be safe as we never match against `const` or `_`, so the macro rules parsing should be unaffected for our usecases.

That said while checking `cargo +nightly fix --edition` I noticed that we're using the `gen` keyword in the macros, which is going to be reserved in 2024, so I've changed that: https://github.com/dani-garcia/vaultwarden/pull/4975

**Comment by BlackDex** [comment]
We could add this:
```toml
rust_2024_compatibility = { level = "deny", priority = -1 }
edition_2024_expr_fragment_specifier = "allow"
```

That would not alert on those maybe to be changed macro's but still warn/deny about all other future items.
