### ISSUE TITLE
about email 2FA error：SMTP error: response error: error Tag at:

### ISSUE THREAD

**Issue by CJSen** [dani-garcia/vaultwarden#4992]
### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.32.0-040e2a7b
* Web-vault version: v2024.6.2c
* OS/Arch: linux/x86_64
* Running within a container: true (Base: Alpine)
* Environment settings overridden: true
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: false
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: n/a
* Domain Configuration Check: false
* HTTPS Check: false
* Database type: SQLite
* Database version: 3.46.1
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** SIGNUPS_ALLOWED, INVITATIONS_ALLOWED, SHOW_PASSWORD_HINT, ADMIN_TOKEN, SMTP_HOST, SMTP_SECURITY, SMTP_PORT, SMTP_FROM, SMTP_USERNAME, SMTP_PASSWORD

```json
{
  "_duo_akey": null,
  "_enable_duo": true,
  "_enable_email_2fa": true,
  "_enable_smtp": false,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_max_note_size": 10000,
  "_smtp_img_src": "cid:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "auth_request_purge_schedule": "30 * * * * *",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "***************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "****://*********",
  "domain_origin": "****://*********",
  "domain_path": "",
  "domain_set": true,
  "duo_context_purge_schedule": "30 * * * * *",
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "duo_use_iframe": false,
  "email_2fa_auto_fallback": false,
  "email_2fa_enforce_on_verified_invite": false,
  "email_attempts_limit": 3,
  "email_change_allowed": true,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "enable_websocket": true,
  "enforce_single_org_with_reset_pw_policy": false,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "experimental_client_feature_flags": "fido2-vault-credentials",
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "http_request_block_non_global_ips": true,
  "http_request_block_regex": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "increase_note_size_limit": false,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Vaultwarden",
  "invitations_allowed": false,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "debug",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 600000,
  "push_enabled": false,
  "push_identity_uri": "https://identity.bitwarden.com",
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.com",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": false,
  "signups_domains_whitelist": "",
  "signups_verify": false,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "****************",
  "smtp_from_name": "Vaultwarden",
  "smtp_host": "***********",
  "smtp_password": "***",
  "smtp_port": 587,
  "smtp_security": "starttls",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": "****************",
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "user_send_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>

### Vaultwarden Build Version

v1.32.0-040e2a7b

### Deployment method

Official Container Image

### Reverse Proxy

nginx 1.27.0

### Host/Server Operating System

Linux

### Operating System Version

ubuntu 22.04

### Clients

Browser Extension, Desktop

### Steps To Reproduce

1. Go to login page and Input password
2. Click on 'login'
3. error

### Expected Result

I declare in advance that I used the beta version of the code to test whether it was a real issue, and this is also the issue in the official version.
1.  I have configured the SMTP server (QQ email) on the admin page
2. Click on test, an error message appears as shown below, but the test email received the email
<img width="690" alt="image" src="https://github.com/user-attachments/assets/a60ea081-17de-487d-872d-a0095a6f25ab">
![image](https://github.com/user-attachments/assets/ead425f7-4552-42cf-a9b0-5a0c72dd2e6e)

3. Change the SMTP service provider, email sending is normal, and the software is working properly.
4. There was no problem in using it before. So I initially think that the qq mailbox may have made some changes to the return value or other aspects, resulting in an abnormality in the code?

### Actual Result

like Expected Result

### Logs

```text
[2024-09-25 22:35:21.678][request][INFO] GET /vw_static/bootstrap.bundle.js
[2024-09-25 22:35:21.679][response][INFO] (static_files) GET /vw_static/<filename> [2] => 200 OK
[2024-09-25 22:35:29.031][request][INFO] GET /alive
[2024-09-25 22:35:29.031][response][INFO] (alive) GET /alive => 200 OK
[2024-09-25 22:35:43.084][request][INFO] POST /admin/test/smtp
[2024-09-25 22:35:44.002][vaultwarden::mail][DEBUG] SMTP error: lettre::transport::smtp::Error {
    kind: Response,
    source: "error Tag at: \0\0\0\u{1a}\0\0\0\n",
}
[2024-09-25 22:35:44.002][vaultwarden::mail][ERROR] SMTP error: response error: error Tag at:

[2024-09-25 22:35:44.003][response][INFO] (test_smtp) POST /admin/test/smtp => 400 Bad Request
[2024-09-25 22:35:57.910][vaultwarden::api::core::accounts][DEBUG] Purging auth requests
[2024-09-25 22:35:57.910][vaultwarden::api::core::two_factor::duo_oidc][DEBUG] Purging Duo authentication contexts
[2024-09-25 22:35:57.910][vaultwarden::api::core::two_factor][DEBUG] Sending notifications for incomplete 2FA logins
[2024-09-25 22:35:57.911][vaultwarden::api::core::two_factor][INFO] User 461646668@qq.com did not complete a 2FA login within the configured time limit. IP: 192.168.93.124
[2024-09-25 22:35:58.919][vaultwarden::mail][DEBUG] SMTP error: lettre::transport::smtp::Error {
    kind: Response,
    source: "error Tag at: \0\0\0\u{1a}\0\0\0\n",
}
[2024-09-25 22:35:58.919][vaultwarden::mail][ERROR] SMTP error: response error: error Tag at:

[2024-09-25 22:35:58.920][vaultwarden::api::core::two_factor][ERROR] Error sending incomplete 2FA email: SMTP error: response error: error Tag at:

[2024-09-25 22:35:58.920][vaultwarden::api::core::two_factor][INFO] User 461646668@qq.com did not complete a 2FA login within the configured time limit. IP: 192.168.93.124
[2024-09-25 22:35:59.868][vaultwarden::mail][DEBUG] SMTP error: lettre::transport::smtp::Error {
    kind: Response,
    source: "error Tag at: \0\0\0\u{1a}\0\0\0\n",
}
[2024-09-25 22:35:59.868][vaultwarden::mail][ERROR] SMTP error: response error: error Tag at:

[2024-09-25 22:35:59.869][vaultwarden::api::core::two_factor][ERROR] Error sending incomplete 2FA email: SMTP error: response error: error Tag at:




[2024-09-25 22:36:29.099][request][INFO] GET /alive
[2024-09-25 22:36:29.099][response][INFO] (alive) GET /alive => 200 OK
```

**Comment by BlackDex** [comment]
Enable `SMTP_DEBUG=true` and see what it reports.
I do not think we can change anything to solve this.

**Comment by BlackDex** [comment]
If anything, then we need to check with lettre i think @paolobarbolini ?

**Comment by BlackDex** [comment]
Looking at it again, i see the following
> Internet access: false
Which means there is no internet access, not sure how your instance is able to send out an email at all this way.
It might also be something which is between you and the mail server which is causing an issue.

Do you maybe have changed the email templates?

**Comment by CJSen** [comment]
> Looking at it again, i see the following
> 
> > Internet access: false
> > Which means there is no internet access, not sure how your instance is able to send out an email at all this way.
> > It might also be something which is between you and the mail server which is causing an issue.
> 
> Do you maybe have changed the email templates?

Sorry brot，I don't know why it shows no network，but it does have a network.
As I said, although it reported an error when I used the QQ mailbox, my destination mailbox did receive the relevant email. When I switch to another mailbox service（such as @163.com mailbox）, there is no error. Everything is fine.

**Comment by LTI-Lennox** [comment]
I have the same problem

### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.32.0
* Web-vault version: v2024.6.2b
* OS/Arch: linux/x86_64
* Running within a container: false (Base: Not applicable)
* Environment settings overridden: true
* Uses a reverse proxy: false
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: false
* HTTPS Check: true
* Database type: PostgreSQL
* Database version: PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** ADMIN_TOKEN


```json
{
  "_duo_akey": null,
  "_enable_duo": false,
  "_enable_email_2fa": true,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_max_note_size": 10000,
  "_smtp_img_src": "cid:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "auth_request_purge_schedule": "30 * * * * *",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "********://**************************************************************************************************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://***************************",
  "domain_origin": "*****://***************************",
  "domain_path": "",
  "domain_set": true,
  "duo_context_purge_schedule": "30 * * * * *",
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "duo_use_iframe": false,
  "email_2fa_auto_fallback": false,
  "email_2fa_enforce_on_verified_invite": false,
  "email_attempts_limit": 3,
  "email_change_allowed": true,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "enable_websocket": true,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "experimental_client_feature_flags": "fido2-vault-credentials",
  "extended_logging": true,
  "helo_name": "*********",
  "hibp_api_key": null,
  "http_request_block_non_global_ips": true,
  "http_request_block_regex": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "increase_note_size_limit": false,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Vaultwarden",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "***",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 100000,
  "push_enabled": false,
  "push_identity_uri": "https://identity.bitwarden.com",
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.com",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": true,
  "signups_allowed": true,
  "signups_domains_whitelist": "",
  "signups_verify": true,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": "Login",
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "****************",
  "smtp_from_name": "Lennox",
  "smtp_host": "***********",
  "smtp_password": "***",
  "smtp_port": 587,
  "smtp_security": "force_tls",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": "****************",
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "user_send_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>

### Logs
2024-09-26 22:27:42.051272+08:002024-09-26T22:27:42.051272335+08:00
2024-09-26 22:27:42.052163+08:00[2024-09-26 22:27:42.052][vaultwarden::api::core::two_factor][ERROR] Error sending incomplete 2FA email: SMTP error: response error: error Tag at: 
2024-09-26 22:27:42.052201+08:002024-09-26T22:27:42.052201428+08:00
2024-09-26 22:27:46.764779+08:00[2024-09-26 22:27:46.764][request][INFO] GET /admin
2024-09-26 22:27:46.766450+08:00[2024-09-26 22:27:46.766][response][INFO] (admin_page) GET /admin/ => 200 OK
2024-09-26 22:27:49.371166+08:00[2024-09-26 22:27:49.371][request][INFO] POST /admin/config
2024-09-26 22:27:49.371303+08:00[NOTICE] You are using a plain text `ADMIN_TOKEN` which is insecure.
2024-09-26 22:27:49.371338+08:00Please generate a secure Argon2 PHC string by using `vaultwarden hash` or `argon2`.
2024-09-26 22:27:49.371362+08:00See: https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page#secure-the-admin_token
2024-09-26 22:27:49.371379+08:002024-09-26T22:27:49.371379562+08:00
2024-09-26 22:27:49.371456+08:00[2024-09-26 22:27:49.371][response][INFO] (post_config) POST /admin/config => 200 OK
2024-09-26 22:27:50.505078+08:00[2024-09-26 22:27:50.504][request][INFO] GET /admin
2024-09-26 22:27:50.506459+08:00[2024-09-26 22:27:50.506][response][INFO] (admin_page) GET /admin/ => 200 OK
2024-09-26 22:27:51.921317+08:00[2024-09-26 22:27:51.921][request][INFO] GET /admin/diagnostics
2024-09-26 22:27:53.667678+08:00[2024-09-26 22:27:53.667][response][INFO] (diagnostics) GET /admin/diagnostics => 200 OK
2024-09-26 22:27:57.468110+08:00[2024-09-26 22:27:57.467][request][INFO] GET /admin/diagnostics/config
2024-09-26 22:27:57.468200+08:00[2024-09-26 22:27:57.468][response][INFO] (get_diagnostics_config) GET /admin/diagnostics/config => 200 OK
2024-09-26 22:28:07.749402+08:00[2024-09-26 22:28:07.749][request][INFO] GET /admin
2024-09-26 22:28:07.751238+08:00[2024-09-26 22:28:07.751][response][INFO] (admin_page) GET /admin/ => 200 OK
2024-09-26 22:28:41.083031+08:00[2024-09-26 22:28:41.082][vaultwarden::api::core::two_factor][INFO] User ********************@outlook.com did not complete a 2FA login within the configured time limit. IP: ***********
2024-09-26 22:28:41.148543+08:00[2024-09-26 22:28:41.148][vaultwarden::mail][ERROR] SMTP error: Connection error: Connection error: error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:354:
2024-09-26 22:28:41.149330+08:00[2024-09-26 22:28:41.149][vaultwarden::api::core::two_factor][ERROR] Error sending incomplete 2FA email: SMTP error: Connection error: Connection error: error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:354:
2024-09-26 22:28:41.149602+08:00[2024-09-26 22:28:41.149][vaultwarden::api::core::two_factor][INFO] User ************@outlook.com did not complete a 2FA login within the configured time limit. IP: **************************
2024-09-26 22:28:42.027247+08:00[2024-09-26 22:28:42.026][vaultwarden::mail][ERROR] SMTP error: response error: error Tag at: 
2024-09-26 22:28:42.027338+08:002024-09-26T22:28:42.027338615+08:00
2024-09-26 22:28:42.028019+08:00[2024-09-26 22:28:42.027][vaultwarden::api::core::two_factor][ERROR] Error sending incomplete 2FA email: SMTP error: response error: error Tag at: 
2024-09-26 22:28:42.028048+08:002024-09-26T22:28:42.028048199+08:00

**Comment by CJSen** [comment]
> I have the same problem
> 
> ### Your environment (Generated via diagnostics page)
> * Vaultwarden version: v1.32.0
> * Web-vault version: v2024.6.2b
> * OS/Arch: linux/x86_64
> * Running within a container: false (Base: Not applicable)
> * Environment settings overridden: true
> * Uses a reverse proxy: false
> * Internet access: true
> * Internet access via a proxy: false
> * DNS Check: true
> * Browser/Server Time Check: true
> * Server/NTP Time Check: true
> * Domain Configuration Check: false
> * HTTPS Check: true
> * Database type: PostgreSQL
> * Database version: PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
> * Clients used:
> * Reverse proxy and version:
> * Other relevant information:
> 
> ### Config (Generated via diagnostics page)
> Show Running Config
> **Environment settings which are overridden:** ADMIN_TOKEN
> 
> ```json
> {
>   "_duo_akey": null,
>   "_enable_duo": false,
>   "_enable_email_2fa": true,
>   "_enable_smtp": true,
>   "_enable_yubico": true,
>   "_icon_service_csp": "",
>   "_icon_service_url": "",
>   "_ip_header_enabled": true,
>   "_max_note_size": 10000,
>   "_smtp_img_src": "cid:",
>   "admin_ratelimit_max_burst": 3,
>   "admin_ratelimit_seconds": 300,
>   "admin_session_lifetime": 20,
>   "admin_token": "***",
>   "allowed_iframe_ancestors": "",
>   "attachments_folder": "data/attachments",
>   "auth_request_purge_schedule": "30 * * * * *",
>   "authenticator_disable_time_drift": false,
>   "data_folder": "data",
>   "database_conn_init": "",
>   "database_max_conns": 10,
>   "database_timeout": 30,
>   "database_url": "********://**************************************************************************************************",
>   "db_connection_retries": 15,
>   "disable_2fa_remember": false,
>   "disable_admin_token": false,
>   "disable_icon_download": false,
>   "domain": "*****://***************************",
>   "domain_origin": "*****://***************************",
>   "domain_path": "",
>   "domain_set": true,
>   "duo_context_purge_schedule": "30 * * * * *",
>   "duo_host": null,
>   "duo_ikey": null,
>   "duo_skey": null,
>   "duo_use_iframe": false,
>   "email_2fa_auto_fallback": false,
>   "email_2fa_enforce_on_verified_invite": false,
>   "email_attempts_limit": 3,
>   "email_change_allowed": true,
>   "email_expiration_time": 600,
>   "email_token_size": 6,
>   "emergency_access_allowed": true,
>   "emergency_notification_reminder_schedule": "0 3 * * * *",
>   "emergency_request_timeout_schedule": "0 7 * * * *",
>   "enable_db_wal": true,
>   "enable_websocket": true,
>   "event_cleanup_schedule": "0 10 0 * * *",
>   "events_days_retain": null,
>   "experimental_client_feature_flags": "fido2-vault-credentials",
>   "extended_logging": true,
>   "helo_name": "*********",
>   "hibp_api_key": null,
>   "http_request_block_non_global_ips": true,
>   "http_request_block_regex": null,
>   "icon_blacklist_non_global_ips": true,
>   "icon_blacklist_regex": null,
>   "icon_cache_folder": "data/icon_cache",
>   "icon_cache_negttl": 259200,
>   "icon_cache_ttl": 2592000,
>   "icon_download_timeout": 10,
>   "icon_redirect_code": 302,
>   "icon_service": "internal",
>   "incomplete_2fa_schedule": "30 * * * * *",
>   "incomplete_2fa_time_limit": 3,
>   "increase_note_size_limit": false,
>   "invitation_expiration_hours": 120,
>   "invitation_org_name": "Vaultwarden",
>   "invitations_allowed": true,
>   "ip_header": "X-Real-IP",
>   "job_poll_interval_ms": 30000,
>   "log_file": null,
>   "log_level": "info",
>   "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
>   "login_ratelimit_max_burst": 10,
>   "login_ratelimit_seconds": 60,
>   "org_attachment_limit": null,
>   "org_creation_users": "***",
>   "org_events_enabled": false,
>   "org_groups_enabled": false,
>   "password_hints_allowed": true,
>   "password_iterations": 100000,
>   "push_enabled": false,
>   "push_identity_uri": "https://identity.bitwarden.com",
>   "push_installation_id": "***",
>   "push_installation_key": "***",
>   "push_relay_uri": "https://push.bitwarden.com",
>   "reload_templates": false,
>   "require_device_email": false,
>   "rsa_key_filename": "data/rsa_key",
>   "send_purge_schedule": "0 5 * * * *",
>   "sendmail_command": null,
>   "sends_allowed": true,
>   "sends_folder": "data/sends",
>   "show_password_hint": true,
>   "signups_allowed": true,
>   "signups_domains_whitelist": "",
>   "signups_verify": true,
>   "signups_verify_resend_limit": 6,
>   "signups_verify_resend_time": 3600,
>   "smtp_accept_invalid_certs": false,
>   "smtp_accept_invalid_hostnames": false,
>   "smtp_auth_mechanism": "Login",
>   "smtp_debug": false,
>   "smtp_embed_images": true,
>   "smtp_explicit_tls": null,
>   "smtp_from": "****************",
>   "smtp_from_name": "Lennox",
>   "smtp_host": "***********",
>   "smtp_password": "***",
>   "smtp_port": 587,
>   "smtp_security": "force_tls",
>   "smtp_ssl": null,
>   "smtp_timeout": 15,
>   "smtp_username": "****************",
>   "templates_folder": "data/templates",
>   "tmp_folder": "data/tmp",
>   "trash_auto_delete_days": null,
>   "trash_purge_schedule": "0 5 0 * * *",
>   "use_sendmail": false,
>   "use_syslog": false,
>   "user_attachment_limit": null,
>   "user_send_limit": null,
>   "web_vault_enabled": true,
>   "web_vault_folder": "web-vault/",
>   "yubico_client_id": null,
>   "yubico_secret_key": null,
>   "yubico_server": null
> }
> ```
> 
> ### Logs
> 2024-09-26 22:27:42.051272+08:002024-09-26T22:27:42.051272335+08:00 2024-09-26 22:27:42.052163+08:00[2024-09-26 22:27:42.052][vaultwarden::api::core::two_factor][ERROR] Error sending incomplete 2FA email: SMTP error: response error: error Tag at: � 2024-09-26 22:27:42.052201+08:002024-09-26T22:27:42.052201428+08:00 2024-09-26 22:27:46.764779+08:00[2024-09-26 22:27:46.764][request][INFO] GET /admin 2024-09-26 22:27:46.766450+08:00[2024-09-26 22:27:46.766][response][INFO] (admin_page) GET /admin/ => 200 OK 2024-09-26 22:27:49.371166+08:00[2024-09-26 22:27:49.371][request][INFO] POST /admin/config 2024-09-26 22:27:49.371303+08:00[NOTICE] You are using a plain text `ADMIN_TOKEN` which is insecure. 2024-09-26 22:27:49.371338+08:00Please generate a secure Argon2 PHC string by using `vaultwarden hash` or `argon2`. 2024-09-26 22:27:49.371362+08:00See: https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page#secure-the-admin_token 2024-09-26 22:27:49.371379+08:002024-09-26T22:27:49.371379562+08:00 2024-09-26 22:27:49.371456+08:00[2024-09-26 22:27:49.371][response][INFO] (post_config) POST /admin/config => 200 OK 2024-09-26 22:27:50.505078+08:00[2024-09-26 22:27:50.504][request][INFO] GET /admin 2024-09-26 22:27:50.506459+08:00[2024-09-26 22:27:50.506][response][INFO] (admin_page) GET /admin/ => 200 OK 2024-09-26 22:27:51.921317+08:00[2024-09-26 22:27:51.921][request][INFO] GET /admin/diagnostics 2024-09-26 22:27:53.667678+08:00[2024-09-26 22:27:53.667][response][INFO] (diagnostics) GET /admin/diagnostics => 200 OK 2024-09-26 22:27:57.468110+08:00[2024-09-26 22:27:57.467][request][INFO] GET /admin/diagnostics/config 2024-09-26 22:27:57.468200+08:00[2024-09-26 22:27:57.468][response][INFO] (get_diagnostics_config) GET /admin/diagnostics/config => 200 OK 2024-09-26 22:28:07.749402+08:00[2024-09-26 22:28:07.749][request][INFO] GET /admin 2024-09-26 22:28:07.751238+08:00[2024-09-26 22:28:07.751][response][INFO] (admin_page) GET /admin/ => 200 OK 2024-09-26 22:28:41.083031+08:00[2024-09-26 22:28:41.082][vaultwarden::api::core::two_factor][INFO] User ********************@outlook.com did not complete a 2FA login within the configured time limit. IP: *********** 2024-09-26 22:28:41.148543+08:00[2024-09-26 22:28:41.148][vaultwarden::mail][ERROR] SMTP error: Connection error: Connection error: error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:354: 2024-09-26 22:28:41.149330+08:00[2024-09-26 22:28:41.149][vaultwarden::api::core::two_factor][ERROR] Error sending incomplete 2FA email: SMTP error: Connection error: Connection error: error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:354: 2024-09-26 22:28:41.149602+08:00[2024-09-26 22:28:41.149][vaultwarden::api::core::two_factor][INFO] User ************@outlook.com did not complete a 2FA login within the configured time limit. IP: ************************** 2024-09-26 22:28:42.027247+08:00[2024-09-26 22:28:42.026][vaultwarden::mail][ERROR] SMTP error: response error: error Tag at: � 2024-09-26 22:28:42.027338+08:002024-09-26T22:28:42.027338615+08:00 2024-09-26 22:28:42.028019+08:00[2024-09-26 22:28:42.027][vaultwarden::api::core::two_factor][ERROR] Error sending incomplete 2FA email: SMTP error: response error: error Tag at: � 2024-09-26 22:28:42.028048+08:002024-09-26T22:28:42.028048199+08:00
> 
> ### Screenshots
> ![image](https://private-user-images.githubusercontent.com/60182856/371189198-c02d6fcf-646a-45a9-ae36-151fdfc015ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjE0ODYsIm5iZiI6MTcyNzM2MTE4NiwicGF0aCI6Ii82MDE4Mjg1Ni8zNzExODkxOTgtYzAyZDZmY2YtNjQ2YS00NWE5LWFlMzYtMTUxZmRmYzAxNWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE0MzMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxOTMzMmExODhjNzU3ZGVkYWZhNWMyODEyMzgwY2EyZTcwZWM0NjFkNDNkZThmYmZlZTBmYzExNGFiODQwNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Reqqzujn0JLeuF_aa_4-uJhXG_WDu9vMHryyYmFLyow)

Hey, brother, is your smtp server also QQ mailbox?

**Comment by CJSen** [comment]
@LTI-Lennox Hey bro, is your smtp server also QQ mailbox?

**Comment by LTI-Lennox** [comment]
> @LTI-Lennox Hey bro, is your smtp server also QQ mailbox?
yes, my mailbox has exploded
![image](https://github.com/user-attachments/assets/33d582f8-7912-429d-83b3-db8ba73c05e8)

**Comment by CJSen** [comment]
@LTI-Lennox A touch of the same, me too. A temporary solution:
1. enter the admin background, in the "SMTP Email Settings" will be closed smtp
2. If you can't log in to your bitwarden account, you can also disable 2FA for the corresponding account in "Users" on the admin page.
3. Before the above operation, please remember to backup your password data!
![image](https://github.com/user-attachments/assets/3a5e2142-4545-414c-a409-938233328ace)

**Comment by BlackDex** [comment]
I Would say to report this to qq actually. This seems an issue with the implementation of there SMTP server.
It's a bad idea to add exceptions for specific errors like this into our code.

You could try to add a custom mail-proxy in between maybe? But good chance it also might generate errors.
Since this is really something coming from the remote mail server, and not something which is a specific bug on the Vaultwarden side, I'm going to move this to a discussion.
