### ISSUE TITLE
Not syncing with Safari Browser Extension on macOS Sequoia

### ISSUE THREAD

**Issue by ctschach** [dani-garcia/vaultwarden#4995]
### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.32.0
* Web-vault version: v2024.6.2b
* OS/Arch: linux/x86_64
* Running within a container: true (Base: Debian)
* Environment settings overridden: true
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.46.0
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** DOMAIN, ADMIN_TOKEN

```json
{
  "_duo_akey": null,
  "_enable_duo": false,
  "_enable_email_2fa": true,
  "_enable_smtp": true,
  "_enable_yubico": false,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_max_note_size": 10000,
  "_smtp_img_src": "cid:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "auth_request_purge_schedule": "30 * * * * *",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "***************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://***********************",
  "domain_origin": "*****://***********************",
  "domain_path": "",
  "domain_set": true,
  "duo_context_purge_schedule": "30 * * * * *",
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "duo_use_iframe": false,
  "email_2fa_auto_fallback": false,
  "email_2fa_enforce_on_verified_invite": false,
  "email_attempts_limit": 3,
  "email_change_allowed": true,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "enable_websocket": true,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "experimental_client_feature_flags": "fido2-vault-credentials",
  "extended_logging": true,
  "helo_name": "****************",
  "hibp_api_key": null,
  "http_request_block_non_global_ips": true,
  "http_request_block_regex": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "increase_note_size_limit": false,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Vaultwarden",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": "/data/vaultwarden.log",
  "log_level": "info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 100000,
  "push_enabled": true,
  "push_identity_uri": "https://identity.bitwarden.eu",
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.eu",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": true,
  "signups_domains_whitelist": "",
  "signups_verify": true,
  "signups_verify_resend_limit": 2,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "***********************",
  "smtp_from_name": "vaultwarden@xxxxxxxnet",
  "smtp_host": "****************",
  "smtp_password": "***",
  "smtp_port": 465,
  "smtp_security": "force_tls",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": "****",
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "user_send_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>

### Vaultwarden Build Version

1.32.0

### Deployment method

Official Container Image

### Reverse Proxy

apache/2.4.52

### Host/Server Operating System

Linux

### Operating System Version

Ubuntu 22.04LTS

### Clients

Browser Extension, Desktop, iOS

### Client Version

2024.8.2 (29359) - via MacApp Store

### Steps To Reproduce

Sync via Safari Browser Extension does not work. No entries are shown. If you manually initiate  the Sync via:

"Einstellungen -> Tresor -> Synchronisierung -> Jetzt Synchronisieren"

you'll get the error message:

"Synchronisierung Fehlgeschlagen"

### Expected Result

Sync the vault and show entries in the Safari extension

### Actual Result

Safari Extension give an error when Syncing, while the Chrome extension on the same machine works fine. This behaviour happens on two independent Mac computers.

### Additional Context

The Sync via Safari works fine with the official Bitwarden Server. This is why I think the problem is based on the server.

**Comment by BlackDex** [comment]
What are the logs of Vaultwarden (already asked in the steps above).

**Comment by ctschach** [comment]
Sorry, missed this. Here are the log entries after I entered the password on the web extension:

```
[2024-09-26 12:01:13.712][request][INFO] GET /notifications/hub?access_token=xxxxxxiJKV1QiL
[2024-09-26 12:01:13.712][vaultwarden::api::notifications][INFO] Accepting Rocket WS connection from 84.172.17.xx
[2024-09-26 12:01:13.713][response][INFO] (websockets_hub) GET /notifications/hub?<data..> => 200 OK
[2024-09-26 12:01:13.726][request][INFO] POST /identity/connect/token
[2024-09-26 12:01:13.727][response][INFO] (login) POST /identity/connect/token => 200 OK
[2024-09-26 12:01:13.762][request][INFO] GET /api/sync
[2024-09-26 12:01:13.987][response][INFO] (sync) GET /api/sync?<data..> => 200 OK
```

When I manually initiate the vault sync, I only see this. Directly after the last entry, the error is shown in the extension.

```
[2024-09-26 12:03:44.492][request][INFO] POST /identity/connect/token
[2024-09-26 12:03:44.494][response][INFO] (login) POST /identity/connect/token => 200 OK
[2024-09-26 12:03:44.543][request][INFO] GET /api/sync
[2024-09-26 12:03:44.783][response][INFO] (sync) GET /api/sync?<data..> => 200 OK
```

**Comment by BlackDex** [comment]
Must be sometime in the vault, or a possible issue with the safari extension.

I don't know if the safari browser has an option see errors of the extension.

**Comment by ctschach** [comment]
Yes, you can, but it doesn't seems to have any helpful information

![Bildschirmfoto 2024-09-26 um 18 11 50](https://github.com/user-attachments/assets/acfb82d6-1df2-4216-a318-690cc1e2df2d)

![Bildschirmfoto 2024-09-26 um 18 10 17](https://github.com/user-attachments/assets/32c62d19-7b26-4dce-a6f0-698ddb6c8644)

And the two assets that have been downloaded both contain valid data.

**Comment by ctschach** [comment]
So I fixed the issue....

I had around 1.000+ entries in the Trash. Looks like the trash is not emptied automatically. Once I permanently deleted those entires, the Safari Extension synced without any issues. 

I had another user on the Bitwarden community who could solve his sync issues with the exact same steps.

**Comment by BlackDex** [comment]
Probably `testing` would have solved the issues as well. 

If trash is not emptied automatically, then you probably have the cron jobs disabled.

**Comment by BlackDex** [comment]
Closing as resolved
