### ISSUE TITLE
Plain text organization invite URL is broken

### ISSUE THREAD

**Issue by z3ntu** [dani-garcia/vaultwarden#5097]
### Vaultwarden Support String

Admin mode is not enabled, should not be relevant

### Vaultwarden Build Version

1.32.1

### Deployment method

OS Package (apt, yum/dnf, pacman, apk, nix, ...)

### Reverse Proxy

nginx 1.22.1

### Host/Server Operating System

Linux

### Clients

Web Vault

### Steps To Reproduce

1. Invite a user to an organization
2. Check the link received via email for the invited user ("You have been invited to join the test orga organization. ")

### Expected Result

The URL should be properly formed in both HTML and plain text variant, like `https://vaultwarden.example.org/#/accept-organization/?email=test%40example.org&organizationName=test+orga&organizationId=<>&organizationUserId=<>&token=<>`

### Actual Result

The URL is only correctly formed in the HTML variant, in the plain text variant it reads

`https://vaultwarden.example.org/#/accept-organization/?email&#x3D;test%40example.org&amp;organizationName&#x3D;test+orga&amp;organizationId&#x3D;<>&amp;organizationUserId&#x3D;<>&amp;token&#x3D;<>`

And when you click this link you get "Unable to accept invitation. Ask an organization admin to send a new invitation."

**Comment by BlackDex** [comment]
Indeed, and solved via #5100

**Comment by z3ntu** [comment]
Thanks for the quick fix, appreciate it!
