### ISSUE TITLE
vaultwarden refuses to connect to Bitwarden iOS application

### ISSUE THREAD

**Issue by acagastya** [dani-garcia/vaultwarden#5108]
### Vaultwarden Support String

Unable to find it.

### Vaultwarden Build Version

v2.19.0, v2024.3.1

### Deployment method

Build from source

### Reverse Proxy

nginx

### Host/Server Operating System

Linux

### Operating System Version

Debian

### Clients

iOS

### Client Version

2024.9.2

### Steps To Reproduce

Apologies if I might have been late to get to know this, but after updating the Bitwarden iOS application (from Bitwarden company) and self-hosted vaultwarden, I am unable to log in to the mobile application, getting "An error occurred." and it is stuck there.

### Expected Result

It should log me in.

### Actual Result

Getting an error alert saying "An error has occurred."

**Comment by BlackDex** [comment]
I would suggest to search and read first.
We even mentioned during the creation of this issue that you need to make sure you are using the latest version of Vaultwarden, which you are not.

Update Vaultwarden!

**Comment by WyInnovate** [comment]
@BlackDex 
IOS 18.1 22B83
IOS APP 2024.9.2
Vaultwarden Build Version 1.32.3
An error has occurred
How should I identify the problem?

**Comment by BlackDex** [comment]
@WyInnovate i have no clue to be honest.
Just be sure you have the latest version installed off both Vaultwarden and the Bitwarden client. 

You can try to fully delete the mobile client with all data and login again. But the chance is small it will help, but if you do not try it you will never know. 

And then the only way to know is by deleting vault items 1 by 1 from your account and directly from the trash to see when it will sync again. Then at least the last vault item you deleted had an issue, but others before could too or course.

And to help us, we would need to know te database record of those items which prevents the sync to work.

**Comment by WyInnovate** [comment]
> @WyInnovate i have no clue to be honest. Just be sure you have the latest version installed off both Vaultwarden and the Bitwarden client.
> 
> You can try to fully delete the mobile client with all data and login again. But the chance is small it will help, but if you do not try it you will never know.
> 
> And then the only way to know is by deleting vault items 1 by 1 from your account and directly from the trash to see when it will sync again. Then at least the last vault item you deleted had an issue, but others before could too or course.
> 
> And to help us, we would need to know te database record of those items which prevents the sync to work.

Sorry, I caught the packet and found that it was an issue with CloudFlare. Upon checking, I discovered that it was blocked by a WAF
