### ISSUE TITLE
AuthRequest doesn't exit

### ISSUE THREAD

**Issue by amduong** [dani-garcia/vaultwarden#5194]
### Vaultwarden Support String

When I tried login with device. The "AuthRequest doesn't exit" show up on my device

### Vaultwarden Build Version

1.32.4

### Deployment method

Official Container Image

### Reverse Proxy

n/a

### Host/Server Operating System

Linux

### Operating System Version

Linux 5.10.103-v7l+ armv7l

### Clients

Browser Extension

### Client Version

Firefox 132.0.1

### Steps To Reproduce

1. Go to bitwarden firefox extention 2024.10.1
2. Log in with device
3. Go to the device 
4. open Bitwarden phone app
5. Go to settings ->Account security -> Pending login requests -> click on Fingerprint phrase
6. I will show "AuthRequest doesn't exist instead of log me in as normal 

### Expected Result

once I click the Fingerprint phrase on my device it has to log me in on the browser extension  

### Actual Result

Instead of log me in on the browser extension it shows "AuthRequest doesn't exist' 

### Screenshots or Videos

![Screenshot_20241113-101727](https://github.com/user-attachments/assets/255ace56-be00-47c9-847c-8fefea1f9b15)

**Comment by BlackDex** [comment]
Already resolved in the main branch and `testing` tagged images.
