### ISSUE TITLE
Rust stable

### ISSUE THREAD

**Issue by djmattyg007** [dani-garcia/vaultwarden#712]
It would be great to be able to build this with a stable version of rust. Installation of stable rust is a lot more straightforward, and would make it easier to convince Linux distros to include bitwarden_rs in their official repositories.

**Comment by mqus** [comment]
The main reason is probably this: https://github.com/SergioBenitez/Rocket/issues/19
This could be solved by 

1. stabilizing https://github.com/rust-lang/rust/issues/54727 
2. somehow patch rocket to work without the remaining feature
3. abandoning rocket and using another webserver like actix-web instead.

I'm not involved with writing code in any of these projects(including here) but it seems that all of those options are neither easy nor fast to do, so there is still a way to go before compiling bitwarden_rs with stable rust is possible.

**Comment by BlackDex** [comment]
The end goal is to have it being able to have it compiled using the stable version.
But indeed the Rocket chain is currently one of the bottlenecks.
And there are also some dependencies, like pear/pear_codegen, which report to need a nightly but probably can use the current v1.38 stable. And some crates and bitwarden_rs it self are using some feature's which aren't in a stable release yet. Not even the v1.38, so we currently are stuck on the nightly release.

**Comment by djmattyg007** [comment]
Thank you everyone for the insight, it's really appreciated!

Does this help at all? https://blog.rust-lang.org/2019/11/07/Rust-1.39.0.html

**Comment by evitalis** [comment]
Any updates on this? I think Rocket was getting close to stable compatibility but not sure what else still needs nightly. On my platforms I do not have access to docker and prefer to use stable Rust if I can, meaning for the moment I can't really use the project despite wanting to try it out.

**Comment by dani-garcia** [comment]
Well the proc-macro hygiene is on track to be stabilized for next Rust release sometime this week, and there are some Span related things in the pear library that are still not stabilized, but those are only to have nicer compile errors, so they might be moved behind a feature gate to make it compile in stable rust, and nightly can be used for nicer errors.

Other than that, I assume the next rocket release will also include the async stuff seeing as it has been merged into master, so it might take a bit longer to iron out all it's issues.

On our side, we have two nightly features enabled, `try_trait` and `ip`, but they aren't essential so I'll try to remove them before any Rocket stable release.

**Comment by montdidier** [comment]
Looking forward to this happening.

**Comment by hgaiser** [comment]
I think this issue has been resolved? At least for me it compiles using stable (1.55).

**Comment by hgaiser** [comment]
That's what I mean, for me it seems to work on `main` branch, with `--feature sqlite` at least. Maybe there are other features with additional dependencies that fail?

**Comment by hgaiser** [comment]
Ah I see what happened: there is a nightly toolchain defined in [`rust-toolchain`](https://github.com/dani-garcia/vaultwarden/blob/main/rust-toolchain). I was not aware of that, I am using stable by default. Apologies for the confusion.

**Comment by BlackDex** [comment]
As an update, there is a new `async` branch available. And i also have a PR #2143 open with some updates from `main`, which currently is outdated already, but it is at least something.

**Comment by BlackDex** [comment]
This is now added and enabled via #2276.

**Comment by montdidier** [comment]
Any view on when this might make it into an official release?

**Comment by BlackDex** [comment]
It currently is in the `main` branch, and you are able to test it by using the `testing` tagged images.
We probably want to have some time for testing, and fix some bugs before we even release a version using these changes.
Since, they are a lot.

**Comment by montdidier** [comment]
Ok. I will be trying it out this week. Is there is a list of know issues beyond the github issues list?

**Comment by BlackDex** [comment]
We only have GitHub for issue tracking.

There is a ticket for some gathering of issues/features which are open #246 
Maybe there are some items on the [Dicussions](https://github.com/dani-garcia/vaultwarden/discussions) page or at our [Forum](https://vaultwarden.discourse.group/) but those arn't tracked then.

Also, if you are talking about specific issues with the new build which is able to build with stable, then until now we have no new reports regarding this. I have been running it for a while now, and didn't encountered any strange issues as of yet.

**Comment by montdidier** [comment]
I just realised you mean the docker images. Ok. I'm working towards building the [offical alpine package](https://gitlab.alpinelinux.org/alpine/aports/-/tree/master/testing/vaultwarden), so I will just make an alpine package build from master then to test it.

**Comment by BlackDex** [comment]
Yea, the `main` branch is the one the new version will be using.
Small note on the APKBUILD, i would suggest to remove the `abort=` statement. That could break the binary, and makes issues harder to debug
